project_id = "etpiadoqryvtlpmiuxia"

[functions.send-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.upload]
verify_jwt = false

[functions.contract-expiry-reminder]
verify_jwt = false

[functions.worker-portal]
verify_jwt = false

[functions.contact-enquiry]
verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false
