import type { UaeListedJob } from '@/lib/uaeListedJobs';

export type TradeQuizOptionId = 'A' | 'B' | 'C' | 'D';

export type TradeQuizOption = {
  id: TradeQuizOptionId;
  en: string;
  hi: string;
};

export type TradeQuizQuestion = {
  question: string;
  question_hi: string;
  options: TradeQuizOption[];
  correct: TradeQuizOptionId;
};

function q(
  question: string,
  question_hi: string,
  a: [string, string],
  b: [string, string],
  c: [string, string],
  d: [string, string],
  correct: TradeQuizOptionId,
): TradeQuizQuestion {
  return {
    question,
    question_hi,
    options: [
      { id: 'A', en: a[0], hi: a[1] },
      { id: 'B', en: b[0], hi: b[1] },
      { id: 'C', en: c[0], hi: c[1] },
      { id: 'D', en: d[0], hi: d[1] },
    ],
    correct,
  };
}

/** Shared Dubai cleaner screening — same paper for male and female listings. */
const CLEANER_TRADE_KNOWLEDGE: TradeQuizQuestion[] = [
  q(
    'What is the main duty of a cleaner?',
    'क्लीनर का मुख्य काम क्या होता है?',
    ['Cleaning and maintaining cleanliness', 'सफाई करना और स्वच्छता बनाए रखना'],
    ['Repairing electrical machines', 'इलेक्ट्रिकल मशीनों की मरम्मत करना'],
    ['Welding metal', 'धातु वेल्ड करना'],
    ['Installing pipes', 'पाइप लगाना'],
    'A',
  ),
  q(
    'Which tool is commonly used to clean floors?',
    'फर्श साफ करने के लिए सामान्यतः किस उपकरण का उपयोग किया जाता है?',
    ['Mop', 'पोछा'],
    ['Welding machine', 'वेल्डिंग मशीन'],
    ['Pipe wrench', 'पाइप रिंच'],
    ['Hammer', 'हथौड़ा'],
    'A',
  ),
  q(
    'What is a broom mainly used for?',
    'झाड़ू का मुख्य उपयोग किस लिए किया जाता है?',
    ['Sweeping dust and dirt', 'धूल और गंदगी साफ करने के लिए'],
    ['Washing windows', 'खिड़कियां धोने के लिए'],
    ['Cutting materials', 'सामग्री काटने के लिए'],
    ['Repairing machines', 'मशीनों की मरम्मत करने के लिए'],
    'A',
  ),
  q(
    'Why should cleaning chemicals be used carefully?',
    'सफाई के केमिकल का सावधानी से उपयोग क्यों करना चाहिए?',
    ['They may cause harm if used incorrectly', 'गलत तरीके से उपयोग करने पर वे नुकसान पहुंचा सकते हैं'],
    ['They make the floor heavier', 'वे फर्श को भारी बनाते हैं'],
    ['They increase electricity', 'वे बिजली बढ़ाते हैं'],
    ['They make tools stronger', 'वे उपकरणों को मजबूत बनाते हैं'],
    'A',
  ),
  q(
    'What should you wear when handling cleaning chemicals?',
    'सफाई के केमिकल को संभालते समय क्या पहनना चाहिए?',
    ['Appropriate protective gloves', 'उचित सुरक्षा ग्लव्स'],
    ['Slippers only', 'केवल चप्पल'],
    ['No protection', 'कोई सुरक्षा नहीं'],
    ['Loose jewellery', 'ढीली ज्वेलरी'],
    'A',
  ),
  q(
    'What should you do if the floor is wet after cleaning?',
    'सफाई के बाद यदि फर्श गीला है तो क्या करना चाहिए?',
    ['Put a warning sign and allow it to dry', 'चेतावनी संकेत लगाएं और फर्श को सूखने दें'],
    ['Leave it without any warning', 'बिना चेतावनी के छोड़ दें'],
    ['Pour more water', 'और पानी डालें'],
    ['Cover it with dust', 'उस पर धूल डालें'],
    'A',
  ),
  q(
    'What is a vacuum cleaner used for?',
    'वैक्यूम क्लीनर का उपयोग किस लिए किया जाता है?',
    ['Removing dust and dirt', 'धूल और गंदगी हटाने के लिए'],
    ['Cutting metal', 'धातु काटने के लिए'],
    ['Painting walls', 'दीवार पेंट करने के लिए'],
    ['Carrying water', 'पानी ले जाने के लिए'],
    'A',
  ),
  q(
    'What should you do with waste after collecting it?',
    'कचरा इकट्ठा करने के बाद क्या करना चाहिए?',
    ['Put it in the appropriate waste bin or disposal area', 'उसे उचित कूड़ेदान या निर्धारित स्थान पर डालना'],
    ['Leave it on the floor', 'फर्श पर छोड़ देना'],
    ['Hide it behind furniture', 'फर्नीचर के पीछे छिपा देना'],
    ['Throw it anywhere', 'कहीं भी फेंक देना'],
    'A',
  ),
  q(
    'Why is hand hygiene important for a cleaner?',
    'क्लीनर के लिए हाथों की स्वच्छता क्यों जरूरी है?',
    ['To maintain hygiene and reduce the spread of germs', 'स्वच्छता बनाए रखने और कीटाणुओं के फैलाव को कम करने के लिए'],
    ['To make hands stronger', 'हाथों को मजबूत बनाने के लिए'],
    ['To increase cleaning speed', 'सफाई की गति बढ़ाने के लिए'],
    ['To save cleaning chemicals', 'सफाई के केमिकल बचाने के लिए'],
    'A',
  ),
  q(
    'What should you do if you find a broken glass while cleaning?',
    'सफाई करते समय यदि टूटा हुआ कांच मिले तो क्या करना चाहिए?',
    ['Handle it safely using appropriate protection and dispose of it properly', 'उचित सुरक्षा के साथ सावधानी से संभालकर सही तरीके से निपटाना'],
    ['Pick it up with bare hands', 'नंगे हाथों से उठाना'],
    ['Kick it away', 'उसे पैर से दूर करना'],
    ['Leave it where it is without reporting', 'बिना बताए वहीं छोड़ देना'],
    'A',
  ),
];

/** Entry-level bilingual MCQ bank — 10 questions per UAE listed trade. */
const CORE_TRADE_KNOWLEDGE_BANK = {
  Electrician: [
    q(
      'What is the main purpose of an MCB?',
      'MCB का मुख्य उद्देश्य क्या है?',
      ['To increase voltage', 'वोल्टेज बढ़ाना'],
      ['To protect the electrical circuit', 'विद्युत सर्किट की सुरक्षा करना'],
      ['To store electricity', 'बिजली को स्टोर करना'],
      ['To measure temperature', 'तापमान मापना'],
      'B',
    ),
    q(
      'What is a multimeter used for?',
      'मल्टीमीटर का उपयोग किस लिए किया जाता है?',
      ['Cutting wires', 'तार काटने के लिए'],
      ['Measuring electrical values', 'विद्युत मान मापने के लिए'],
      ['Tightening bolts', 'बोल्ट कसने के लिए'],
      ['Cutting pipes', 'पाइप काटने के लिए'],
      'B',
    ),
    q(
      'Why is earthing used in electrical systems?',
      'विद्युत सिस्टम में अर्थिंग क्यों की जाती है?',
      ['To increase electricity consumption', 'बिजली की खपत बढ़ाने के लिए'],
      ['To provide protection from electrical faults', 'विद्युत खराबी से सुरक्षा के लिए'],
      ['To make wires longer', 'तारों को लंबा करने के लिए'],
      ['To increase light brightness', 'रोशनी बढ़ाने के लिए'],
      'B',
    ),
    q(
      'What should you do before working on an electrical circuit?',
      'विद्युत सर्किट पर काम करने से पहले आपको क्या करना चाहिए?',
      ['Increase the voltage', 'वोल्टेज बढ़ाना'],
      ['Switch off/isolate the power', 'बिजली की सप्लाई बंद/आइसोलेट करना'],
      ['Touch the wire to check it', 'तार को छूकर जांचना'],
      ['Pour water on the circuit', 'सर्किट पर पानी डालना'],
      'B',
    ),
    q(
      'What is an electrical switch used for?',
      'विद्युत स्विच का उपयोग किस लिए किया जाता है?',
      ['Controlling ON/OFF of a circuit', 'सर्किट को चालू/बंद करने के लिए'],
      ['Measuring current', 'करंट मापने के लिए'],
      ['Cutting cables', 'केबल काटने के लिए'],
      ['Joining pipes', 'पाइप जोड़ने के लिए'],
      'A',
    ),
    q(
      'Which tool is commonly used to tighten electrical terminal screws?',
      'विद्युत टर्मिनल के स्क्रू कसने के लिए सामान्यतः किस उपकरण का उपयोग किया जाता है?',
      ['Screwdriver', 'स्क्रूड्राइवर'],
      ['Pipe wrench', 'पाइप रिंच'],
      ['Hammer drill', 'हैमर ड्रिल'],
      ['Hacksaw', 'हैक्सॉ'],
      'A',
    ),
    q(
      'What is an electrical cable mainly used for?',
      'विद्युत केबल का मुख्य उपयोग किस लिए होता है?',
      ['Carrying electrical current', 'विद्युत करंट ले जाने के लिए'],
      ['Carrying water', 'पानी ले जाने के लिए'],
      ['Supporting walls', 'दीवारों को सहारा देने के लिए'],
      ['Painting surfaces', 'सतहों पर पेंट करने के लिए'],
      'A',
    ),
    q(
      'What should you do if you find a damaged electrical wire?',
      'यदि आपको कोई क्षतिग्रस्त विद्युत तार मिले तो आपको क्या करना चाहिए?',
      ['Continue using it', 'उसका उपयोग जारी रखना'],
      ['Touch it with your hand', 'उसे हाथ से छूना'],
      ['Report it and repair/replace it safely', 'इसकी सूचना देकर सुरक्षित रूप से मरम्मत/बदलना'],
      ['Pour water on it', 'उस पर पानी डालना'],
      'C',
    ),
    q(
      'Which equipment protects the eyes during electrical work from flying particles?',
      'विद्युत कार्य के दौरान उड़ने वाले कणों से आंखों की सुरक्षा के लिए क्या उपयोग किया जाता है?',
      ['Safety glasses', 'सेफ्टी ग्लास'],
      ['Safety belt', 'सेफ्टी बेल्ट'],
      ['Safety shoes', 'सेफ्टी शूज़'],
      ['Ear plugs', 'ईयर प्लग'],
      'A',
    ),
    q(
      'What is a socket used for?',
      'इलेक्ट्रिकल सॉकेट का उपयोग किस लिए किया जाता है?',
      ['Connecting an electrical plug to a power supply', 'विद्युत प्लग को बिजली की सप्लाई से जोड़ने के लिए'],
      ['Cutting wires', 'तार काटने के लिए'],
      ['Measuring pipes', 'पाइप मापने के लिए'],
      ['Holding concrete', 'कंक्रीट को पकड़ने के लिए'],
      'A',
    ),
  ],

  Welder: [
    q(
      'What is welding?',
      'वेल्डिंग क्या है?',
      ['Painting metal', 'धातु पर पेंट करना'],
      ['Joining metal using heat, pressure, or both', 'गर्मी, दबाव या दोनों की सहायता से धातु जोड़ना'],
      ['Cutting wood', 'लकड़ी काटना'],
      ['Cleaning pipes', 'पाइप साफ करना'],
      'B',
    ),
    q(
      'What is a welding helmet used for?',
      'वेल्डिंग हेलमेट का उपयोग किस लिए किया जाता है?',
      ['Protecting the head and eyes from the welding arc', 'वेल्डिंग आर्क से सिर और आंखों की सुरक्षा के लिए'],
      ['Measuring metal', 'धातु मापने के लिए'],
      ['Cutting steel', 'स्टील काटने के लिए'],
      ['Carrying tools', 'उपकरण ले जाने के लिए'],
      'A',
    ),
    q(
      'What is a welding electrode used for?',
      'वेल्डिंग इलेक्ट्रोड का उपयोग किस लिए किया जाता है?',
      ['Creating the welding arc and/or providing filler metal', 'वेल्डिंग आर्क बनाने और/या फिलर मेटल देने के लिए'],
      ['Measuring temperature', 'तापमान मापने के लिए'],
      ['Cleaning the floor', 'फर्श साफ करने के लिए'],
      ['Painting metal', 'धातु पर पेंट करने के लिए'],
      'A',
    ),
    q(
      'Why are welding gloves worn?',
      'वेल्डिंग ग्लव्स क्यों पहने जाते हैं?',
      ['To protect hands from heat and sparks', 'हाथों को गर्मी और चिंगारी से बचाने के लिए'],
      ['To improve eyesight', 'दृष्टि बेहतर करने के लिए'],
      ['To measure voltage', 'वोल्टेज मापने के लिए'],
      ['To hold water', 'पानी पकड़ने के लिए'],
      'A',
    ),
    q(
      'What should you check before starting welding?',
      'वेल्डिंग शुरू करने से पहले क्या जांचना चाहिए?',
      ['Welding equipment and safety equipment', 'वेल्डिंग उपकरण और सुरक्षा उपकरण'],
      ['Refrigerator', 'फ्रिज'],
      ['Water tank', 'पानी की टंकी'],
      ['Office computer', 'ऑफिस कंप्यूटर'],
      'A',
    ),
    q(
      'Why should the welding area be kept clean?',
      'वेल्डिंग क्षेत्र को साफ क्यों रखना चाहिए?',
      ['To reduce accidents and fire hazards', 'दुर्घटना और आग के खतरे को कम करने के लिए'],
      ['To increase welding noise', 'वेल्डिंग का शोर बढ़ाने के लिए'],
      ['To make metal heavier', 'धातु को भारी बनाने के लिए'],
      ['To increase electricity use', 'बिजली की खपत बढ़ाने के लिए'],
      'A',
    ),
    q(
      'Can freshly welded metal be touched immediately?',
      'क्या अभी-अभी वेल्ड की गई धातु को तुरंत छू सकते हैं?',
      ['Yes, always', 'हां, हमेशा'],
      ['Yes, with bare hands', 'हां, नंगे हाथों से'],
      ['No, it may be very hot', 'नहीं, यह बहुत गर्म हो सकती है'],
      ['Only with water', 'केवल पानी से'],
      'C',
    ),
    q(
      'Why is ventilation important during welding?',
      'वेल्डिंग के दौरान वेंटिलेशन क्यों जरूरी है?',
      ['To reduce exposure to welding fumes', 'वेल्डिंग के धुएं के संपर्क को कम करने के लिए'],
      ['To increase sparks', 'चिंगारी बढ़ाने के लिए'],
      ['To cool the welding machine only', 'केवल वेल्डिंग मशीन को ठंडा करने के लिए'],
      ['To make the metal heavier', 'धातु को भारी बनाने के लिए'],
      'A',
    ),
    q(
      'Which tool is commonly used to remove welding slag?',
      'वेल्डिंग स्लैग हटाने के लिए सामान्यतः किस उपकरण का उपयोग किया जाता है?',
      ['Chipping hammer', 'चिपिंग हैमर'],
      ['Pipe wrench', 'पाइप रिंच'],
      ['Paint roller', 'पेंट रोलर'],
      ['Screwdriver', 'स्क्रूड्राइवर'],
      'A',
    ),
    q(
      'What should a welder wear to protect the body from sparks?',
      'चिंगारी से शरीर की सुरक्षा के लिए वेल्डर को क्या पहनना चाहिए?',
      ['Suitable protective clothing', 'उपयुक्त सुरक्षात्मक कपड़े'],
      ['Plastic shopping bag', 'प्लास्टिक बैग'],
      ['Loose synthetic clothing', 'ढीले सिंथेटिक कपड़े'],
      ['Normal sandals', 'सामान्य चप्पल'],
      'A',
    ),
  ],

  'MIG Welder': [
    q(
      'What does MIG stand for?',
      'MIG का पूरा नाम क्या है?',
      ['Metal Inert Gas', 'मेटल इनर्ट गैस'],
      ['Metal Iron Gas', 'मेटल आयरन गैस'],
      ['Manual Industrial Gas', 'मैनुअल इंडस्ट्रियल गैस'],
      ['Metal Internal Ground', 'मेटल इंटरनल ग्राउंड'],
      'A',
    ),
    q(
      'What is mainly used as the electrode in MIG welding?',
      'MIG वेल्डिंग में मुख्य रूप से इलेक्ट्रोड के रूप में क्या उपयोग किया जाता है?',
      ['Welding rod', 'वेल्डिंग रॉड'],
      ['Continuous wire', 'लगातार चलने वाली वायर'],
      ['Copper plate', 'कॉपर प्लेट'],
      ['Steel pipe', 'स्टील पाइप'],
      'B',
    ),
    q(
      'What is the main purpose of shielding gas in MIG welding?',
      'MIG वेल्डिंग में शील्डिंग गैस का मुख्य उद्देश्य क्या है?',
      ['To cool the worker', 'वर्कर को ठंडा करना'],
      ['To protect the weld from air contamination', 'वेल्ड को हवा से होने वाले प्रदूषण से बचाना'],
      ['To clean the floor', 'फर्श साफ करना'],
      ['To increase the weight of the metal', 'धातु का वजन बढ़ाना'],
      'B',
    ),
    q(
      "Which equipment protects the welder's eyes and face from the welding arc?",
      'वेल्डिंग आर्क से वेल्डर की आंखों और चेहरे की सुरक्षा के लिए कौन सा उपकरण उपयोग किया जाता है?',
      ['Safety helmet', 'सेफ्टी हेलमेट'],
      ['Welding helmet', 'वेल्डिंग हेलमेट'],
      ['Safety shoes', 'सेफ्टी शूज़'],
      ['Ear plugs', 'ईयर प्लग'],
      'B',
    ),
    q(
      'What is the purpose of the welding gun in MIG welding?',
      'MIG वेल्डिंग में वेल्डिंग गन का क्या काम होता है?',
      ['To deliver the welding wire and shielding gas', 'वेल्डिंग वायर और शील्डिंग गैस पहुंचाना'],
      ['To measure metal thickness', 'धातु की मोटाई मापना'],
      ['To cut the metal', 'धातु काटना'],
      ['To clean the welding area', 'वेल्डिंग क्षेत्र साफ करना'],
      'A',
    ),
    q(
      'What should you do before starting MIG welding?',
      'MIG वेल्डिंग शुरू करने से पहले आपको क्या करना चाहिए?',
      ['Check the welding machine, cables and PPE', 'वेल्डिंग मशीन, केबल और PPE की जांच करना'],
      ['Touch the welding wire with bare hands', 'वेल्डिंग वायर को नंगे हाथों से छूना'],
      ['Pour water on the machine', 'मशीन पर पानी डालना'],
      ['Remove the welding helmet', 'वेल्डिंग हेलमेट हटाना'],
      'A',
    ),
    q(
      'What can happen if the shielding gas flow is not proper?',
      'यदि शील्डिंग गैस का फ्लो सही नहीं है तो क्या हो सकता है?',
      ['The weld may have defects', 'वेल्ड में खराबी आ सकती है'],
      ['The metal becomes plastic', 'धातु प्लास्टिक बन जाती है'],
      ['The welding machine becomes larger', 'वेल्डिंग मशीन बड़ी हो जाती है'],
      ['Nothing can happen', 'कुछ भी नहीं होता'],
      'A',
    ),
    q(
      'Why should the welding surface be clean before welding?',
      'वेल्डिंग से पहले धातु की सतह को साफ क्यों करना चाहिए?',
      ['To improve the quality of the weld', 'वेल्ड की गुणवत्ता बेहतर करने के लिए'],
      ['To make the metal heavier', 'धातु को भारी बनाने के लिए'],
      ['To increase electricity consumption', 'बिजली की खपत बढ़ाने के लिए'],
      ['To change the metal colour', 'धातु का रंग बदलने के लिए'],
      'A',
    ),
    q(
      'What should a MIG welder do if the welding wire is not feeding properly?',
      'यदि MIG वेल्डिंग वायर सही तरीके से फीड नहीं हो रही है तो वेल्डर को क्या करना चाहिए?',
      ['Check the wire feed and equipment', 'वायर फीड और उपकरण की जांच करनी चाहिए'],
      ['Pull the wire with bare hands while welding', 'वेल्डिंग के दौरान वायर को हाथ से खींचना चाहिए'],
      ['Pour water on the wire', 'वायर पर पानी डालना चाहिए'],
      ['Continue welding without checking', 'बिना जांचे वेल्डिंग जारी रखनी चाहिए'],
      'A',
    ),
    q(
      'Why should a welder wear protective gloves?',
      'वेल्डर को सुरक्षात्मक ग्लव्स क्यों पहनने चाहिए?',
      ['To protect hands from heat, sparks and sharp metal', 'हाथों को गर्मी, चिंगारी और तेज धातु से बचाने के लिए'],
      ['To increase welding speed', 'वेल्डिंग की गति बढ़ाने के लिए'],
      ['To reduce the weight of the welding gun', 'वेल्डिंग गन का वजन कम करने के लिए'],
      ['To increase gas flow', 'गैस फ्लो बढ़ाने के लिए'],
      'A',
    ),
  ],

  'TIG Welder': [
    q(
      'What does TIG stand for?',
      'TIG का पूरा नाम क्या है?',
      ['Tungsten Inert Gas', 'टंगस्टन इनर्ट गैस'],
      ['Tungsten Industrial Gas', 'टंगस्टन इंडस्ट्रियल गैस'],
      ['Thermal Inert Gas', 'थर्मल इनर्ट गैस'],
      ['Tungsten Iron Gas', 'टंगस्टन आयरन गैस'],
      'A',
    ),
    q(
      'Which electrode is used in TIG welding?',
      'TIG वेल्डिंग में किस प्रकार का इलेक्ट्रोड उपयोग किया जाता है?',
      ['Tungsten electrode', 'टंगस्टन इलेक्ट्रोड'],
      ['Copper electrode', 'कॉपर इलेक्ट्रोड'],
      ['Aluminium electrode', 'एल्युमिनियम इलेक्ट्रोड'],
      ['Wooden electrode', 'लकड़ी का इलेक्ट्रोड'],
      'A',
    ),
    q(
      'What is the main purpose of shielding gas in TIG welding?',
      'TIG वेल्डिंग में शील्डिंग गैस का मुख्य उद्देश्य क्या है?',
      ['To protect the weld from air contamination', 'वेल्ड को हवा से होने वाले प्रदूषण से बचाना'],
      ['To cool the welding machine', 'वेल्डिंग मशीन को ठंडा करना'],
      ['To clean the floor', 'फर्श साफ करना'],
      ['To increase the weight of the metal', 'धातु का वजन बढ़ाना'],
      'A',
    ),
    q(
      'Which gas is commonly used as shielding gas in TIG welding?',
      'TIG वेल्डिंग में शील्डिंग गैस के रूप में सामान्यतः किस गैस का उपयोग किया जाता है?',
      ['Argon', 'आर्गन'],
      ['Oxygen', 'ऑक्सीजन'],
      ['Hydrogen', 'हाइड्रोजन'],
      ['Carbon dioxide only', 'केवल कार्बन डाइऑक्साइड'],
      'A',
    ),
    q(
      'What is the purpose of a TIG welding torch?',
      'TIG वेल्डिंग टॉर्च का क्या उद्देश्य है?',
      ['To hold the tungsten electrode and direct the shielding gas', 'टंगस्टन इलेक्ट्रोड को पकड़ना और शील्डिंग गैस को सही दिशा में पहुंचाना'],
      ['To measure metal thickness', 'धातु की मोटाई मापना'],
      ['To cut the metal', 'धातु काटना'],
      ['To mix welding gas', 'वेल्डिंग गैस मिलाना'],
      'A',
    ),
    q(
      'What should you wear to protect your eyes during TIG welding?',
      'TIG वेल्डिंग के दौरान आंखों की सुरक्षा के लिए क्या पहनना चाहिए?',
      ['Welding helmet', 'वेल्डिंग हेलमेट'],
      ['Normal sunglasses', 'सामान्य धूप का चश्मा'],
      ['Cotton cap', 'सूती टोपी'],
      ['Ear plugs', 'ईयर प्लग'],
      'A',
    ),
    q(
      'What is a filler rod used for in TIG welding?',
      'TIG वेल्डिंग में फिलर रॉड का उपयोग किस लिए किया जाता है?',
      ['To add additional metal to the weld when required', 'आवश्यकता होने पर वेल्ड में अतिरिक्त धातु जोड़ने के लिए'],
      ['To cool the metal', 'धातु को ठंडा करने के लिए'],
      ['To measure the weld', 'वेल्ड को मापने के लिए'],
      ['To clean the floor', 'फर्श साफ करने के लिए'],
      'A',
    ),
    q(
      'Why should the metal surface be cleaned before TIG welding?',
      'TIG वेल्डिंग से पहले धातु की सतह को साफ क्यों करना चाहिए?',
      ['To improve weld quality', 'वेल्ड की गुणवत्ता बेहतर करने के लिए'],
      ['To make the metal heavier', 'धातु को भारी बनाने के लिए'],
      ['To increase gas pressure', 'गैस का दबाव बढ़ाने के लिए'],
      ['To change the metal colour', 'धातु का रंग बदलने के लिए'],
      'A',
    ),
    q(
      'What can happen if shielding gas is not supplied properly?',
      'यदि शील्डिंग गैस सही तरीके से सप्लाई न हो तो क्या हो सकता है?',
      ['The weld can become defective or contaminated', 'वेल्ड में खराबी या प्रदूषण हो सकता है'],
      ['The metal becomes plastic', 'धातु प्लास्टिक बन जाती है'],
      ['The welding machine becomes larger', 'वेल्डिंग मशीन बड़ी हो जाती है'],
      ['Nothing happens', 'कुछ नहीं होता'],
      'A',
    ),
    q(
      'Why should a TIG welder wear protective gloves?',
      'TIG वेल्डर को सुरक्षात्मक ग्लव्स क्यों पहनने चाहिए?',
      ['To protect hands from heat, sparks and sharp metal', 'हाथों को गर्मी, चिंगारी और तेज धातु से बचाने के लिए'],
      ['To increase welding speed', 'वेल्डिंग की गति बढ़ाने के लिए'],
      ['To increase gas flow', 'गैस फ्लो बढ़ाने के लिए'],
      ['To make the welding torch lighter', 'वेल्डिंग टॉर्च को हल्का बनाने के लिए'],
      'A',
    ),
  ],

  Plumber: [
    q(
      'What is the main work of a plumber?',
      'प्लम्बर का मुख्य काम क्या होता है?',
      ['Installing and repairing pipe systems', 'पाइप सिस्टम लगाना और उसकी मरम्मत करना'],
      ['Painting cars', 'कारों पर पेंट करना'],
      ['Welding only', 'केवल वेल्डिंग करना'],
      ['Installing electrical panels', 'इलेक्ट्रिकल पैनल लगाना'],
      'A',
    ),
    q(
      'What is a pipe used for?',
      'पाइप का उपयोग किस लिए किया जाता है?',
      ['Carrying water or other fluids', 'पानी या अन्य तरल पदार्थ ले जाने के लिए'],
      ['Measuring electricity', 'बिजली मापने के लिए'],
      ['Painting walls', 'दीवारों पर पेंट करने के लिए'],
      ['Cutting wood', 'लकड़ी काटने के लिए'],
      'A',
    ),
    q(
      'What is a valve used for?',
      'वाल्व का उपयोग किस लिए किया जाता है?',
      ['Controlling or stopping fluid flow', 'तरल पदार्थ के प्रवाह को नियंत्रित या बंद करने के लिए'],
      ['Cutting wood', 'लकड़ी काटने के लिए'],
      ['Measuring temperature', 'तापमान मापने के लिए'],
      ['Mixing paint', 'पेंट मिलाने के लिए'],
      'A',
    ),
    q(
      'What is a pipe wrench used for?',
      'पाइप रिंच का उपयोग किस लिए किया जाता है?',
      ['Turning and gripping pipes', 'पाइप को पकड़ने और घुमाने के लिए'],
      ['Cutting tiles', 'टाइल काटने के लिए'],
      ['Painting walls', 'दीवार पेंट करने के लिए'],
      ['Measuring voltage', 'वोल्टेज मापने के लिए'],
      'A',
    ),
    q(
      'What is an elbow fitting used for?',
      'एल्बो फिटिंग का उपयोग किस लिए किया जाता है?',
      ['Changing the direction of a pipe', 'पाइप की दिशा बदलने के लिए'],
      ['Measuring water pressure', 'पानी का दबाव मापने के लिए'],
      ['Cutting pipes', 'पाइप काटने के लिए'],
      ['Painting pipes', 'पाइप पर पेंट करने के लिए'],
      'A',
    ),
    q(
      'What is Teflon/PTFE tape commonly used for?',
      'Teflon/PTFE टेप का सामान्य उपयोग किस लिए किया जाता है?',
      ['Sealing threaded pipe connections', 'थ्रेडेड पाइप कनेक्शन को सील करने के लिए'],
      ['Cutting pipes', 'पाइप काटने के लिए'],
      ['Painting pipes', 'पाइप पेंट करने के लिए'],
      ['Measuring pipes', 'पाइप मापने के लिए'],
      'A',
    ),
    q(
      'What should you normally do before repairing a water pipe?',
      'पानी के पाइप की मरम्मत से पहले सामान्यतः क्या करना चाहिए?',
      ['Shut off the water supply if required', 'आवश्यकता होने पर पानी की सप्लाई बंद करना'],
      ['Open all taps', 'सभी नल खोलना'],
      ['Increase water pressure', 'पानी का दबाव बढ़ाना'],
      ['Heat the pipe', 'पाइप को गर्म करना'],
      'A',
    ),
    q(
      'What is a drainage pipe used for?',
      'ड्रेनेज पाइप का उपयोग किस लिए किया जाता है?',
      ['Carrying wastewater away', 'गंदा पानी बाहर ले जाने के लिए'],
      ['Carrying electricity', 'बिजली ले जाने के लिए'],
      ['Supporting a building', 'इमारत को सहारा देने के लिए'],
      ['Carrying paint', 'पेंट ले जाने के लिए'],
      'A',
    ),
    q(
      'What is a tap used for?',
      'नल का उपयोग किस लिए किया जाता है?',
      ['Controlling the flow of water', 'पानी के प्रवाह को नियंत्रित करने के लिए'],
      ['Cutting metal', 'धातु काटने के लिए'],
      ['Measuring electricity', 'बिजली मापने के लिए'],
      ['Joining steel', 'स्टील जोड़ने के लिए'],
      'A',
    ),
    q(
      'What should be checked after installing a pipe joint?',
      'पाइप जॉइंट लगाने के बाद क्या जांचना चाहिए?',
      ['Whether it leaks', 'कहीं लीकेज तो नहीं है'],
      ['Whether it changes colour', 'उसका रंग बदलता है या नहीं'],
      ['Whether it becomes heavier', 'वह भारी होता है या नहीं'],
      ['Whether it produces electricity', 'वह बिजली बनाता है या नहीं'],
      'A',
    ),
  ],

  'Shuttering Carpenter': [
    q(
      'What is shuttering/formwork used for?',
      'शटरिंग/फॉर्मवर्क का उपयोग किस लिए किया जाता है?',
      ['Holding wet concrete in the required shape', 'गीले कंक्रीट को आवश्यक आकार में रखने के लिए'],
      ['Painting walls', 'दीवार पेंट करने के लिए'],
      ['Carrying water', 'पानी ले जाने के लिए'],
      ['Cutting electrical cables', 'इलेक्ट्रिकल केबल काटने के लिए'],
      'A',
    ),
    q(
      'Which material is commonly used for shuttering?',
      'शटरिंग में सामान्यतः किस सामग्री का उपयोग किया जाता है?',
      ['Plywood', 'प्लाईवुड'],
      ['Glass only', 'केवल कांच'],
      ['Cloth', 'कपड़ा'],
      ['Paper', 'कागज'],
      'A',
    ),
    q(
      'Why must shuttering be properly supported?',
      'शटरिंग को सही तरीके से सपोर्ट देना क्यों जरूरी है?',
      ['To prevent movement or collapse', 'हिलने या गिरने से रोकने के लिए'],
      ['To make concrete softer', 'कंक्रीट को नरम बनाने के लिए'],
      ['To increase paint colour', 'पेंट का रंग बढ़ाने के लिए'],
      ['To reduce concrete size', 'कंक्रीट का आकार कम करने के लिए'],
      'A',
    ),
    q(
      'What is a measuring tape used for?',
      'मेजरिंग टेप का उपयोग किस लिए किया जाता है?',
      ['Measuring dimensions', 'माप लेने के लिए'],
      ['Cutting concrete', 'कंक्रीट काटने के लिए'],
      ['Mixing cement', 'सीमेंट मिलाने के लिए'],
      ['Painting', 'पेंट करने के लिए'],
      'A',
    ),
    q(
      'Why is proper alignment of shuttering important?',
      'शटरिंग का सही अलाइनमेंट क्यों जरूरी है?',
      ['To get the correct shape and position of concrete', 'कंक्रीट का सही आकार और स्थिति प्राप्त करने के लिए'],
      ['To make wood heavier', 'लकड़ी को भारी बनाने के लिए'],
      ['To increase electricity', 'बिजली बढ़ाने के लिए'],
      ['To make cement dry instantly', 'सीमेंट को तुरंत सुखाने के लिए'],
      'A',
    ),
    q(
      'What is a hammer commonly used for?',
      'हैमर का सामान्य उपयोग किस लिए किया जाता है?',
      ['Driving or removing nails', 'कील लगाने या निकालने के लिए'],
      ['Measuring voltage', 'वोल्टेज मापने के लिए'],
      ['Testing water pressure', 'पानी का दबाव जांचने के लिए'],
      ['Mixing paint', 'पेंट मिलाने के लिए'],
      'A',
    ),
    q(
      'What should be checked before concrete is poured?',
      'कंक्रीट डालने से पहले क्या जांचना चाहिए?',
      ['Supports, alignment and dimensions', 'सपोर्ट, अलाइनमेंट और माप'],
      ['Office furniture', 'ऑफिस का फर्नीचर'],
      ['Worker uniforms only', 'केवल कर्मचारियों की यूनिफॉर्म'],
      ['Vehicle fuel', 'वाहन का ईंधन'],
      'A',
    ),
    q(
      'What can happen if shuttering is not strong enough?',
      'यदि शटरिंग पर्याप्त मजबूत नहीं हो तो क्या हो सकता है?',
      ['It can move or collapse', 'यह हिल या गिर सकती है'],
      ['Concrete becomes electricity', 'कंक्रीट बिजली बन जाएगा'],
      ['Wood becomes steel', 'लकड़ी स्टील बन जाएगी'],
      ['Cement changes colour', 'सीमेंट का रंग बदल जाएगा'],
      'A',
    ),
    q(
      'Why should shuttering be removed carefully?',
      'शटरिंग को सावधानी से क्यों हटाना चाहिए?',
      ['To avoid damaging concrete and causing accidents', 'कंक्रीट को नुकसान और दुर्घटना से बचाने के लिए'],
      ['To make concrete wet', 'कंक्रीट को गीला करने के लिए'],
      ['To increase concrete weight', 'कंक्रीट का वजन बढ़ाने के लिए'],
      ['To change concrete colour', 'कंक्रीट का रंग बदलने के लिए'],
      'A',
    ),
    q(
      'Which tool is useful for checking whether a surface is level?',
      'किसी सतह का लेवल जांचने के लिए कौन सा उपकरण उपयोगी है?',
      ['Spirit level', 'स्पिरिट लेवल'],
      ['Pipe wrench', 'पाइप रिंच'],
      ['Welding electrode', 'वेल्डिंग इलेक्ट्रोड'],
      ['Paint brush', 'पेंट ब्रश'],
      'A',
    ),
  ],

  'Mason (tiles/marble)': [
    q(
      'What is a trowel commonly used for?',
      'ट्रॉवेल का सामान्य उपयोग किस लिए किया जाता है?',
      ['Applying and spreading mortar or plaster', 'मोर्टार या प्लास्टर लगाने और फैलाने के लिए'],
      ['Measuring electricity', 'बिजली मापने के लिए'],
      ['Cutting electrical wires', 'विद्युत तार काटने के लिए'],
      ['Welding steel', 'स्टील वेल्ड करने के लिए'],
      'A',
    ),
    q(
      'What is cement mainly used for in masonry work?',
      'राजमिस्त्री के काम में सीमेंट का मुख्य उपयोग क्या है?',
      ['As a binding material', 'बांधने वाली सामग्री के रूप में'],
      ['As electrical insulation', 'विद्युत इंसुलेशन के रूप में'],
      ['As a paint thinner', 'पेंट थिनर के रूप में'],
      ['As a fuel', 'ईंधन के रूप में'],
      'A',
    ),
    q(
      'What is plastering?',
      'प्लास्टरिंग क्या है?',
      ['Applying a finishing layer to a wall or surface', 'दीवार या सतह पर फिनिशिंग की परत लगाना'],
      ['Joining electrical wires', 'विद्युत तार जोड़ना'],
      ['Cutting steel', 'स्टील काटना'],
      ['Installing air conditioners', 'एयर कंडीशनर लगाना'],
      'A',
    ),
    q(
      'What is tile adhesive used for?',
      'टाइल एडहेसिव का उपयोग किस लिए किया जाता है?',
      ['Fixing tiles to a suitable surface', 'टाइल को उपयुक्त सतह पर लगाने के लिए'],
      ['Cutting tiles', 'टाइल काटने के लिए'],
      ['Painting tiles', 'टाइल पेंट करने के लिए'],
      ['Measuring tiles', 'टाइल मापने के लिए'],
      'A',
    ),
    q(
      'Why should the surface be cleaned before fixing tiles?',
      'टाइल लगाने से पहले सतह को साफ क्यों करना चाहिए?',
      ['To help proper bonding', 'सही बॉन्डिंग के लिए'],
      ['To increase dust', 'धूल बढ़ाने के लिए'],
      ['To make tiles heavier', 'टाइल को भारी बनाने के लिए'],
      ['To change tile colour', 'टाइल का रंग बदलने के लिए'],
      'A',
    ),
    q(
      'What is a spirit level used for?',
      'स्पिरिट लेवल का उपयोग किस लिए किया जाता है?',
      ['Checking whether a surface is level', 'सतह का लेवल जांचने के लिए'],
      ['Cutting marble', 'मार्बल काटने के लिए'],
      ['Mixing cement', 'सीमेंट मिलाने के लिए'],
      ['Measuring electricity', 'बिजली मापने के लिए'],
      'A',
    ),
    q(
      'Why is correct tile alignment important?',
      'टाइल का सही अलाइनमेंट क्यों जरूरी है?',
      ['For a straight and good-quality finish', 'सीधी और अच्छी फिनिश के लिए'],
      ['To increase water pressure', 'पानी का दबाव बढ़ाने के लिए'],
      ['To increase electricity', 'बिजली बढ़ाने के लिए'],
      ['To make tiles softer', 'टाइल को नरम बनाने के लिए'],
      'A',
    ),
    q(
      'What is mortar commonly made from?',
      'मोर्टार सामान्यतः किससे बनाया जाता है?',
      ['Cement, sand and water', 'सीमेंट, रेत और पानी'],
      ['Oil and petrol', 'तेल और पेट्रोल'],
      ['Paint and water', 'पेंट और पानी'],
      ['Steel and aluminium', 'स्टील और एल्युमिनियम'],
      'A',
    ),
    q(
      'Which tool is commonly used to cut tiles?',
      'टाइल काटने के लिए सामान्यतः किस उपकरण का उपयोग किया जाता है?',
      ['Tile cutter', 'टाइल कटर'],
      ['Pipe wrench', 'पाइप रिंच'],
      ['Screwdriver', 'स्क्रूड्राइवर'],
      ['Welding electrode', 'वेल्डिंग इलेक्ट्रोड'],
      'A',
    ),
    q(
      "Which PPE can protect a mason's eyes from dust and particles?",
      'धूल और कणों से राजमिस्त्री की आंखों की सुरक्षा के लिए कौन सा PPE उपयोगी है?',
      ['Safety glasses', 'सेफ्टी ग्लास'],
      ['Cotton shirt', 'सूती शर्ट'],
      ['Safety belt', 'सेफ्टी बेल्ट'],
      ['Earphones', 'ईयरफोन'],
      'A',
    ),
  ],

  'Mason (bricks/plaster)': [
    q(
      'What is the main work of a mason?',
      'राजमिस्त्री का मुख्य काम क्या होता है?',
      ['Building walls and doing masonry work', 'दीवार बनाना और चिनाई का काम करना'],
      ['Repairing electrical panels', 'इलेक्ट्रिकल पैनल की मरम्मत करना'],
      ['Welding pipes', 'पाइप वेल्ड करना'],
      ['Repairing vehicles', 'वाहनों की मरम्मत करना'],
      'A',
    ),
    q(
      'What is mortar commonly used for?',
      'मोर्टार का सामान्यतः उपयोग किस लिए किया जाता है?',
      ['Joining bricks or blocks', 'ईंटों या ब्लॉक्स को जोड़ने के लिए'],
      ['Cutting steel', 'स्टील काटने के लिए'],
      ['Painting walls', 'दीवारों पर पेंट करने के लिए'],
      ['Measuring electricity', 'बिजली मापने के लिए'],
      'A',
    ),
    q(
      'What are common materials used to make cement mortar?',
      'सीमेंट मोर्टार बनाने में सामान्यतः किन सामग्रियों का उपयोग किया जाता है?',
      ['Cement, sand and water', 'सीमेंट, रेत और पानी'],
      ['Paint, oil and water', 'पेंट, तेल और पानी'],
      ['Steel, glass and water', 'स्टील, कांच और पानी'],
      ['Wood, paint and cement', 'लकड़ी, पेंट और सीमेंट'],
      'A',
    ),
    q(
      'What is a trowel used for?',
      'ट्रॉवेल का उपयोग किस लिए किया जाता है?',
      ['Applying and spreading mortar or plaster', 'मोर्टार या प्लास्टर लगाने और फैलाने के लिए'],
      ['Cutting electrical wires', 'विद्युत तार काटने के लिए'],
      ['Measuring voltage', 'वोल्टेज मापने के लिए'],
      ['Welding metal', 'धातु वेल्ड करने के लिए'],
      'A',
    ),
    q(
      'Why is a spirit level used in masonry work?',
      'चिनाई के काम में स्पिरिट लेवल का उपयोग क्यों किया जाता है?',
      ['To check whether a surface is level', 'यह जांचने के लिए कि सतह सीधी और लेवल में है'],
      ['To cut bricks', 'ईंट काटने के लिए'],
      ['To mix cement', 'सीमेंट मिलाने के लिए'],
      ['To measure water temperature', 'पानी का तापमान मापने के लिए'],
      'A',
    ),
    q(
      'Why is proper alignment important when building a wall?',
      'दीवार बनाते समय सही अलाइनमेंट क्यों जरूरी है?',
      ['To make the wall straight and properly positioned', 'दीवार को सीधा और सही स्थिति में बनाने के लिए'],
      ['To make the wall heavier', 'दीवार को भारी बनाने के लिए'],
      ['To increase the colour of the wall', 'दीवार का रंग बढ़ाने के लिए'],
      ['To make cement dry immediately', 'सीमेंट को तुरंत सुखाने के लिए'],
      'A',
    ),
    q(
      'What is plastering?',
      'प्लास्टरिंग क्या है?',
      ['Applying a layer of plaster/mortar to a surface', 'सतह पर प्लास्टर/मोर्टार की परत लगाना'],
      ['Cutting steel bars', 'स्टील बार काटना'],
      ['Joining electrical wires', 'विद्युत तार जोड़ना'],
      ['Installing pipes', 'पाइप लगाना'],
      'A',
    ),
    q(
      'Why should the wall surface be cleaned before plastering?',
      'प्लास्टर करने से पहले दीवार की सतह को साफ क्यों करना चाहिए?',
      ['To help the plaster bond properly', 'प्लास्टर को सतह पर अच्छी तरह चिपकने में मदद करने के लिए'],
      ['To increase dust', 'धूल बढ़ाने के लिए'],
      ['To make the wall heavier', 'दीवार को भारी बनाने के लिए'],
      ['To change the wall colour', 'दीवार का रंग बदलने के लिए'],
      'A',
    ),
    q(
      'What should you do if a brick or block is damaged?',
      'यदि कोई ईंट या ब्लॉक क्षतिग्रस्त हो तो क्या करना चाहिए?',
      ['Use it without checking', 'बिना जांचे इस्तेमाल करना'],
      ["Use a suitable undamaged brick/block or follow the supervisor's instruction", 'सही और बिना क्षतिग्रस्त ईंट/ब्लॉक का उपयोग करना या सुपरवाइजर के निर्देश का पालन करना'],
      ['Hide it inside the wall', 'उसे दीवार के अंदर छिपा देना'],
      ['Throw it at another worker', 'उसे दूसरे कर्मचारी पर फेंकना'],
      'B',
    ),
    q(
      'Which PPE is important for a mason working on a construction site?',
      'कंस्ट्रक्शन साइट पर काम करने वाले राजमिस्त्री के लिए कौन सा PPE महत्वपूर्ण है?',
      ['Safety helmet and safety shoes', 'सेफ्टी हेलमेट और सेफ्टी शूज़'],
      ['Sunglasses and slippers', 'धूप का चश्मा और चप्पल'],
      ['Earphones and sandals', 'ईयरफोन और सैंडल'],
      ['Normal clothes only', 'केवल सामान्य कपड़े'],
      'A',
    ),
  ],

  'Construction Labour/Helper': [
    q(
      'What is the main role of a construction helper?',
      'कंस्ट्रक्शन हेल्पर की मुख्य भूमिका क्या होती है?',
      ['Assist skilled workers with basic site work', 'कुशल श्रमिकों को सामान्य साइट कार्य में सहायता करना'],
      ['Design the entire building', 'पूरी इमारत का डिजाइन बनाना'],
      ['Approve building plans', 'बिल्डिंग प्लान को मंजूर करना'],
      ['Manage the company', 'कंपनी चलाना'],
      'A',
    ),
    q(
      'Why is a safety helmet worn on a construction site?',
      'कंस्ट्रक्शन साइट पर सेफ्टी हेलमेट क्यों पहना जाता है?',
      ['To protect the head', 'सिर की सुरक्षा के लिए'],
      ['To protect the feet', 'पैरों की सुरक्षा के लिए'],
      ['To measure temperature', 'तापमान मापने के लिए'],
      ['To carry tools', 'उपकरण ले जाने के लिए'],
      'A',
    ),
    q(
      'Why are safety shoes used?',
      'सेफ्टी शूज़ क्यों पहने जाते हैं?',
      ['To protect the feet', 'पैरों की सुरक्षा के लिए'],
      ['To improve walking speed', 'चलने की गति बढ़ाने के लिए'],
      ['To measure distance', 'दूरी मापने के लिए'],
      ['To protect the eyes', 'आंखों की सुरक्षा के लिए'],
      'A',
    ),
    q(
      'What should you do if you do not understand a work instruction?',
      'यदि आपको काम का निर्देश समझ नहीं आता है तो क्या करना चाहिए?',
      ['Ask the supervisor', 'सुपरवाइजर से पूछना चाहिए'],
      ['Guess and continue', 'अनुमान लगाकर काम जारी रखना चाहिए'],
      ['Leave the site', 'साइट छोड़ देनी चाहिए'],
      ['Ignore the instruction', 'निर्देश को नजरअंदाज करना चाहिए'],
      'A',
    ),
    q(
      'What should you do before lifting a very heavy object?',
      'बहुत भारी वस्तु उठाने से पहले क्या करना चाहिए?',
      ['Use proper lifting methods and ask for help if needed', 'सही तरीके से उठाएं और जरूरत होने पर मदद लें'],
      ['Lift it suddenly', 'अचानक उठा लें'],
      ['Throw it', 'उसे फेंक दें'],
      ['Kick it', 'उसे लात मारें'],
      'A',
    ),
    q(
      'Why should construction areas be kept clean?',
      'कंस्ट्रक्शन क्षेत्र को साफ क्यों रखना चाहिए?',
      ['To reduce trips and accidents', 'ठोकर और दुर्घटनाओं को कम करने के लिए'],
      ['To increase dust', 'धूल बढ़ाने के लिए'],
      ['To make tools difficult to find', 'उपकरण ढूंढना मुश्किल करने के लिए'],
      ['To slow down work', 'काम धीमा करने के लिए'],
      'A',
    ),
    q(
      'Can you operate a machine without proper training or authorization?',
      'क्या उचित ट्रेनिंग या अनुमति के बिना मशीन चला सकते हैं?',
      ['Yes', 'हां'],
      ['No', 'नहीं'],
      ['Only at night', 'केवल रात में'],
      ['Only when alone', 'केवल अकेले होने पर'],
      'B',
    ),
    q(
      'What should you do if you see an unsafe condition?',
      'यदि आपको कोई असुरक्षित स्थिति दिखाई दे तो क्या करना चाहिए?',
      ['Report it to the supervisor', 'सुपरवाइजर को इसकी सूचना दें'],
      ['Ignore it', 'नजरअंदाज करें'],
      ['Hide it', 'उसे छिपा दें'],
      ['Continue working without informing anyone', 'किसी को बताए बिना काम जारी रखें'],
      'A',
    ),
    q(
      'What does PPE stand for?',
      'PPE का पूरा नाम क्या है?',
      ['Personal Protective Equipment', 'पर्सनल प्रोटेक्टिव इक्विपमेंट'],
      ['Personal Power Engine', 'पर्सनल पावर इंजन'],
      ['Public Protection Entry', 'पब्लिक प्रोटेक्शन एंट्री'],
      ['Professional Plumbing Equipment', 'प्रोफेशनल प्लंबिंग इक्विपमेंट'],
      'A',
    ),
    q(
      'Why is following safety instructions important?',
      'सुरक्षा निर्देशों का पालन करना क्यों जरूरी है?',
      ['To reduce accidents and injuries', 'दुर्घटनाओं और चोटों को कम करने के लिए'],
      ['To increase working hours', 'काम के घंटे बढ़ाने के लिए'],
      ['To make tools heavier', 'उपकरणों को भारी बनाने के लिए'],
      ['To slow down construction', 'कंस्ट्रक्शन धीमा करने के लिए'],
      'A',
    ),
  ],

  'Pipe Fitter': [
    q(
      'What does a pipe fitter mainly do?',
      'पाइप फिटर का मुख्य काम क्या होता है?',
      ['Installs and connects piping systems', 'पाइपिंग सिस्टम लगाना और जोड़ना'],
      ['Paints walls', 'दीवारों पर पेंट करना'],
      ['Repairs electrical circuits', 'इलेक्ट्रिकल सर्किट की मरम्मत करना'],
      ['Installs tiles only', 'केवल टाइल लगाना'],
      'A',
    ),
    q(
      'What does GI commonly mean in GI pipe?',
      'GI पाइप में GI का सामान्य अर्थ क्या है?',
      ['Galvanized Iron', 'गैल्वनाइज्ड आयरन'],
      ['General Insulation', 'जनरल इंसुलेशन'],
      ['Ground Installation', 'ग्राउंड इंस्टॉलेशन'],
      ['Gas Indicator', 'गैस इंडिकेटर'],
      'A',
    ),
    q(
      'What is an elbow used for in piping?',
      'पाइपिंग में एल्बो का उपयोग किस लिए किया जाता है?',
      ['Changing the direction of a pipe', 'पाइप की दिशा बदलने के लिए'],
      ['Measuring pipe length', 'पाइप की लंबाई मापने के लिए'],
      ['Cutting steel', 'स्टील काटने के लिए'],
      ['Painting pipes', 'पाइप पेंट करने के लिए'],
      'A',
    ),
    q(
      'What is a tee fitting used for?',
      'टी फिटिंग का उपयोग किस लिए किया जाता है?',
      ['Creating a branch in a pipe system', 'पाइप सिस्टम में ब्रांच बनाने के लिए'],
      ['Cutting pipes', 'पाइप काटने के लिए'],
      ['Measuring pressure', 'दबाव मापने के लिए'],
      ['Painting pipes', 'पाइप पेंट करने के लिए'],
      'A',
    ),
    q(
      'What is a reducer used for?',
      'रिड्यूसर का उपयोग किस लिए किया जाता है?',
      ['Connecting pipes of different sizes', 'अलग-अलग आकार के पाइप जोड़ने के लिए'],
      ['Measuring pipe temperature', 'पाइप का तापमान मापने के लिए'],
      ['Cutting steel', 'स्टील काटने के लिए'],
      ['Cleaning floors', 'फर्श साफ करने के लिए'],
      'A',
    ),
    q(
      'Which tool is commonly used to grip and turn a pipe?',
      'पाइप को पकड़ने और घुमाने के लिए किस उपकरण का उपयोग किया जाता है?',
      ['Pipe wrench', 'पाइप रिंच'],
      ['Paint brush', 'पेंट ब्रश'],
      ['Trowel', 'ट्रॉवेल'],
      ['Tile cutter', 'टाइल कटर'],
      'A',
    ),
    q(
      'Why is correct pipe alignment important?',
      'पाइप का सही अलाइनमेंट क्यों जरूरी है?',
      ['For proper installation and to reduce leakage/stress', 'सही इंस्टॉलेशन और लीकेज/तनाव कम करने के लिए'],
      ['To make pipes colourful', 'पाइप को रंगीन बनाने के लिए'],
      ['To increase electricity', 'बिजली बढ़ाने के लिए'],
      ['To make pipes heavier', 'पाइप को भारी बनाने के लिए'],
      'A',
    ),
    q(
      'What should be checked after joining pipes?',
      'पाइप जोड़ने के बाद क्या जांचना चाहिए?',
      ['Connections and possible leaks', 'कनेक्शन और संभावित लीकेज'],
      ['Paint colour only', 'केवल पेंट का रंग'],
      ['Worker height', 'कर्मचारी की लंबाई'],
      ['Floor colour', 'फर्श का रंग'],
      'A',
    ),
    q(
      'What is a coupling generally used for?',
      'कपलिंग का सामान्य उपयोग किस लिए किया जाता है?',
      ['Joining two pipes', 'दो पाइप जोड़ने के लिए'],
      ['Cutting a pipe', 'पाइप काटने के लिए'],
      ['Measuring electricity', 'बिजली मापने के लिए'],
      ['Painting a wall', 'दीवार पेंट करने के लिए'],
      'A',
    ),
    q(
      'Why should gloves be worn when handling steel pipes?',
      'स्टील पाइप संभालते समय ग्लव्स क्यों पहनने चाहिए?',
      ['To protect hands from cuts and sharp edges', 'हाथों को कटने और तेज किनारों से बचाने के लिए'],
      ['To increase pipe size', 'पाइप का आकार बढ़ाने के लिए'],
      ['To measure pressure', 'दबाव मापने के लिए'],
      ['To make pipes lighter', 'पाइप को हल्का बनाने के लिए'],
      'A',
    ),
  ],

  'Furniture Carpenter - Finishing, All Rounder': [
    q(
      'What is a carpenter mainly involved in?',
      'कारपेंटर मुख्य रूप से किस काम से जुड़ा होता है?',
      ['Working with wood and related materials', 'लकड़ी और संबंधित सामग्री के साथ काम करना'],
      ['Repairing electrical circuits', 'विद्युत सर्किट की मरम्मत करना'],
      ['Installing water pumps only', 'केवल पानी के पंप लगाना'],
      ['Welding pipes', 'पाइप वेल्ड करना'],
      'A',
    ),
    q(
      'What is a saw used for?',
      'आरी का उपयोग किस लिए किया जाता है?',
      ['Cutting wood', 'लकड़ी काटने के लिए'],
      ['Measuring electricity', 'बिजली मापने के लिए'],
      ['Mixing cement', 'सीमेंट मिलाने के लिए'],
      ['Tightening bolts', 'बोल्ट कसने के लिए'],
      'A',
    ),
    q(
      'What is a hammer commonly used for?',
      'हैमर का सामान्य उपयोग किस लिए किया जाता है?',
      ['Driving nails', 'कील लगाने के लिए'],
      ['Measuring wood', 'लकड़ी मापने के लिए'],
      ['Cutting pipes', 'पाइप काटने के लिए'],
      ['Testing electricity', 'बिजली जांचने के लिए'],
      'A',
    ),
    q(
      'What is a screwdriver used for?',
      'स्क्रूड्राइवर का उपयोग किस लिए किया जाता है?',
      ['Tightening or removing screws', 'स्क्रू कसने या निकालने के लिए'],
      ['Cutting wood', 'लकड़ी काटने के लिए'],
      ['Mixing paint', 'पेंट मिलाने के लिए'],
      ['Measuring water', 'पानी मापने के लिए'],
      'A',
    ),
    q(
      'Why is accurate measurement important in carpentry?',
      'कारपेंटरी में सही माप लेना क्यों जरूरी है?',
      ['To ensure proper size and fit', 'सही आकार और फिट सुनिश्चित करने के लिए'],
      ['To make wood heavier', 'लकड़ी को भारी बनाने के लिए'],
      ['To increase electricity', 'बिजली बढ़ाने के लिए'],
      ['To change wood colour', 'लकड़ी का रंग बदलने के लिए'],
      'A',
    ),
    q(
      'What is plywood?',
      'प्लाईवुड क्या है?',
      ['A wood-based panel made from layers of veneer', 'लकड़ी की परतों से बना एक पैनल'],
      ['A type of steel', 'एक प्रकार का स्टील'],
      ['A type of pipe', 'एक प्रकार का पाइप'],
      ['A type of cement', 'एक प्रकार का सीमेंट'],
      'A',
    ),
    q(
      'What is a nail used for?',
      'कील का उपयोग किस लिए किया जाता है?',
      ['Joining or fixing suitable materials', 'उपयुक्त सामग्री को जोड़ने या फिक्स करने के लिए'],
      ['Measuring voltage', 'वोल्टेज मापने के लिए'],
      ['Cutting tiles', 'टाइल काटने के लिए'],
      ['Painting wood', 'लकड़ी पेंट करने के लिए'],
      'A',
    ),
    q(
      'What is sandpaper used for?',
      'सैंडपेपर का उपयोग किस लिए किया जाता है?',
      ['Smoothing a surface', 'सतह को चिकना करने के लिए'],
      ['Joining pipes', 'पाइप जोड़ने के लिए'],
      ['Measuring electricity', 'बिजली मापने के लिए'],
      ['Welding steel', 'स्टील वेल्ड करने के लिए'],
      'A',
    ),
    q(
      'Why should carpentry tools be kept in good condition?',
      'कारपेंटरी के उपकरणों को अच्छी स्थिति में क्यों रखना चाहिए?',
      ['For safe and effective work', 'सुरक्षित और प्रभावी काम के लिए'],
      ['To increase their weight', 'उनका वजन बढ़ाने के लिए'],
      ['To make them colourful', 'उन्हें रंगीन बनाने के लिए'],
      ['To reduce their size', 'उनका आकार कम करने के लिए'],
      'A',
    ),
    q(
      'Which PPE protects the eyes from wood dust and particles?',
      'लकड़ी की धूल और कणों से आंखों की सुरक्षा के लिए कौन सा PPE उपयोगी है?',
      ['Safety glasses', 'सेफ्टी ग्लास'],
      ['Safety belt', 'सेफ्टी बेल्ट'],
      ['Safety shoes only', 'केवल सेफ्टी शूज़'],
      ['Ear plugs', 'ईयर प्लग'],
      'A',
    ),
  ],

  'Steel Fixer': [
    q(
      'What does a steel fixer mainly work with?',
      'स्टील फिक्सर मुख्य रूप से किसके साथ काम करता है?',
      ['Reinforcement steel', 'रिइन्फोर्समेंट स्टील'],
      ['Paint', 'पेंट'],
      ['Glass only', 'केवल कांच'],
      ['Electrical wires', 'विद्युत तार'],
      'A',
    ),
    q(
      'What is rebar?',
      'रीबार क्या होता है?',
      ['Reinforcement steel bar', 'रिइन्फोर्समेंट स्टील बार'],
      ['A type of paint', 'एक प्रकार का पेंट'],
      ['A plumbing valve', 'प्लंबिंग वाल्व'],
      ['A wooden panel', 'लकड़ी का पैनल'],
      'A',
    ),
    q(
      'Why is reinforcement steel placed in concrete?',
      'कंक्रीट में रिइन्फोर्समेंट स्टील क्यों लगाया जाता है?',
      ['To provide additional structural strength', 'संरचना को अतिरिक्त मजबूती देने के लिए'],
      ['To change its colour', 'उसका रंग बदलने के लिए'],
      ['To make it lighter', 'उसे हल्का बनाने के लिए'],
      ['To make it waterproof by itself', 'इसे अपने आप वाटरप्रूफ बनाने के लिए'],
      'A',
    ),
    q(
      'What is binding wire used for?',
      'बाइंडिंग वायर का उपयोग किस लिए किया जाता है?',
      ['Tying reinforcement bars together', 'रिइन्फोर्समेंट बार को आपस में बांधने के लिए'],
      ['Carrying electricity', 'बिजली ले जाने के लिए'],
      ['Cutting concrete', 'कंक्रीट काटने के लिए'],
      ['Painting steel', 'स्टील पेंट करने के लिए'],
      'A',
    ),
    q(
      'What is a rebar bending machine used for?',
      'रीबार बेंडिंग मशीन का उपयोग किस लिए किया जाता है?',
      ['Bending reinforcement bars', 'रिइन्फोर्समेंट बार को मोड़ने के लिए'],
      ['Cutting wood', 'लकड़ी काटने के लिए'],
      ['Mixing cement', 'सीमेंट मिलाने के लिए'],
      ['Painting steel', 'स्टील पेंट करने के लिए'],
      'A',
    ),
    q(
      'Why is correct spacing between reinforcement bars important?',
      'रिइन्फोर्समेंट बार के बीच सही दूरी क्यों जरूरी है?',
      ['To place reinforcement according to the required design', 'निर्धारित डिजाइन के अनुसार रिइन्फोर्समेंट लगाने के लिए'],
      ['To make steel colourful', 'स्टील को रंगीन बनाने के लिए'],
      ['To reduce steel strength', 'स्टील की मजबूती कम करने के लिए'],
      ['To make concrete dry faster', 'कंक्रीट को जल्दी सुखाने के लिए'],
      'A',
    ),
    q(
      'Why should steel bars be handled carefully?',
      'स्टील बार को सावधानी से क्यों संभालना चाहिए?',
      ['They can be heavy and have sharp edges', 'वे भारी हो सकते हैं और उनके किनारे तेज हो सकते हैं'],
      ['They can melt in sunlight', 'वे धूप में पिघल सकते हैं'],
      ['They produce electricity automatically', 'वे अपने आप बिजली बनाते हैं'],
      ['They are made of glass', 'वे कांच से बने होते हैं'],
      'A',
    ),
    q(
      'What should you use when moving very heavy steel bars?',
      'बहुत भारी स्टील बार को स्थानांतरित करते समय क्या उपयोग करना चाहिए?',
      ['Proper assistance or lifting equipment', 'उचित सहायता या लिफ्टिंग उपकरण'],
      ['Bare hands only', 'केवल नंगे हाथ'],
      ['A paint brush', 'पेंट ब्रश'],
      ['A screwdriver', 'स्क्रूड्राइवर'],
      'A',
    ),
    q(
      'What tool is commonly used to tie reinforcement bars with binding wire?',
      'बाइंडिंग वायर से रिइन्फोर्समेंट बार बांधने के लिए किस उपकरण का उपयोग किया जाता है?',
      ['Rebar tying hook', 'रीबार टाइंग हुक'],
      ['Paint roller', 'पेंट रोलर'],
      ['Pipe wrench', 'पाइप रिंच'],
      ['Tile cutter', 'टाइल कटर'],
      'A',
    ),
    q(
      'What should you wear when handling reinforcement steel?',
      'रिइन्फोर्समेंट स्टील संभालते समय क्या पहनना चाहिए?',
      ['Suitable gloves and safety footwear', 'उपयुक्त ग्लव्स और सेफ्टी फुटवियर'],
      ['Slippers only', 'केवल चप्पल'],
      ['No PPE', 'कोई PPE नहीं'],
      ['Loose jewellery', 'ढीली ज्वेलरी'],
      'A',
    ),
  ],

  'AC Technician': [
    q(
      'What is the main purpose of an air conditioner?',
      'एयर कंडीशनर का मुख्य उद्देश्य क्या है?',
      ['To cool and condition indoor air', 'कमरे की हवा को ठंडा और नियंत्रित करना'],
      ['To heat steel', 'स्टील गर्म करना'],
      ['To pump water', 'पानी पंप करना'],
      ['To generate electricity', 'बिजली बनाना'],
      'A',
    ),
    q(
      'What is the main function of an AC filter?',
      'AC फिल्टर का मुख्य काम क्या है?',
      ['To help remove dust and particles from air', 'हवा से धूल और कण हटाने में मदद करना'],
      ['To increase voltage', 'वोल्टेज बढ़ाना'],
      ['To store refrigerant', 'रेफ्रिजरेंट स्टोर करना'],
      ['To produce electricity', 'बिजली बनाना'],
      'A',
    ),
    q(
      'What is a compressor in an AC system?',
      'AC सिस्टम में कंप्रेसर क्या होता है?',
      ['A major component that compresses and circulates refrigerant', 'एक मुख्य घटक जो रेफ्रिजरेंट को कंप्रेस और सर्कुलेट करता है'],
      ['An electrical switch only', 'केवल इलेक्ट्रिकल स्विच'],
      ['An air filter', 'एयर फिल्टर'],
      ['A water tank', 'पानी की टंकी'],
      'A',
    ),
    q(
      'What is refrigerant used for in an AC?',
      'AC में रेफ्रिजरेंट का उपयोग किस लिए होता है?',
      ['Transferring heat in the cooling system', 'कूलिंग सिस्टम में गर्मी को ट्रांसफर करने के लिए'],
      ['Cleaning floors', 'फर्श साफ करने के लिए'],
      ['Painting walls', 'दीवार पेंट करने के लिए'],
      ['Lubricating doors', 'दरवाजों को चिकना करने के लिए'],
      'A',
    ),
    q(
      'Why should an AC filter be cleaned?',
      'AC फिल्टर को साफ क्यों करना चाहिए?',
      ['To maintain proper airflow and efficient operation', 'सही एयरफ्लो और बेहतर संचालन के लिए'],
      ['To increase room temperature', 'कमरे का तापमान बढ़ाने के लिए'],
      ['To increase electricity consumption', 'बिजली की खपत बढ़ाने के लिए'],
      ['To make the AC heavier', 'AC को भारी बनाने के लिए'],
      'A',
    ),
    q(
      'What is the indoor unit of a split AC?',
      'स्प्लिट AC की इनडोर यूनिट क्या होती है?',
      ['The unit installed inside the room', 'कमरे के अंदर लगाई जाने वाली यूनिट'],
      ['The outdoor compressor only', 'केवल आउटडोर कंप्रेसर'],
      ['The electrical meter', 'बिजली का मीटर'],
      ['The water tank', 'पानी की टंकी'],
      'A',
    ),
    q(
      'What is the outdoor unit?',
      'आउटडोर यूनिट क्या होती है?',
      ['The external unit containing components such as the compressor and condenser', 'बाहर लगी यूनिट जिसमें कंप्रेसर और कंडेंसर जैसे घटक होते हैं'],
      ['The indoor air filter only', 'केवल इनडोर एयर फिल्टर'],
      ['The room thermostat only', 'केवल रूम थर्मोस्टेट'],
      ['The electrical socket', 'इलेक्ट्रिकल सॉकेट'],
      'A',
    ),
    q(
      "What should be done before working on an AC's electrical components?",
      'AC के इलेक्ट्रिकल पार्ट्स पर काम करने से पहले क्या करना चाहिए?',
      ['Safely isolate/switch off the electrical supply', 'इलेक्ट्रिकल सप्लाई को सुरक्षित रूप से बंद/आइसोलेट करना'],
      ['Pour water on the unit', 'यूनिट पर पानी डालना'],
      ['Touch the wires', 'तारों को छूना'],
      ['Increase the voltage', 'वोल्टेज बढ़ाना'],
      'A',
    ),
    q(
      'What can happen if an AC filter is heavily blocked with dust?',
      'यदि AC फिल्टर धूल से बहुत ज्यादा ब्लॉक हो जाए तो क्या हो सकता है?',
      ['Airflow can be reduced', 'एयरफ्लो कम हो सकता है'],
      ['The room becomes larger', 'कमरा बड़ा हो जाता है'],
      ['The AC becomes a heater automatically', 'AC अपने आप हीटर बन जाता है'],
      ['Refrigerant becomes water', 'रेफ्रिजरेंट पानी बन जाता है'],
      'A',
    ),
    q(
      'Why should PPE be used when working on an AC?',
      'AC पर काम करते समय PPE का उपयोग क्यों करना चाहिए?',
      ['To protect against electrical and other workplace hazards', 'विद्युत और अन्य कार्यस्थल के खतरों से सुरक्षा के लिए'],
      ['To make the AC colder', 'AC को अधिक ठंडा करने के लिए'],
      ['To increase refrigerant pressure', 'रेफ्रिजरेंट का दबाव बढ़ाने के लिए'],
      ['To reduce room size', 'कमरे का आकार कम करने के लिए'],
      'A',
    ),
  ],

  'Warehouse Helper': [
    q(
      'What is a common job of a warehouse worker?',
      'वेयरहाउस वर्कर का सामान्य काम क्या होता है?',
      ['Moving, sorting and organizing goods', 'सामान को ले जाना, छांटना और व्यवस्थित करना'],
      ['Designing buildings', 'इमारतों का डिजाइन बनाना'],
      ['Repairing electrical panels', 'इलेक्ट्रिकल पैनल की मरम्मत करना'],
      ['Welding structures', 'स्ट्रक्चर वेल्ड करना'],
      'A',
    ),
    q(
      'What is stock?',
      'स्टॉक क्या होता है?',
      ['Goods/products kept for sale or use', 'बिक्री या उपयोग के लिए रखे गए सामान/उत्पाद'],
      ['A type of machine', 'एक प्रकार की मशीन'],
      ['A safety helmet', 'सेफ्टी हेलमेट'],
      ['A type of pipe', 'एक प्रकार का पाइप'],
      'A',
    ),
    q(
      'Why should warehouse aisles be kept clear?',
      'वेयरहाउस के रास्ते/आइल्स खाली क्यों रखने चाहिए?',
      ['For safe movement and to prevent accidents', 'सुरक्षित आवाजाही और दुर्घटनाओं से बचने के लिए'],
      ['To store more waste', 'अधिक कचरा रखने के लिए'],
      ['To block workers', 'कर्मचारियों को रोकने के लिए'],
      ['To reduce visibility', 'दिखाई देना कम करने के लिए'],
      'A',
    ),
    q(
      'What is a barcode mainly used for?',
      'बारकोड का मुख्य उपयोग किस लिए किया जाता है?',
      ['Identifying and tracking products', 'उत्पादों की पहचान और ट्रैकिंग के लिए'],
      ['Cutting boxes', 'डिब्बे काटने के लिए'],
      ['Measuring temperature', 'तापमान मापने के लिए'],
      ['Cleaning shelves', 'शेल्फ साफ करने के लिए'],
      'A',
    ),
    q(
      'What should you do if you find damaged stock?',
      'यदि आपको क्षतिग्रस्त स्टॉक मिले तो क्या करना चाहिए?',
      ['Report it according to workplace procedure', 'कार्यस्थल की प्रक्रिया के अनुसार इसकी सूचना दें'],
      ['Hide it', 'उसे छिपा दें'],
      ['Sell it without informing anyone', 'बिना बताए बेच दें'],
      ['Throw it anywhere', 'कहीं भी फेंक दें'],
      'A',
    ),
    q(
      'What should you do when a box is too heavy to lift safely?',
      'यदि कोई बॉक्स सुरक्षित रूप से उठाने के लिए बहुत भारी है तो क्या करना चाहिए?',
      ['Ask for help or use suitable equipment', 'मदद मांगें या उचित उपकरण का उपयोग करें'],
      ['Lift it alone immediately', 'अकेले तुरंत उठाएं'],
      ['Kick it', 'उसे लात मारें'],
      ['Throw it', 'उसे फेंक दें'],
      'A',
    ),
    q(
      'Why is stock counting important?',
      'स्टॉक की गिनती करना क्यों जरूरी है?',
      ['To know how much stock is available', 'उपलब्ध स्टॉक की मात्रा जानने के लिए'],
      ['To make products heavier', 'उत्पादों को भारी बनाने के लिए'],
      ['To change product prices automatically', 'उत्पाद की कीमत अपने आप बदलने के लिए'],
      ['To clean the warehouse', 'वेयरहाउस साफ करने के लिए'],
      'A',
    ),
    q(
      'Can an untrained worker operate a forklift?',
      'क्या बिना ट्रेनिंग वाला कर्मचारी फोर्कलिफ्ट चला सकता है?',
      ['Yes', 'हां'],
      ['No', 'नहीं'],
      ['Only after lunch', 'केवल लंच के बाद'],
      ['Only when the warehouse is empty', 'केवल वेयरहाउस खाली होने पर'],
      'B',
    ),
    q(
      'Why should products be stored properly?',
      'उत्पादों को सही तरीके से क्यों रखना चाहिए?',
      ['To prevent damage and maintain safety', 'नुकसान से बचाने और सुरक्षा बनाए रखने के लिए'],
      ['To make them difficult to find', 'उन्हें ढूंढना मुश्किल बनाने के लिए'],
      ['To increase dust', 'धूल बढ़ाने के लिए'],
      ['To block aisles', 'रास्ते बंद करने के लिए'],
      'A',
    ),
    q(
      'What should you do if you notice a safety hazard in the warehouse?',
      'यदि आपको वेयरहाउस में कोई सुरक्षा खतरा दिखाई दे तो क्या करना चाहिए?',
      ['Report it to the supervisor', 'सुपरवाइजर को इसकी सूचना दें'],
      ['Ignore it', 'नजरअंदाज करें'],
      ['Hide it', 'उसे छिपा दें'],
      ['Continue working without informing anyone', 'किसी को बताए बिना काम जारी रखें'],
      'A',
    ),
  ],

  'Cleaner (Male)': CLEANER_TRADE_KNOWLEDGE,
  'Cleaner (Female)': CLEANER_TRADE_KNOWLEDGE,

  Scaffolder: [
    q(
      'What is scaffolding used for?',
      'स्कैफोल्डिंग का उपयोग किस लिए किया जाता है?',
      ['Providing a temporary working platform/access at height', 'ऊंचाई पर अस्थायी कार्य प्लेटफॉर्म/पहुंच प्रदान करने के लिए'],
      ['Carrying water', 'पानी ले जाने के लिए'],
      ['Painting vehicles', 'वाहनों पर पेंट करने के लिए'],
      ['Cutting electrical wires', 'विद्युत तार काटने के लिए'],
      'A',
    ),
    q(
      'Why must scaffolding be stable?',
      'स्कैफोल्डिंग का स्थिर होना क्यों जरूरी है?',
      ['To prevent movement and collapse', 'हिलने और गिरने से बचाने के लिए'],
      ['To make it heavier', 'इसे भारी बनाने के लिए'],
      ['To increase its height automatically', 'इसकी ऊंचाई अपने आप बढ़ाने के लिए'],
      ['To make it easier to paint', 'इसे पेंट करना आसान बनाने के लिए'],
      'A',
    ),
    q(
      'What is a scaffold platform?',
      'स्कैफोल्ड प्लेटफॉर्म क्या होता है?',
      ['The working surface where workers stand', 'वह कार्य सतह जहां कर्मचारी खड़े होकर काम करते हैं'],
      ['A type of pipe', 'एक प्रकार का पाइप'],
      ['A type of electrical cable', 'एक प्रकार की इलेक्ट्रिकल केबल'],
      ['A safety helmet', 'सेफ्टी हेलमेट'],
      'A',
    ),
    q(
      'What is a guardrail used for?',
      'गार्डरेल का उपयोग किस लिए किया जाता है?',
      ['Helping prevent workers from falling', 'कर्मचारियों को गिरने से बचाने में मदद करने के लिए'],
      ['Measuring height', 'ऊंचाई मापने के लिए'],
      ['Carrying tools', 'उपकरण ले जाने के लिए'],
      ['Joining pipes', 'पाइप जोड़ने के लिए'],
      'A',
    ),
    q(
      'Can damaged scaffold components be used?',
      'क्या क्षतिग्रस्त स्कैफोल्डिंग पार्ट्स का उपयोग किया जा सकता है?',
      ['Yes, always', 'हां, हमेशा'],
      ['No, they should be reported', 'नहीं, इसकी सूचना देनी चाहिए'],
      ['Yes, if painted', 'हां, अगर पेंट किए हों'],
      ['Only at night', 'केवल रात में'],
      'B',
    ),
    q(
      'Why should scaffolding be inspected?',
      'स्कैफोल्डिंग का निरीक्षण क्यों किया जाना चाहिए?',
      ['To identify unsafe or damaged components', 'असुरक्षित या क्षतिग्रस्त पार्ट्स की पहचान करने के लिए'],
      ['To change its colour', 'उसका रंग बदलने के लिए'],
      ['To increase its weight', 'उसका वजन बढ़ाने के लिए'],
      ['To make it easier to transport', 'उसे ले जाना आसान बनाने के लिए'],
      'A',
    ),
    q(
      'What should you do if scaffolding appears unsafe?',
      'यदि स्कैफोल्डिंग असुरक्षित दिखाई दे तो क्या करना चाहिए?',
      ['Do not use it and inform the responsible person', 'इसका उपयोग न करें और जिम्मेदार व्यक्ति को सूचित करें'],
      ['Use it carefully anyway', 'फिर भी सावधानी से इस्तेमाल करें'],
      ['Remove random parts', 'कुछ भी पार्ट निकाल दें'],
      ['Ignore the problem', 'समस्या को नजरअंदाज करें'],
      'A',
    ),
    q(
      'Why should the scaffold platform be kept clear?',
      'स्कैफोल्ड प्लेटफॉर्म को खाली/साफ क्यों रखना चाहिए?',
      ['To reduce trips and falling-object hazards', 'ठोकर और गिरने वाली वस्तुओं के खतरे को कम करने के लिए'],
      ['To store more waste', 'अधिक कचरा रखने के लिए'],
      ['To make the platform heavier', 'प्लेटफॉर्म को भारी बनाने के लिए'],
      ['To reduce working space', 'कार्य स्थान कम करने के लिए'],
      'A',
    ),
    q(
      'When working at height, what may be required in addition to normal PPE?',
      'ऊंचाई पर काम करते समय सामान्य PPE के अलावा क्या आवश्यक हो सकता है?',
      ['Appropriate fall-protection equipment', 'उचित फॉल-प्रोटेक्शन उपकरण'],
      ['Swimming equipment', 'तैराकी उपकरण'],
      ['Cooking gloves', 'कुकिंग ग्लव्स'],
      ['Earphones', 'ईयरफोन'],
      'A',
    ),
    q(
      'What is one important hazard when working on scaffolding?',
      'स्कैफोल्डिंग पर काम करते समय एक महत्वपूर्ण खतरा क्या है?',
      ['Falling from height', 'ऊंचाई से गिरना'],
      ['Getting wet from rain only', 'केवल बारिश में भीगना'],
      ['Losing a measuring tape', 'मेजरिंग टेप खोना'],
      ['Paint colour changing', 'पेंट का रंग बदलना'],
      'A',
    ),
  ],

  Painter: [
    q(
      'What is the main job of a painter?',
      'पेंटर का मुख्य काम क्या होता है?',
      ['Preparing and painting surfaces', 'सतह तैयार करना और पेंट करना'],
      ['Installing electrical panels', 'इलेक्ट्रिकल पैनल लगाना'],
      ['Welding steel', 'स्टील वेल्ड करना'],
      ['Installing pipes', 'पाइप लगाना'],
      'A',
    ),
    q(
      'What is a paint brush used for?',
      'पेंट ब्रश का उपयोग किस लिए किया जाता है?',
      ['Applying paint', 'पेंट लगाने के लिए'],
      ['Cutting wood', 'लकड़ी काटने के लिए'],
      ['Measuring voltage', 'वोल्टेज मापने के लिए'],
      ['Joining pipes', 'पाइप जोड़ने के लिए'],
      'A',
    ),
    q(
      'What is a paint roller commonly used for?',
      'पेंट रोलर का सामान्य उपयोग किस लिए किया जाता है?',
      ['Painting larger surfaces', 'बड़ी सतहों पर पेंट करने के लिए'],
      ['Cutting metal', 'धातु काटने के लिए'],
      ['Measuring pipes', 'पाइप मापने के लिए'],
      ['Welding', 'वेल्डिंग करने के लिए'],
      'A',
    ),
    q(
      'Why is surface preparation important before painting?',
      'पेंट करने से पहले सतह तैयार करना क्यों जरूरी है?',
      ['It helps the paint adhere properly and improves the finish', 'इससे पेंट अच्छी तरह चिपकता है और फिनिश बेहतर होती है'],
      ['It makes the wall heavier', 'दीवार भारी हो जाती है'],
      ['It increases electricity', 'बिजली बढ़ती है'],
      ['It makes paint dry before application', 'पेंट लगाने से पहले ही सूख जाता है'],
      'A',
    ),
    q(
      'What is sandpaper used for?',
      'सैंडपेपर का उपयोग किस लिए किया जाता है?',
      ['Smoothing a surface', 'सतह को चिकना करने के लिए'],
      ['Mixing paint', 'पेंट मिलाने के लिए'],
      ['Measuring paint', 'पेंट मापने के लिए'],
      ['Cutting pipes', 'पाइप काटने के लिए'],
      'A',
    ),
    q(
      'What is primer used for?',
      'प्राइमर का उपयोग किस लिए किया जाता है?',
      ['Preparing a surface before the final coat', 'अंतिम पेंट कोट से पहले सतह तैयार करने के लिए'],
      ['Cleaning electrical wires', 'इलेक्ट्रिकल तार साफ करने के लिए'],
      ['Cutting tiles', 'टाइल काटने के लिए'],
      ['Joining steel pipes', 'स्टील पाइप जोड़ने के लिए'],
      'A',
    ),
    q(
      'Why should paint be mixed properly?',
      'पेंट को अच्छी तरह मिलाना क्यों जरूरी है?',
      ['To achieve an even consistency', 'एक समान कंसिस्टेंसी प्राप्त करने के लिए'],
      ['To make the paint heavier', 'पेंट को भारी बनाने के लिए'],
      ['To increase electricity', 'बिजली बढ़ाने के लिए'],
      ['To make the brush harder', 'ब्रश को कठोर बनाने के लिए'],
      'A',
    ),
    q(
      'Why is ventilation important when using certain paints?',
      'कुछ प्रकार के पेंट इस्तेमाल करते समय वेंटिलेशन क्यों जरूरी है?',
      ['To reduce exposure to fumes', 'धुएं के संपर्क को कम करने के लिए'],
      ['To increase paint smell', 'पेंट की गंध बढ़ाने के लिए'],
      ['To make paint thicker', 'पेंट को गाढ़ा बनाने के लिए'],
      ['To make the wall wet', 'दीवार को गीला करने के लिए'],
      'A',
    ),
    q(
      'What should you do if paint gets into your eyes?',
      'यदि पेंट आंखों में चला जाए तो क्या करना चाहिए?',
      ['Rinse with clean water and report/seek appropriate medical attention', 'साफ पानी से धोकर सूचना दें और उचित चिकित्सा सहायता लें'],
      ['Rub your eyes', 'आंखों को रगड़ें'],
      ['Ignore it', 'नजरअंदाज करें'],
      ['Continue painting', 'पेंटिंग जारी रखें'],
      'A',
    ),
    q(
      'Why should paint containers be closed when not in use?',
      'इस्तेमाल न होने पर पेंट के डिब्बे बंद क्यों रखने चाहिए?',
      ['To prevent spills and unnecessary drying', 'गिरने और अनावश्यक रूप से सूखने से रोकने के लिए'],
      ['To increase paint temperature', 'पेंट का तापमान बढ़ाने के लिए'],
      ['To make the paint heavier', 'पेंट को भारी बनाने के लिए'],
      ['To change the colour', 'रंग बदलने के लिए'],
      'A',
    ),
  ],

  'Aluminium Fixer/Fabricator': [
    q(
      'Where is aluminium commonly used in construction?',
      'निर्माण कार्य में एल्युमिनियम का सामान्यतः उपयोग कहां किया जाता है?',
      ['Windows, doors and frames', 'खिड़कियों, दरवाजों और फ्रेम में'],
      ['Concrete foundations only', 'केवल कंक्रीट फाउंडेशन में'],
      ['Water tanks only', 'केवल पानी की टंकी में'],
      ['Electrical transformers only', 'केवल इलेक्ट्रिकल ट्रांसफॉर्मर में'],
      'A',
    ),
    q(
      'What is an aluminium profile?',
      'एल्युमिनियम प्रोफाइल क्या होती है?',
      ['A shaped aluminium section used to make frames or structures', 'फ्रेम या स्ट्रक्चर बनाने के लिए उपयोग की जाने वाली आकार वाली एल्युमिनियम सेक्शन'],
      ['A type of cement', 'एक प्रकार का सीमेंट'],
      ['A type of electrical cable', 'एक प्रकार की इलेक्ट्रिकल केबल'],
      ['A type of paint', 'एक प्रकार का पेंट'],
      'A',
    ),
    q(
      'Why is accurate measurement important in aluminium fabrication?',
      'एल्युमिनियम फैब्रिकेशन में सही माप क्यों जरूरी है?',
      ['To ensure the frame fits correctly', 'यह सुनिश्चित करने के लिए कि फ्रेम सही फिट हो'],
      ['To make aluminium heavier', 'एल्युमिनियम को भारी बनाने के लिए'],
      ['To increase electricity', 'बिजली बढ़ाने के लिए'],
      ['To change its colour', 'इसका रंग बदलने के लिए'],
      'A',
    ),
    q(
      'What is a measuring tape used for?',
      'मेजरिंग टेप का उपयोग किस लिए किया जाता है?',
      ['Measuring dimensions', 'माप लेने के लिए'],
      ['Cutting aluminium', 'एल्युमिनियम काटने के लिए'],
      ['Painting aluminium', 'एल्युमिनियम पेंट करने के लिए'],
      ['Welding aluminium', 'एल्युमिनियम वेल्ड करने के लिए'],
      'A',
    ),
    q(
      'What is a drill commonly used for?',
      'ड्रिल का सामान्य उपयोग किस लिए किया जाता है?',
      ['Making holes for suitable fixing', 'उचित फिक्सिंग के लिए छेद बनाने के लिए'],
      ['Painting walls', 'दीवार पेंट करने के लिए'],
      ['Measuring temperature', 'तापमान मापने के लिए'],
      ['Mixing cement', 'सीमेंट मिलाने के लिए'],
      'A',
    ),
    q(
      'What is a cutting machine used for in aluminium fabrication?',
      'एल्युमिनियम फैब्रिकेशन में कटिंग मशीन का उपयोग किस लिए किया जाता है?',
      ['Cutting aluminium profiles to the required size', 'एल्युमिनियम प्रोफाइल को आवश्यक आकार में काटने के लिए'],
      ['Measuring electricity', 'बिजली मापने के लिए'],
      ['Mixing paint', 'पेंट मिलाने के लिए'],
      ['Cleaning floors', 'फर्श साफ करने के लिए'],
      'A',
    ),
    q(
      'Why should aluminium edges be handled carefully?',
      'एल्युमिनियम के किनारों को सावधानी से क्यों संभालना चाहिए?',
      ['They can be sharp and cause cuts', 'वे तेज हो सकते हैं और कट लगा सकते हैं'],
      ['They can produce electricity', 'वे बिजली बना सकते हैं'],
      ['They can melt immediately', 'वे तुरंत पिघल सकते हैं'],
      ['They can absorb water', 'वे पानी सोख सकते हैं'],
      'A',
    ),
    q(
      'What should be checked before installing an aluminium frame?',
      'एल्युमिनियम फ्रेम लगाने से पहले क्या जांचना चाहिए?',
      ['Dimensions and alignment', 'माप और अलाइनमेंट'],
      ['Paint smell only', 'केवल पेंट की गंध'],
      ['Worker height', 'कर्मचारी की लंबाई'],
      ['Weather colour', 'मौसम का रंग'],
      'A',
    ),
    q(
      'Which PPE can protect the eyes when cutting aluminium?',
      'एल्युमिनियम काटते समय आंखों की सुरक्षा के लिए कौन सा PPE उपयोगी है?',
      ['Safety glasses', 'सेफ्टी ग्लास'],
      ['Safety shoes only', 'केवल सेफ्टी शूज़'],
      ['Cotton cap', 'सूती टोपी'],
      ['Earphones', 'ईयरफोन'],
      'A',
    ),
    q(
      'What is a screw commonly used for in aluminium installation?',
      'एल्युमिनियम इंस्टॉलेशन में स्क्रू का सामान्य उपयोग किस लिए किया जाता है?',
      ['Fixing or joining suitable components', 'उपयुक्त पार्ट्स को फिक्स या जोड़ने के लिए'],
      ['Measuring aluminium', 'एल्युमिनियम मापने के लिए'],
      ['Painting aluminium', 'एल्युमिनियम पेंट करने के लिए'],
      ['Cleaning glass', 'कांच साफ करने के लिए'],
      'A',
    ),
  ],
};

export const BASIC_TRADE_KNOWLEDGE_BANK: Record<UaeListedJob, TradeQuizQuestion[]> = {
  ...CORE_TRADE_KNOWLEDGE_BANK,
};
