ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS seo_title text,
  ADD COLUMN IF NOT EXISTS seo_description text,
  ADD COLUMN IF NOT EXISTS canonical_url text,
  ADD COLUMN IF NOT EXISTS indexable boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS noindex_reason text,
  ADD COLUMN IF NOT EXISTS first_published_at timestamptz;

ALTER TABLE public.employer_profiles
  ADD COLUMN IF NOT EXISTS public_slug text,
  ADD COLUMN IF NOT EXISTS is_public boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS public_description text,
  ADD COLUMN IF NOT EXISTS public_verified boolean NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS employer_profiles_public_slug_idx
  ON public.employer_profiles (public_slug)
  WHERE public_slug IS NOT NULL;
CREATE INDEX IF NOT EXISTS jobs_public_seo_idx
  ON public.jobs (status, indexable, country, city, category);

CREATE TABLE IF NOT EXISTS public.job_slug_redirects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  old_slug text NOT NULL UNIQUE,
  new_slug text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.job_slug_redirects TO anon, authenticated;
GRANT ALL ON public.job_slug_redirects TO service_role;
ALTER TABLE public.job_slug_redirects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can resolve job redirects"
  ON public.job_slug_redirects FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins manage job redirects"
  ON public.job_slug_redirects FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE TABLE IF NOT EXISTS public.seo_pages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  page_type text NOT NULL CHECK (page_type IN ('country','city','category','category_city','resource','employer','overview')),
  title text NOT NULL,
  description text NOT NULL,
  country text,
  city text,
  job_category text,
  content text,
  indexable boolean NOT NULL DEFAULT false,
  canonical_url text,
  noindex_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.seo_pages TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.seo_pages TO authenticated;
GRANT ALL ON public.seo_pages TO service_role;
ALTER TABLE public.seo_pages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read indexable SEO pages"
  ON public.seo_pages FOR SELECT TO anon, authenticated USING (indexable = true OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins create SEO pages"
  ON public.seo_pages FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins update SEO pages"
  ON public.seo_pages FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins delete SEO pages"
  ON public.seo_pages FOR DELETE TO authenticated USING (public.has_role(auth.uid(), 'admin'));

CREATE TABLE IF NOT EXISTS public.seo_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL CHECK (event_type IN ('landing_view','job_view','application_start','application_complete','registration_complete')),
  path text NOT NULL,
  job_id uuid REFERENCES public.jobs(id) ON DELETE SET NULL,
  country text,
  city text,
  category text,
  referrer_host text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  session_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT INSERT ON public.seo_events TO anon, authenticated;
GRANT SELECT ON public.seo_events TO authenticated;
GRANT ALL ON public.seo_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.seo_events_id_seq TO anon, authenticated, service_role;
ALTER TABLE public.seo_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Visitors can record SEO events"
  ON public.seo_events FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Admins can read SEO events"
  ON public.seo_events FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'));

CREATE OR REPLACE FUNCTION public.set_seo_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS seo_pages_updated_at ON public.seo_pages;
CREATE TRIGGER seo_pages_updated_at BEFORE UPDATE ON public.seo_pages
FOR EACH ROW EXECUTE FUNCTION public.set_seo_updated_at();

CREATE OR REPLACE FUNCTION public.generate_job_slug()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
DECLARE
  base_slug text;
  candidate text;
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.slug IS NOT DISTINCT FROM OLD.slug THEN
    RETURN NEW;
  END IF;
  IF NEW.slug IS NOT NULL AND btrim(NEW.slug) <> '' THEN
    base_slug := lower(regexp_replace(NEW.slug, '[^a-zA-Z0-9]+', '-', 'g'));
  ELSE
    base_slug := lower(regexp_replace(concat_ws('-', NEW.title, NEW.location, NEW.country), '[^a-zA-Z0-9]+', '-', 'g'));
  END IF;
  base_slug := trim(both '-' from regexp_replace(base_slug, '-+', '-', 'g'));
  candidate := base_slug || '-' || substring(NEW.id::text from 1 for 8);
  IF EXISTS (SELECT 1 FROM public.jobs j WHERE j.slug = candidate AND j.id <> NEW.id) THEN
    candidate := candidate || '-' || substring(md5(NEW.id::text) from 1 for 4);
  END IF;
  NEW.slug := candidate;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS generate_job_slug_trigger ON public.jobs;
CREATE TRIGGER generate_job_slug_trigger
BEFORE INSERT OR UPDATE OF slug ON public.jobs
FOR EACH ROW EXECUTE FUNCTION public.generate_job_slug();

CREATE OR REPLACE FUNCTION public.capture_job_slug_redirect()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF OLD.slug IS NOT NULL AND NEW.slug IS DISTINCT FROM OLD.slug THEN
    INSERT INTO public.job_slug_redirects(job_id, old_slug, new_slug)
    VALUES (NEW.id, OLD.slug, NEW.slug)
    ON CONFLICT (old_slug) DO UPDATE SET new_slug = EXCLUDED.new_slug, job_id = EXCLUDED.job_id;
    UPDATE public.job_slug_redirects SET new_slug = NEW.slug WHERE new_slug = OLD.slug;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS capture_job_slug_redirect_trigger ON public.jobs;
CREATE TRIGGER capture_job_slug_redirect_trigger
AFTER UPDATE OF slug ON public.jobs
FOR EACH ROW EXECUTE FUNCTION public.capture_job_slug_redirect();

CREATE OR REPLACE FUNCTION public.set_job_publication_fields()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF NEW.status = 'ACTIVE' AND NEW.first_published_at IS NULL THEN
    NEW.first_published_at := COALESCE(NEW.posted_at, now());
  END IF;
  NEW.city := COALESCE(NULLIF(btrim(NEW.city), ''), NULLIF(btrim(NEW.location), ''));
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS set_job_publication_fields_trigger ON public.jobs;
CREATE TRIGGER set_job_publication_fields_trigger
BEFORE INSERT OR UPDATE OF status, posted_at, location, city ON public.jobs
FOR EACH ROW EXECUTE FUNCTION public.set_job_publication_fields();

CREATE OR REPLACE FUNCTION public.public_job_by_slug(p_slug text)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'id', j.id,
    'slug', j.slug,
    'title', j.title,
    'description', j.description,
    'requirements', j.requirements,
    'responsibilities', j.responsibilities,
    'benefits', j.benefits,
    'location', j.location,
    'city', COALESCE(j.city, j.location),
    'country', j.country,
    'category', j.category,
    'job_type', j.job_type,
    'experience_level', j.experience_level,
    'salary_min', j.salary_min,
    'salary_max', j.salary_max,
    'salary_display', j.salary_display,
    'currency', j.currency,
    'openings', j.openings,
    'visa_sponsorship', j.visa_sponsorship,
    'remote_allowed', j.remote_allowed,
    'status', CASE WHEN j.status = 'ACTIVE' AND j.expires_at IS NOT NULL AND j.expires_at < now() THEN 'EXPIRED' ELSE j.status END,
    'posted_at', j.posted_at,
    'updated_at', j.updated_at,
    'expires_at', j.expires_at,
    'first_published_at', j.first_published_at,
    'seo_title', j.seo_title,
    'seo_description', j.seo_description,
    'canonical_url', j.canonical_url,
    'indexable', j.indexable,
    'noindex_reason', j.noindex_reason,
    'service_charge', j.service_charge,
    'employer', CASE WHEN ep.is_public THEN jsonb_build_object(
      'slug', ep.public_slug,
      'name', ep.company_name,
      'logo_url', ep.company_logo_url,
      'industry', ep.industry,
      'location', COALESCE(ep.emirate, ep.country),
      'description', ep.public_description,
      'verified', ep.public_verified
    ) ELSE NULL END,
    'skills', COALESCE((SELECT jsonb_agg(js.skill_name ORDER BY js.skill_name) FROM public.job_skills js WHERE js.job_id = j.id), '[]'::jsonb)
  )
  FROM public.jobs j
  LEFT JOIN public.employer_profiles ep ON ep.user_id = j.employer_id
  WHERE j.slug = p_slug
    AND j.first_published_at IS NOT NULL
    AND j.status IN ('ACTIVE','CLOSED','EXPIRED','PAUSED')
  LIMIT 1;
$$;
GRANT EXECUTE ON FUNCTION public.public_job_by_slug(text) TO anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public.public_employer_by_slug(p_slug text)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'slug', ep.public_slug,
    'name', ep.company_name,
    'logo_url', ep.company_logo_url,
    'industry', ep.industry,
    'location', COALESCE(ep.emirate, ep.country),
    'country', ep.country,
    'description', ep.public_description,
    'verified', ep.public_verified,
    'jobs', COALESCE((SELECT jsonb_agg(jsonb_build_object(
      'id', j.id, 'slug', j.slug, 'title', j.title, 'location', j.location,
      'country', j.country, 'category', j.category, 'salary_min', j.salary_min,
      'salary_max', j.salary_max, 'currency', j.currency, 'job_type', j.job_type,
      'experience_level', j.experience_level, 'posted_at', j.posted_at,
      'description', j.description, 'visa_sponsorship', j.visa_sponsorship
    ) ORDER BY j.posted_at DESC)
    FROM public.jobs j
    WHERE j.employer_id = ep.user_id AND j.status = 'ACTIVE'
      AND (j.expires_at IS NULL OR j.expires_at >= now()) AND j.indexable), '[]'::jsonb)
  )
  FROM public.employer_profiles ep
  WHERE ep.public_slug = p_slug AND ep.is_public = true
  LIMIT 1;
$$;
GRANT EXECUTE ON FUNCTION public.public_employer_by_slug(text) TO anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public.seo_health_summary()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE WHEN public.has_role(auth.uid(), 'admin') THEN jsonb_build_object(
    'jobs_total', (SELECT count(*) FROM public.jobs),
    'jobs_active', (SELECT count(*) FROM public.jobs WHERE status='ACTIVE' AND (expires_at IS NULL OR expires_at >= now())),
    'jobs_expired', (SELECT count(*) FROM public.jobs WHERE status='EXPIRED' OR (status='ACTIVE' AND expires_at < now())),
    'jobs_noindex', (SELECT count(*) FROM public.jobs WHERE NOT indexable),
    'jobs_missing_slug', (SELECT count(*) FROM public.jobs WHERE slug IS NULL OR btrim(slug)=''),
    'jobs_missing_meta', (SELECT count(*) FROM public.jobs WHERE status='ACTIVE' AND (seo_title IS NULL OR seo_description IS NULL)),
    'seo_pages_total', (SELECT count(*) FROM public.seo_pages),
    'seo_pages_indexable', (SELECT count(*) FROM public.seo_pages WHERE indexable),
    'seo_pages_noindex', (SELECT count(*) FROM public.seo_pages WHERE NOT indexable),
    'public_employers', (SELECT count(*) FROM public.employer_profiles WHERE is_public)
  ) ELSE NULL END;
$$;
REVOKE ALL ON FUNCTION public.seo_health_summary() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.seo_health_summary() TO authenticated, service_role;

COMMENT ON TABLE public.seo_pages IS 'Admin-controlled indexable landing and resource pages.';
COMMENT ON TABLE public.job_slug_redirects IS 'Permanent redirect history for public job slugs.';
COMMENT ON TABLE public.seo_events IS 'Privacy-conscious public SEO funnel events without user identifiers.';