-- Test 1: bilingual 4-option MCQ bank (14 UAE trades × 10 questions).
-- Correct option stays server-side; workers submit the option id.

ALTER TABLE public.worker_skill_quiz_items
  ADD COLUMN IF NOT EXISTS correct_option text;

ALTER TABLE public.worker_skill_quiz_responses
  ADD COLUMN IF NOT EXISTS selected_option text;

COMMENT ON COLUMN public.worker_skill_quiz_items.correct_option IS
  'MCQ answer key (option id). Never returned by get_worker_quiz_items.';
COMMENT ON COLUMN public.worker_skill_quiz_responses.selected_option IS
  'Worker-selected option id for 4-choice questions. Boolean Yes/No stays in answer.';

CREATE OR REPLACE FUNCTION public.grade_worker_quiz_response()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_expected boolean;
  v_correct_option text;
BEGIN
  SELECT expected_answer, correct_option
    INTO v_expected, v_correct_option
  FROM public.worker_skill_quiz_items
  WHERE id = NEW.quiz_item_id;

  IF v_correct_option IS NOT NULL AND length(trim(v_correct_option)) > 0 THEN
    NEW.is_correct := (
      NEW.selected_option IS NOT NULL
      AND NEW.selected_option = v_correct_option
    );
  ELSIF v_expected IS NULL THEN
    NEW.is_correct := false;
  ELSE
    NEW.is_correct := (NEW.answer IS NOT NULL AND NEW.answer = v_expected);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_grade_worker_quiz_response ON public.worker_skill_quiz_responses;
CREATE TRIGGER trg_grade_worker_quiz_response
BEFORE INSERT OR UPDATE ON public.worker_skill_quiz_responses
FOR EACH ROW EXECUTE FUNCTION public.grade_worker_quiz_response();

CREATE OR REPLACE FUNCTION public.submit_worker_quiz(p_answers jsonb, p_user_id uuid DEFAULT NULL)
RETURNS TABLE (score numeric, correct_count integer, total_count integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_subject uuid;
  v_total integer := 0;
  v_correct integer := 0;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;
  IF p_answers IS NULL OR jsonb_typeof(p_answers) <> 'array' THEN
    RAISE EXCEPTION 'Invalid answers payload';
  END IF;

  v_subject := COALESCE(p_user_id, v_uid);
  IF v_subject IS DISTINCT FROM v_uid AND NOT public.partner_manages_worker(v_subject) THEN
    RAISE EXCEPTION 'Not allowed to submit a quiz for this worker';
  END IF;

  INSERT INTO public.worker_skill_quiz_responses (user_id, quiz_item_id, answer, selected_option, is_correct)
  SELECT v_subject,
         (a->>'quiz_item_id')::uuid,
         CASE
           WHEN jsonb_typeof(a->'answer') = 'boolean' THEN (a->>'answer')::boolean
           WHEN lower(COALESCE(a->>'answer', '')) IN ('true', 'false') THEN (a->>'answer')::boolean
           ELSE false
         END,
         CASE
           WHEN jsonb_typeof(a->'answer') = 'boolean' THEN NULL
           WHEN lower(COALESCE(a->>'answer', '')) IN ('true', 'false') THEN NULL
           ELSE NULLIF(trim(a->>'answer'), '')
         END,
         false
  FROM jsonb_array_elements(p_answers) a
  WHERE (a->>'quiz_item_id') IS NOT NULL
  ON CONFLICT (user_id, quiz_item_id) DO UPDATE
    SET answer = EXCLUDED.answer,
        selected_option = EXCLUDED.selected_option;

  SELECT count(*)::int,
         count(*) FILTER (WHERE r.is_correct)::int
    INTO v_total, v_correct
  FROM public.worker_skill_quiz_responses r
  WHERE r.user_id = v_subject
    AND r.quiz_item_id IN (
      SELECT (a->>'quiz_item_id')::uuid FROM jsonb_array_elements(p_answers) a
      WHERE (a->>'quiz_item_id') IS NOT NULL
    );

  RETURN QUERY
  SELECT CASE WHEN v_total > 0
              THEN round((v_correct::numeric / v_total) * 1000) / 10
              ELSE 0 END,
         v_correct,
         v_total;
END;
$$;

REVOKE ALL ON FUNCTION public.submit_worker_quiz(jsonb, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.submit_worker_quiz(jsonb, uuid) TO authenticated;

-- Retire old Yes/No items for trades that now have a 10-question MCQ bank.
UPDATE public.worker_skill_quiz_items
SET active = false, updated_at = now()
WHERE skill_code IN (
    'Electrician', 'Plumber', 'Welder', 'Mason', 'Carpenter', 'Helper', 'HVAC Technician',
    'Shuttering Carpenter', 'Mason (tiles/marble)', 'Construction Labour/Helper',
    'Pipe Fitter', 'Furniture Carpenter - Finishing, All Rounder', 'Steel Fixer',
    'AC Technician', 'General Labour - Warehouse/Supermarket', 'Scaffolder',
    'Painter', 'Aluminium Fixer/Fabricator'
  )
  AND (options IS NULL OR jsonb_typeof(options) <> 'array' OR jsonb_array_length(options) < 2);

-- 10 questions, 60% pass (6/10) per UAE listed trade.
UPDATE public.skill_quiz_configs
SET questions_to_show = 10,
    pass_score = 60,
    selection_mode = 'random_active',
    active = true,
    updated_at = now()
WHERE region IS NULL
  AND skill_code IN (
    'Electrician', 'Welder', 'Plumber', 'Shuttering Carpenter',
    'Mason (tiles/marble)', 'Construction Labour/Helper', 'Pipe Fitter',
    'Furniture Carpenter - Finishing, All Rounder', 'Steel Fixer',
    'AC Technician', 'General Labour - Warehouse/Supermarket',
    'Scaffolder', 'Painter', 'Aluminium Fixer/Fabricator'
  );

INSERT INTO public.skill_quiz_configs
  (skill_code, region, questions_to_show, selection_mode, selected_ids, pass_score, active)
SELECT v.skill_code, NULL, 10, 'random_active', '{}'::uuid[], 60, true
FROM (VALUES
  ('Electrician'),
  ('Welder'),
  ('Plumber'),
  ('Shuttering Carpenter'),
  ('Mason (tiles/marble)'),
  ('Construction Labour/Helper'),
  ('Pipe Fitter'),
  ('Furniture Carpenter - Finishing, All Rounder'),
  ('Steel Fixer'),
  ('AC Technician'),
  ('General Labour - Warehouse/Supermarket'),
  ('Scaffolder'),
  ('Painter'),
  ('Aluminium Fixer/Fabricator')
) AS v(skill_code)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.skill_quiz_configs c
  WHERE c.skill_code = v.skill_code
    AND c.region IS NULL
);


-- Bilingual MCQ seed (14 trades × 10).
DELETE FROM public.worker_skill_quiz_responses
WHERE quiz_item_id IN (
  SELECT id FROM public.worker_skill_quiz_items WHERE correct_option IS NOT NULL
);
DELETE FROM public.worker_skill_quiz_items WHERE correct_option IS NOT NULL;

INSERT INTO public.worker_skill_quiz_items
  (skill_code, question, question_hi, options, correct_option, sort_order)
VALUES
  ('Electrician', 'What is the main purpose of an MCB?', 'MCB का मुख्य उद्देश्य क्या है?', '[{"id":"A","en":"To increase voltage","hi":"वोल्टेज बढ़ाना"},{"id":"B","en":"To protect the electrical circuit","hi":"विद्युत सर्किट की सुरक्षा करना"},{"id":"C","en":"To store electricity","hi":"बिजली को स्टोर करना"},{"id":"D","en":"To measure temperature","hi":"तापमान मापना"}]'::jsonb, 'B', 1),
  ('Electrician', 'What is a multimeter used for?', 'मल्टीमीटर का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Cutting wires","hi":"तार काटने के लिए"},{"id":"B","en":"Measuring electrical values","hi":"विद्युत मान मापने के लिए"},{"id":"C","en":"Tightening bolts","hi":"बोल्ट कसने के लिए"},{"id":"D","en":"Cutting pipes","hi":"पाइप काटने के लिए"}]'::jsonb, 'B', 2),
  ('Electrician', 'Why is earthing used in electrical systems?', 'विद्युत सिस्टम में अर्थिंग क्यों की जाती है?', '[{"id":"A","en":"To increase electricity consumption","hi":"बिजली की खपत बढ़ाने के लिए"},{"id":"B","en":"To provide protection from electrical faults","hi":"विद्युत खराबी से सुरक्षा के लिए"},{"id":"C","en":"To make wires longer","hi":"तारों को लंबा करने के लिए"},{"id":"D","en":"To increase light brightness","hi":"रोशनी बढ़ाने के लिए"}]'::jsonb, 'B', 3),
  ('Electrician', 'What should you do before working on an electrical circuit?', 'विद्युत सर्किट पर काम करने से पहले आपको क्या करना चाहिए?', '[{"id":"A","en":"Increase the voltage","hi":"वोल्टेज बढ़ाना"},{"id":"B","en":"Switch off/isolate the power","hi":"बिजली की सप्लाई बंद/आइसोलेट करना"},{"id":"C","en":"Touch the wire to check it","hi":"तार को छूकर जांचना"},{"id":"D","en":"Pour water on the circuit","hi":"सर्किट पर पानी डालना"}]'::jsonb, 'B', 4),
  ('Electrician', 'What is an electrical switch used for?', 'विद्युत स्विच का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Controlling ON/OFF of a circuit","hi":"सर्किट को चालू/बंद करने के लिए"},{"id":"B","en":"Measuring current","hi":"करंट मापने के लिए"},{"id":"C","en":"Cutting cables","hi":"केबल काटने के लिए"},{"id":"D","en":"Joining pipes","hi":"पाइप जोड़ने के लिए"}]'::jsonb, 'A', 5),
  ('Electrician', 'Which tool is commonly used to tighten electrical terminal screws?', 'विद्युत टर्मिनल के स्क्रू कसने के लिए सामान्यतः किस उपकरण का उपयोग किया जाता है?', '[{"id":"A","en":"Screwdriver","hi":"स्क्रूड्राइवर"},{"id":"B","en":"Pipe wrench","hi":"पाइप रिंच"},{"id":"C","en":"Hammer drill","hi":"हैमर ड्रिल"},{"id":"D","en":"Hacksaw","hi":"हैक्सॉ"}]'::jsonb, 'A', 6),
  ('Electrician', 'What is an electrical cable mainly used for?', 'विद्युत केबल का मुख्य उपयोग किस लिए होता है?', '[{"id":"A","en":"Carrying electrical current","hi":"विद्युत करंट ले जाने के लिए"},{"id":"B","en":"Carrying water","hi":"पानी ले जाने के लिए"},{"id":"C","en":"Supporting walls","hi":"दीवारों को सहारा देने के लिए"},{"id":"D","en":"Painting surfaces","hi":"सतहों पर पेंट करने के लिए"}]'::jsonb, 'A', 7),
  ('Electrician', 'What should you do if you find a damaged electrical wire?', 'यदि आपको कोई क्षतिग्रस्त विद्युत तार मिले तो आपको क्या करना चाहिए?', '[{"id":"A","en":"Continue using it","hi":"उसका उपयोग जारी रखना"},{"id":"B","en":"Touch it with your hand","hi":"उसे हाथ से छूना"},{"id":"C","en":"Report it and repair/replace it safely","hi":"इसकी सूचना देकर सुरक्षित रूप से मरम्मत/बदलना"},{"id":"D","en":"Pour water on it","hi":"उस पर पानी डालना"}]'::jsonb, 'C', 8),
  ('Electrician', 'Which equipment protects the eyes during electrical work from flying particles?', 'विद्युत कार्य के दौरान उड़ने वाले कणों से आंखों की सुरक्षा के लिए क्या उपयोग किया जाता है?', '[{"id":"A","en":"Safety glasses","hi":"सेफ्टी ग्लास"},{"id":"B","en":"Safety belt","hi":"सेफ्टी बेल्ट"},{"id":"C","en":"Safety shoes","hi":"सेफ्टी शूज़"},{"id":"D","en":"Ear plugs","hi":"ईयर प्लग"}]'::jsonb, 'A', 9),
  ('Electrician', 'What is a socket used for?', 'इलेक्ट्रिकल सॉकेट का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Connecting an electrical plug to a power supply","hi":"विद्युत प्लग को बिजली की सप्लाई से जोड़ने के लिए"},{"id":"B","en":"Cutting wires","hi":"तार काटने के लिए"},{"id":"C","en":"Measuring pipes","hi":"पाइप मापने के लिए"},{"id":"D","en":"Holding concrete","hi":"कंक्रीट को पकड़ने के लिए"}]'::jsonb, 'A', 10),
  ('Welder', 'What is welding?', 'वेल्डिंग क्या है?', '[{"id":"A","en":"Painting metal","hi":"धातु पर पेंट करना"},{"id":"B","en":"Joining metal using heat, pressure, or both","hi":"गर्मी, दबाव या दोनों की सहायता से धातु जोड़ना"},{"id":"C","en":"Cutting wood","hi":"लकड़ी काटना"},{"id":"D","en":"Cleaning pipes","hi":"पाइप साफ करना"}]'::jsonb, 'B', 1),
  ('Welder', 'What is a welding helmet used for?', 'वेल्डिंग हेलमेट का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Protecting the head and eyes from the welding arc","hi":"वेल्डिंग आर्क से सिर और आंखों की सुरक्षा के लिए"},{"id":"B","en":"Measuring metal","hi":"धातु मापने के लिए"},{"id":"C","en":"Cutting steel","hi":"स्टील काटने के लिए"},{"id":"D","en":"Carrying tools","hi":"उपकरण ले जाने के लिए"}]'::jsonb, 'A', 2),
  ('Welder', 'What is a welding electrode used for?', 'वेल्डिंग इलेक्ट्रोड का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Creating the welding arc and/or providing filler metal","hi":"वेल्डिंग आर्क बनाने और/या फिलर मेटल देने के लिए"},{"id":"B","en":"Measuring temperature","hi":"तापमान मापने के लिए"},{"id":"C","en":"Cleaning the floor","hi":"फर्श साफ करने के लिए"},{"id":"D","en":"Painting metal","hi":"धातु पर पेंट करने के लिए"}]'::jsonb, 'A', 3),
  ('Welder', 'Why are welding gloves worn?', 'वेल्डिंग ग्लव्स क्यों पहने जाते हैं?', '[{"id":"A","en":"To protect hands from heat and sparks","hi":"हाथों को गर्मी और चिंगारी से बचाने के लिए"},{"id":"B","en":"To improve eyesight","hi":"दृष्टि बेहतर करने के लिए"},{"id":"C","en":"To measure voltage","hi":"वोल्टेज मापने के लिए"},{"id":"D","en":"To hold water","hi":"पानी पकड़ने के लिए"}]'::jsonb, 'A', 4),
  ('Welder', 'What should you check before starting welding?', 'वेल्डिंग शुरू करने से पहले क्या जांचना चाहिए?', '[{"id":"A","en":"Welding equipment and safety equipment","hi":"वेल्डिंग उपकरण और सुरक्षा उपकरण"},{"id":"B","en":"Refrigerator","hi":"फ्रिज"},{"id":"C","en":"Water tank","hi":"पानी की टंकी"},{"id":"D","en":"Office computer","hi":"ऑफिस कंप्यूटर"}]'::jsonb, 'A', 5),
  ('Welder', 'Why should the welding area be kept clean?', 'वेल्डिंग क्षेत्र को साफ क्यों रखना चाहिए?', '[{"id":"A","en":"To reduce accidents and fire hazards","hi":"दुर्घटना और आग के खतरे को कम करने के लिए"},{"id":"B","en":"To increase welding noise","hi":"वेल्डिंग का शोर बढ़ाने के लिए"},{"id":"C","en":"To make metal heavier","hi":"धातु को भारी बनाने के लिए"},{"id":"D","en":"To increase electricity use","hi":"बिजली की खपत बढ़ाने के लिए"}]'::jsonb, 'A', 6),
  ('Welder', 'Can freshly welded metal be touched immediately?', 'क्या अभी-अभी वेल्ड की गई धातु को तुरंत छू सकते हैं?', '[{"id":"A","en":"Yes, always","hi":"हां, हमेशा"},{"id":"B","en":"Yes, with bare hands","hi":"हां, नंगे हाथों से"},{"id":"C","en":"No, it may be very hot","hi":"नहीं, यह बहुत गर्म हो सकती है"},{"id":"D","en":"Only with water","hi":"केवल पानी से"}]'::jsonb, 'C', 7),
  ('Welder', 'Why is ventilation important during welding?', 'वेल्डिंग के दौरान वेंटिलेशन क्यों जरूरी है?', '[{"id":"A","en":"To reduce exposure to welding fumes","hi":"वेल्डिंग के धुएं के संपर्क को कम करने के लिए"},{"id":"B","en":"To increase sparks","hi":"चिंगारी बढ़ाने के लिए"},{"id":"C","en":"To cool the welding machine only","hi":"केवल वेल्डिंग मशीन को ठंडा करने के लिए"},{"id":"D","en":"To make the metal heavier","hi":"धातु को भारी बनाने के लिए"}]'::jsonb, 'A', 8),
  ('Welder', 'Which tool is commonly used to remove welding slag?', 'वेल्डिंग स्लैग हटाने के लिए सामान्यतः किस उपकरण का उपयोग किया जाता है?', '[{"id":"A","en":"Chipping hammer","hi":"चिपिंग हैमर"},{"id":"B","en":"Pipe wrench","hi":"पाइप रिंच"},{"id":"C","en":"Paint roller","hi":"पेंट रोलर"},{"id":"D","en":"Screwdriver","hi":"स्क्रूड्राइवर"}]'::jsonb, 'A', 9),
  ('Welder', 'What should a welder wear to protect the body from sparks?', 'चिंगारी से शरीर की सुरक्षा के लिए वेल्डर को क्या पहनना चाहिए?', '[{"id":"A","en":"Suitable protective clothing","hi":"उपयुक्त सुरक्षात्मक कपड़े"},{"id":"B","en":"Plastic shopping bag","hi":"प्लास्टिक बैग"},{"id":"C","en":"Loose synthetic clothing","hi":"ढीले सिंथेटिक कपड़े"},{"id":"D","en":"Normal sandals","hi":"सामान्य चप्पल"}]'::jsonb, 'A', 10),
  ('Plumber', 'What is the main work of a plumber?', 'प्लम्बर का मुख्य काम क्या होता है?', '[{"id":"A","en":"Installing and repairing pipe systems","hi":"पाइप सिस्टम लगाना और उसकी मरम्मत करना"},{"id":"B","en":"Painting cars","hi":"कारों पर पेंट करना"},{"id":"C","en":"Welding only","hi":"केवल वेल्डिंग करना"},{"id":"D","en":"Installing electrical panels","hi":"इलेक्ट्रिकल पैनल लगाना"}]'::jsonb, 'A', 1),
  ('Plumber', 'What is a pipe used for?', 'पाइप का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Carrying water or other fluids","hi":"पानी या अन्य तरल पदार्थ ले जाने के लिए"},{"id":"B","en":"Measuring electricity","hi":"बिजली मापने के लिए"},{"id":"C","en":"Painting walls","hi":"दीवारों पर पेंट करने के लिए"},{"id":"D","en":"Cutting wood","hi":"लकड़ी काटने के लिए"}]'::jsonb, 'A', 2),
  ('Plumber', 'What is a valve used for?', 'वाल्व का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Controlling or stopping fluid flow","hi":"तरल पदार्थ के प्रवाह को नियंत्रित या बंद करने के लिए"},{"id":"B","en":"Cutting wood","hi":"लकड़ी काटने के लिए"},{"id":"C","en":"Measuring temperature","hi":"तापमान मापने के लिए"},{"id":"D","en":"Mixing paint","hi":"पेंट मिलाने के लिए"}]'::jsonb, 'A', 3),
  ('Plumber', 'What is a pipe wrench used for?', 'पाइप रिंच का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Turning and gripping pipes","hi":"पाइप को पकड़ने और घुमाने के लिए"},{"id":"B","en":"Cutting tiles","hi":"टाइल काटने के लिए"},{"id":"C","en":"Painting walls","hi":"दीवार पेंट करने के लिए"},{"id":"D","en":"Measuring voltage","hi":"वोल्टेज मापने के लिए"}]'::jsonb, 'A', 4),
  ('Plumber', 'What is an elbow fitting used for?', 'एल्बो फिटिंग का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Changing the direction of a pipe","hi":"पाइप की दिशा बदलने के लिए"},{"id":"B","en":"Measuring water pressure","hi":"पानी का दबाव मापने के लिए"},{"id":"C","en":"Cutting pipes","hi":"पाइप काटने के लिए"},{"id":"D","en":"Painting pipes","hi":"पाइप पर पेंट करने के लिए"}]'::jsonb, 'A', 5),
  ('Plumber', 'What is Teflon/PTFE tape commonly used for?', 'Teflon/PTFE टेप का सामान्य उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Sealing threaded pipe connections","hi":"थ्रेडेड पाइप कनेक्शन को सील करने के लिए"},{"id":"B","en":"Cutting pipes","hi":"पाइप काटने के लिए"},{"id":"C","en":"Painting pipes","hi":"पाइप पेंट करने के लिए"},{"id":"D","en":"Measuring pipes","hi":"पाइप मापने के लिए"}]'::jsonb, 'A', 6),
  ('Plumber', 'What should you normally do before repairing a water pipe?', 'पानी के पाइप की मरम्मत से पहले सामान्यतः क्या करना चाहिए?', '[{"id":"A","en":"Shut off the water supply if required","hi":"आवश्यकता होने पर पानी की सप्लाई बंद करना"},{"id":"B","en":"Open all taps","hi":"सभी नल खोलना"},{"id":"C","en":"Increase water pressure","hi":"पानी का दबाव बढ़ाना"},{"id":"D","en":"Heat the pipe","hi":"पाइप को गर्म करना"}]'::jsonb, 'A', 7),
  ('Plumber', 'What is a drainage pipe used for?', 'ड्रेनेज पाइप का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Carrying wastewater away","hi":"गंदा पानी बाहर ले जाने के लिए"},{"id":"B","en":"Carrying electricity","hi":"बिजली ले जाने के लिए"},{"id":"C","en":"Supporting a building","hi":"इमारत को सहारा देने के लिए"},{"id":"D","en":"Carrying paint","hi":"पेंट ले जाने के लिए"}]'::jsonb, 'A', 8),
  ('Plumber', 'What is a tap used for?', 'नल का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Controlling the flow of water","hi":"पानी के प्रवाह को नियंत्रित करने के लिए"},{"id":"B","en":"Cutting metal","hi":"धातु काटने के लिए"},{"id":"C","en":"Measuring electricity","hi":"बिजली मापने के लिए"},{"id":"D","en":"Joining steel","hi":"स्टील जोड़ने के लिए"}]'::jsonb, 'A', 9),
  ('Plumber', 'What should be checked after installing a pipe joint?', 'पाइप जॉइंट लगाने के बाद क्या जांचना चाहिए?', '[{"id":"A","en":"Whether it leaks","hi":"कहीं लीकेज तो नहीं है"},{"id":"B","en":"Whether it changes colour","hi":"उसका रंग बदलता है या नहीं"},{"id":"C","en":"Whether it becomes heavier","hi":"वह भारी होता है या नहीं"},{"id":"D","en":"Whether it produces electricity","hi":"वह बिजली बनाता है या नहीं"}]'::jsonb, 'A', 10),
  ('Shuttering Carpenter', 'What is shuttering/formwork used for?', 'शटरिंग/फॉर्मवर्क का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Holding wet concrete in the required shape","hi":"गीले कंक्रीट को आवश्यक आकार में रखने के लिए"},{"id":"B","en":"Painting walls","hi":"दीवार पेंट करने के लिए"},{"id":"C","en":"Carrying water","hi":"पानी ले जाने के लिए"},{"id":"D","en":"Cutting electrical cables","hi":"इलेक्ट्रिकल केबल काटने के लिए"}]'::jsonb, 'A', 1),
  ('Shuttering Carpenter', 'Which material is commonly used for shuttering?', 'शटरिंग में सामान्यतः किस सामग्री का उपयोग किया जाता है?', '[{"id":"A","en":"Plywood","hi":"प्लाईवुड"},{"id":"B","en":"Glass only","hi":"केवल कांच"},{"id":"C","en":"Cloth","hi":"कपड़ा"},{"id":"D","en":"Paper","hi":"कागज"}]'::jsonb, 'A', 2),
  ('Shuttering Carpenter', 'Why must shuttering be properly supported?', 'शटरिंग को सही तरीके से सपोर्ट देना क्यों जरूरी है?', '[{"id":"A","en":"To prevent movement or collapse","hi":"हिलने या गिरने से रोकने के लिए"},{"id":"B","en":"To make concrete softer","hi":"कंक्रीट को नरम बनाने के लिए"},{"id":"C","en":"To increase paint colour","hi":"पेंट का रंग बढ़ाने के लिए"},{"id":"D","en":"To reduce concrete size","hi":"कंक्रीट का आकार कम करने के लिए"}]'::jsonb, 'A', 3),
  ('Shuttering Carpenter', 'What is a measuring tape used for?', 'मेजरिंग टेप का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Measuring dimensions","hi":"माप लेने के लिए"},{"id":"B","en":"Cutting concrete","hi":"कंक्रीट काटने के लिए"},{"id":"C","en":"Mixing cement","hi":"सीमेंट मिलाने के लिए"},{"id":"D","en":"Painting","hi":"पेंट करने के लिए"}]'::jsonb, 'A', 4),
  ('Shuttering Carpenter', 'Why is proper alignment of shuttering important?', 'शटरिंग का सही अलाइनमेंट क्यों जरूरी है?', '[{"id":"A","en":"To get the correct shape and position of concrete","hi":"कंक्रीट का सही आकार और स्थिति प्राप्त करने के लिए"},{"id":"B","en":"To make wood heavier","hi":"लकड़ी को भारी बनाने के लिए"},{"id":"C","en":"To increase electricity","hi":"बिजली बढ़ाने के लिए"},{"id":"D","en":"To make cement dry instantly","hi":"सीमेंट को तुरंत सुखाने के लिए"}]'::jsonb, 'A', 5),
  ('Shuttering Carpenter', 'What is a hammer commonly used for?', 'हैमर का सामान्य उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Driving or removing nails","hi":"कील लगाने या निकालने के लिए"},{"id":"B","en":"Measuring voltage","hi":"वोल्टेज मापने के लिए"},{"id":"C","en":"Testing water pressure","hi":"पानी का दबाव जांचने के लिए"},{"id":"D","en":"Mixing paint","hi":"पेंट मिलाने के लिए"}]'::jsonb, 'A', 6),
  ('Shuttering Carpenter', 'What should be checked before concrete is poured?', 'कंक्रीट डालने से पहले क्या जांचना चाहिए?', '[{"id":"A","en":"Supports, alignment and dimensions","hi":"सपोर्ट, अलाइनमेंट और माप"},{"id":"B","en":"Office furniture","hi":"ऑफिस का फर्नीचर"},{"id":"C","en":"Worker uniforms only","hi":"केवल कर्मचारियों की यूनिफॉर्म"},{"id":"D","en":"Vehicle fuel","hi":"वाहन का ईंधन"}]'::jsonb, 'A', 7),
  ('Shuttering Carpenter', 'What can happen if shuttering is not strong enough?', 'यदि शटरिंग पर्याप्त मजबूत नहीं हो तो क्या हो सकता है?', '[{"id":"A","en":"It can move or collapse","hi":"यह हिल या गिर सकती है"},{"id":"B","en":"Concrete becomes electricity","hi":"कंक्रीट बिजली बन जाएगा"},{"id":"C","en":"Wood becomes steel","hi":"लकड़ी स्टील बन जाएगी"},{"id":"D","en":"Cement changes colour","hi":"सीमेंट का रंग बदल जाएगा"}]'::jsonb, 'A', 8),
  ('Shuttering Carpenter', 'Why should shuttering be removed carefully?', 'शटरिंग को सावधानी से क्यों हटाना चाहिए?', '[{"id":"A","en":"To avoid damaging concrete and causing accidents","hi":"कंक्रीट को नुकसान और दुर्घटना से बचाने के लिए"},{"id":"B","en":"To make concrete wet","hi":"कंक्रीट को गीला करने के लिए"},{"id":"C","en":"To increase concrete weight","hi":"कंक्रीट का वजन बढ़ाने के लिए"},{"id":"D","en":"To change concrete colour","hi":"कंक्रीट का रंग बदलने के लिए"}]'::jsonb, 'A', 9),
  ('Shuttering Carpenter', 'Which tool is useful for checking whether a surface is level?', 'किसी सतह का लेवल जांचने के लिए कौन सा उपकरण उपयोगी है?', '[{"id":"A","en":"Spirit level","hi":"स्पिरिट लेवल"},{"id":"B","en":"Pipe wrench","hi":"पाइप रिंच"},{"id":"C","en":"Welding electrode","hi":"वेल्डिंग इलेक्ट्रोड"},{"id":"D","en":"Paint brush","hi":"पेंट ब्रश"}]'::jsonb, 'A', 10),
  ('Mason (tiles/marble)', 'What is a trowel commonly used for?', 'ट्रॉवेल का सामान्य उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Applying and spreading mortar or plaster","hi":"मोर्टार या प्लास्टर लगाने और फैलाने के लिए"},{"id":"B","en":"Measuring electricity","hi":"बिजली मापने के लिए"},{"id":"C","en":"Cutting electrical wires","hi":"विद्युत तार काटने के लिए"},{"id":"D","en":"Welding steel","hi":"स्टील वेल्ड करने के लिए"}]'::jsonb, 'A', 1),
  ('Mason (tiles/marble)', 'What is cement mainly used for in masonry work?', 'राजमिस्त्री के काम में सीमेंट का मुख्य उपयोग क्या है?', '[{"id":"A","en":"As a binding material","hi":"बांधने वाली सामग्री के रूप में"},{"id":"B","en":"As electrical insulation","hi":"विद्युत इंसुलेशन के रूप में"},{"id":"C","en":"As a paint thinner","hi":"पेंट थिनर के रूप में"},{"id":"D","en":"As a fuel","hi":"ईंधन के रूप में"}]'::jsonb, 'A', 2),
  ('Mason (tiles/marble)', 'What is plastering?', 'प्लास्टरिंग क्या है?', '[{"id":"A","en":"Applying a finishing layer to a wall or surface","hi":"दीवार या सतह पर फिनिशिंग की परत लगाना"},{"id":"B","en":"Joining electrical wires","hi":"विद्युत तार जोड़ना"},{"id":"C","en":"Cutting steel","hi":"स्टील काटना"},{"id":"D","en":"Installing air conditioners","hi":"एयर कंडीशनर लगाना"}]'::jsonb, 'A', 3),
  ('Mason (tiles/marble)', 'What is tile adhesive used for?', 'टाइल एडहेसिव का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Fixing tiles to a suitable surface","hi":"टाइल को उपयुक्त सतह पर लगाने के लिए"},{"id":"B","en":"Cutting tiles","hi":"टाइल काटने के लिए"},{"id":"C","en":"Painting tiles","hi":"टाइल पेंट करने के लिए"},{"id":"D","en":"Measuring tiles","hi":"टाइल मापने के लिए"}]'::jsonb, 'A', 4),
  ('Mason (tiles/marble)', 'Why should the surface be cleaned before fixing tiles?', 'टाइल लगाने से पहले सतह को साफ क्यों करना चाहिए?', '[{"id":"A","en":"To help proper bonding","hi":"सही बॉन्डिंग के लिए"},{"id":"B","en":"To increase dust","hi":"धूल बढ़ाने के लिए"},{"id":"C","en":"To make tiles heavier","hi":"टाइल को भारी बनाने के लिए"},{"id":"D","en":"To change tile colour","hi":"टाइल का रंग बदलने के लिए"}]'::jsonb, 'A', 5),
  ('Mason (tiles/marble)', 'What is a spirit level used for?', 'स्पिरिट लेवल का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Checking whether a surface is level","hi":"सतह का लेवल जांचने के लिए"},{"id":"B","en":"Cutting marble","hi":"मार्बल काटने के लिए"},{"id":"C","en":"Mixing cement","hi":"सीमेंट मिलाने के लिए"},{"id":"D","en":"Measuring electricity","hi":"बिजली मापने के लिए"}]'::jsonb, 'A', 6),
  ('Mason (tiles/marble)', 'Why is correct tile alignment important?', 'टाइल का सही अलाइनमेंट क्यों जरूरी है?', '[{"id":"A","en":"For a straight and good-quality finish","hi":"सीधी और अच्छी फिनिश के लिए"},{"id":"B","en":"To increase water pressure","hi":"पानी का दबाव बढ़ाने के लिए"},{"id":"C","en":"To increase electricity","hi":"बिजली बढ़ाने के लिए"},{"id":"D","en":"To make tiles softer","hi":"टाइल को नरम बनाने के लिए"}]'::jsonb, 'A', 7),
  ('Mason (tiles/marble)', 'What is mortar commonly made from?', 'मोर्टार सामान्यतः किससे बनाया जाता है?', '[{"id":"A","en":"Cement, sand and water","hi":"सीमेंट, रेत और पानी"},{"id":"B","en":"Oil and petrol","hi":"तेल और पेट्रोल"},{"id":"C","en":"Paint and water","hi":"पेंट और पानी"},{"id":"D","en":"Steel and aluminium","hi":"स्टील और एल्युमिनियम"}]'::jsonb, 'A', 8),
  ('Mason (tiles/marble)', 'Which tool is commonly used to cut tiles?', 'टाइल काटने के लिए सामान्यतः किस उपकरण का उपयोग किया जाता है?', '[{"id":"A","en":"Tile cutter","hi":"टाइल कटर"},{"id":"B","en":"Pipe wrench","hi":"पाइप रिंच"},{"id":"C","en":"Screwdriver","hi":"स्क्रूड्राइवर"},{"id":"D","en":"Welding electrode","hi":"वेल्डिंग इलेक्ट्रोड"}]'::jsonb, 'A', 9),
  ('Mason (tiles/marble)', 'Which PPE can protect a mason''s eyes from dust and particles?', 'धूल और कणों से राजमिस्त्री की आंखों की सुरक्षा के लिए कौन सा PPE उपयोगी है?', '[{"id":"A","en":"Safety glasses","hi":"सेफ्टी ग्लास"},{"id":"B","en":"Cotton shirt","hi":"सूती शर्ट"},{"id":"C","en":"Safety belt","hi":"सेफ्टी बेल्ट"},{"id":"D","en":"Earphones","hi":"ईयरफोन"}]'::jsonb, 'A', 10),
  ('Construction Labour/Helper', 'What is the main role of a construction helper?', 'कंस्ट्रक्शन हेल्पर की मुख्य भूमिका क्या होती है?', '[{"id":"A","en":"Assist skilled workers with basic site work","hi":"कुशल श्रमिकों को सामान्य साइट कार्य में सहायता करना"},{"id":"B","en":"Design the entire building","hi":"पूरी इमारत का डिजाइन बनाना"},{"id":"C","en":"Approve building plans","hi":"बिल्डिंग प्लान को मंजूर करना"},{"id":"D","en":"Manage the company","hi":"कंपनी चलाना"}]'::jsonb, 'A', 1),
  ('Construction Labour/Helper', 'Why is a safety helmet worn on a construction site?', 'कंस्ट्रक्शन साइट पर सेफ्टी हेलमेट क्यों पहना जाता है?', '[{"id":"A","en":"To protect the head","hi":"सिर की सुरक्षा के लिए"},{"id":"B","en":"To protect the feet","hi":"पैरों की सुरक्षा के लिए"},{"id":"C","en":"To measure temperature","hi":"तापमान मापने के लिए"},{"id":"D","en":"To carry tools","hi":"उपकरण ले जाने के लिए"}]'::jsonb, 'A', 2),
  ('Construction Labour/Helper', 'Why are safety shoes used?', 'सेफ्टी शूज़ क्यों पहने जाते हैं?', '[{"id":"A","en":"To protect the feet","hi":"पैरों की सुरक्षा के लिए"},{"id":"B","en":"To improve walking speed","hi":"चलने की गति बढ़ाने के लिए"},{"id":"C","en":"To measure distance","hi":"दूरी मापने के लिए"},{"id":"D","en":"To protect the eyes","hi":"आंखों की सुरक्षा के लिए"}]'::jsonb, 'A', 3),
  ('Construction Labour/Helper', 'What should you do if you do not understand a work instruction?', 'यदि आपको काम का निर्देश समझ नहीं आता है तो क्या करना चाहिए?', '[{"id":"A","en":"Ask the supervisor","hi":"सुपरवाइजर से पूछना चाहिए"},{"id":"B","en":"Guess and continue","hi":"अनुमान लगाकर काम जारी रखना चाहिए"},{"id":"C","en":"Leave the site","hi":"साइट छोड़ देनी चाहिए"},{"id":"D","en":"Ignore the instruction","hi":"निर्देश को नजरअंदाज करना चाहिए"}]'::jsonb, 'A', 4),
  ('Construction Labour/Helper', 'What should you do before lifting a very heavy object?', 'बहुत भारी वस्तु उठाने से पहले क्या करना चाहिए?', '[{"id":"A","en":"Use proper lifting methods and ask for help if needed","hi":"सही तरीके से उठाएं और जरूरत होने पर मदद लें"},{"id":"B","en":"Lift it suddenly","hi":"अचानक उठा लें"},{"id":"C","en":"Throw it","hi":"उसे फेंक दें"},{"id":"D","en":"Kick it","hi":"उसे लात मारें"}]'::jsonb, 'A', 5),
  ('Construction Labour/Helper', 'Why should construction areas be kept clean?', 'कंस्ट्रक्शन क्षेत्र को साफ क्यों रखना चाहिए?', '[{"id":"A","en":"To reduce trips and accidents","hi":"ठोकर और दुर्घटनाओं को कम करने के लिए"},{"id":"B","en":"To increase dust","hi":"धूल बढ़ाने के लिए"},{"id":"C","en":"To make tools difficult to find","hi":"उपकरण ढूंढना मुश्किल करने के लिए"},{"id":"D","en":"To slow down work","hi":"काम धीमा करने के लिए"}]'::jsonb, 'A', 6),
  ('Construction Labour/Helper', 'Can you operate a machine without proper training or authorization?', 'क्या उचित ट्रेनिंग या अनुमति के बिना मशीन चला सकते हैं?', '[{"id":"A","en":"Yes","hi":"हां"},{"id":"B","en":"No","hi":"नहीं"},{"id":"C","en":"Only at night","hi":"केवल रात में"},{"id":"D","en":"Only when alone","hi":"केवल अकेले होने पर"}]'::jsonb, 'B', 7),
  ('Construction Labour/Helper', 'What should you do if you see an unsafe condition?', 'यदि आपको कोई असुरक्षित स्थिति दिखाई दे तो क्या करना चाहिए?', '[{"id":"A","en":"Report it to the supervisor","hi":"सुपरवाइजर को इसकी सूचना दें"},{"id":"B","en":"Ignore it","hi":"नजरअंदाज करें"},{"id":"C","en":"Hide it","hi":"उसे छिपा दें"},{"id":"D","en":"Continue working without informing anyone","hi":"किसी को बताए बिना काम जारी रखें"}]'::jsonb, 'A', 8),
  ('Construction Labour/Helper', 'What does PPE stand for?', 'PPE का पूरा नाम क्या है?', '[{"id":"A","en":"Personal Protective Equipment","hi":"पर्सनल प्रोटेक्टिव इक्विपमेंट"},{"id":"B","en":"Personal Power Engine","hi":"पर्सनल पावर इंजन"},{"id":"C","en":"Public Protection Entry","hi":"पब्लिक प्रोटेक्शन एंट्री"},{"id":"D","en":"Professional Plumbing Equipment","hi":"प्रोफेशनल प्लंबिंग इक्विपमेंट"}]'::jsonb, 'A', 9),
  ('Construction Labour/Helper', 'Why is following safety instructions important?', 'सुरक्षा निर्देशों का पालन करना क्यों जरूरी है?', '[{"id":"A","en":"To reduce accidents and injuries","hi":"दुर्घटनाओं और चोटों को कम करने के लिए"},{"id":"B","en":"To increase working hours","hi":"काम के घंटे बढ़ाने के लिए"},{"id":"C","en":"To make tools heavier","hi":"उपकरणों को भारी बनाने के लिए"},{"id":"D","en":"To slow down construction","hi":"कंस्ट्रक्शन धीमा करने के लिए"}]'::jsonb, 'A', 10),
  ('Pipe Fitter', 'What does a pipe fitter mainly do?', 'पाइप फिटर का मुख्य काम क्या होता है?', '[{"id":"A","en":"Installs and connects piping systems","hi":"पाइपिंग सिस्टम लगाना और जोड़ना"},{"id":"B","en":"Paints walls","hi":"दीवारों पर पेंट करना"},{"id":"C","en":"Repairs electrical circuits","hi":"इलेक्ट्रिकल सर्किट की मरम्मत करना"},{"id":"D","en":"Installs tiles only","hi":"केवल टाइल लगाना"}]'::jsonb, 'A', 1),
  ('Pipe Fitter', 'What does GI commonly mean in GI pipe?', 'GI पाइप में GI का सामान्य अर्थ क्या है?', '[{"id":"A","en":"Galvanized Iron","hi":"गैल्वनाइज्ड आयरन"},{"id":"B","en":"General Insulation","hi":"जनरल इंसुलेशन"},{"id":"C","en":"Ground Installation","hi":"ग्राउंड इंस्टॉलेशन"},{"id":"D","en":"Gas Indicator","hi":"गैस इंडिकेटर"}]'::jsonb, 'A', 2),
  ('Pipe Fitter', 'What is an elbow used for in piping?', 'पाइपिंग में एल्बो का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Changing the direction of a pipe","hi":"पाइप की दिशा बदलने के लिए"},{"id":"B","en":"Measuring pipe length","hi":"पाइप की लंबाई मापने के लिए"},{"id":"C","en":"Cutting steel","hi":"स्टील काटने के लिए"},{"id":"D","en":"Painting pipes","hi":"पाइप पेंट करने के लिए"}]'::jsonb, 'A', 3),
  ('Pipe Fitter', 'What is a tee fitting used for?', 'टी फिटिंग का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Creating a branch in a pipe system","hi":"पाइप सिस्टम में ब्रांच बनाने के लिए"},{"id":"B","en":"Cutting pipes","hi":"पाइप काटने के लिए"},{"id":"C","en":"Measuring pressure","hi":"दबाव मापने के लिए"},{"id":"D","en":"Painting pipes","hi":"पाइप पेंट करने के लिए"}]'::jsonb, 'A', 4),
  ('Pipe Fitter', 'What is a reducer used for?', 'रिड्यूसर का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Connecting pipes of different sizes","hi":"अलग-अलग आकार के पाइप जोड़ने के लिए"},{"id":"B","en":"Measuring pipe temperature","hi":"पाइप का तापमान मापने के लिए"},{"id":"C","en":"Cutting steel","hi":"स्टील काटने के लिए"},{"id":"D","en":"Cleaning floors","hi":"फर्श साफ करने के लिए"}]'::jsonb, 'A', 5),
  ('Pipe Fitter', 'Which tool is commonly used to grip and turn a pipe?', 'पाइप को पकड़ने और घुमाने के लिए किस उपकरण का उपयोग किया जाता है?', '[{"id":"A","en":"Pipe wrench","hi":"पाइप रिंच"},{"id":"B","en":"Paint brush","hi":"पेंट ब्रश"},{"id":"C","en":"Trowel","hi":"ट्रॉवेल"},{"id":"D","en":"Tile cutter","hi":"टाइल कटर"}]'::jsonb, 'A', 6),
  ('Pipe Fitter', 'Why is correct pipe alignment important?', 'पाइप का सही अलाइनमेंट क्यों जरूरी है?', '[{"id":"A","en":"For proper installation and to reduce leakage/stress","hi":"सही इंस्टॉलेशन और लीकेज/तनाव कम करने के लिए"},{"id":"B","en":"To make pipes colourful","hi":"पाइप को रंगीन बनाने के लिए"},{"id":"C","en":"To increase electricity","hi":"बिजली बढ़ाने के लिए"},{"id":"D","en":"To make pipes heavier","hi":"पाइप को भारी बनाने के लिए"}]'::jsonb, 'A', 7),
  ('Pipe Fitter', 'What should be checked after joining pipes?', 'पाइप जोड़ने के बाद क्या जांचना चाहिए?', '[{"id":"A","en":"Connections and possible leaks","hi":"कनेक्शन और संभावित लीकेज"},{"id":"B","en":"Paint colour only","hi":"केवल पेंट का रंग"},{"id":"C","en":"Worker height","hi":"कर्मचारी की लंबाई"},{"id":"D","en":"Floor colour","hi":"फर्श का रंग"}]'::jsonb, 'A', 8),
  ('Pipe Fitter', 'What is a coupling generally used for?', 'कपलिंग का सामान्य उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Joining two pipes","hi":"दो पाइप जोड़ने के लिए"},{"id":"B","en":"Cutting a pipe","hi":"पाइप काटने के लिए"},{"id":"C","en":"Measuring electricity","hi":"बिजली मापने के लिए"},{"id":"D","en":"Painting a wall","hi":"दीवार पेंट करने के लिए"}]'::jsonb, 'A', 9),
  ('Pipe Fitter', 'Why should gloves be worn when handling steel pipes?', 'स्टील पाइप संभालते समय ग्लव्स क्यों पहनने चाहिए?', '[{"id":"A","en":"To protect hands from cuts and sharp edges","hi":"हाथों को कटने और तेज किनारों से बचाने के लिए"},{"id":"B","en":"To increase pipe size","hi":"पाइप का आकार बढ़ाने के लिए"},{"id":"C","en":"To measure pressure","hi":"दबाव मापने के लिए"},{"id":"D","en":"To make pipes lighter","hi":"पाइप को हल्का बनाने के लिए"}]'::jsonb, 'A', 10),
  ('Furniture Carpenter - Finishing, All Rounder', 'What is a carpenter mainly involved in?', 'कारपेंटर मुख्य रूप से किस काम से जुड़ा होता है?', '[{"id":"A","en":"Working with wood and related materials","hi":"लकड़ी और संबंधित सामग्री के साथ काम करना"},{"id":"B","en":"Repairing electrical circuits","hi":"विद्युत सर्किट की मरम्मत करना"},{"id":"C","en":"Installing water pumps only","hi":"केवल पानी के पंप लगाना"},{"id":"D","en":"Welding pipes","hi":"पाइप वेल्ड करना"}]'::jsonb, 'A', 1),
  ('Furniture Carpenter - Finishing, All Rounder', 'What is a saw used for?', 'आरी का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Cutting wood","hi":"लकड़ी काटने के लिए"},{"id":"B","en":"Measuring electricity","hi":"बिजली मापने के लिए"},{"id":"C","en":"Mixing cement","hi":"सीमेंट मिलाने के लिए"},{"id":"D","en":"Tightening bolts","hi":"बोल्ट कसने के लिए"}]'::jsonb, 'A', 2),
  ('Furniture Carpenter - Finishing, All Rounder', 'What is a hammer commonly used for?', 'हैमर का सामान्य उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Driving nails","hi":"कील लगाने के लिए"},{"id":"B","en":"Measuring wood","hi":"लकड़ी मापने के लिए"},{"id":"C","en":"Cutting pipes","hi":"पाइप काटने के लिए"},{"id":"D","en":"Testing electricity","hi":"बिजली जांचने के लिए"}]'::jsonb, 'A', 3),
  ('Furniture Carpenter - Finishing, All Rounder', 'What is a screwdriver used for?', 'स्क्रूड्राइवर का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Tightening or removing screws","hi":"स्क्रू कसने या निकालने के लिए"},{"id":"B","en":"Cutting wood","hi":"लकड़ी काटने के लिए"},{"id":"C","en":"Mixing paint","hi":"पेंट मिलाने के लिए"},{"id":"D","en":"Measuring water","hi":"पानी मापने के लिए"}]'::jsonb, 'A', 4),
  ('Furniture Carpenter - Finishing, All Rounder', 'Why is accurate measurement important in carpentry?', 'कारपेंटरी में सही माप लेना क्यों जरूरी है?', '[{"id":"A","en":"To ensure proper size and fit","hi":"सही आकार और फिट सुनिश्चित करने के लिए"},{"id":"B","en":"To make wood heavier","hi":"लकड़ी को भारी बनाने के लिए"},{"id":"C","en":"To increase electricity","hi":"बिजली बढ़ाने के लिए"},{"id":"D","en":"To change wood colour","hi":"लकड़ी का रंग बदलने के लिए"}]'::jsonb, 'A', 5),
  ('Furniture Carpenter - Finishing, All Rounder', 'What is plywood?', 'प्लाईवुड क्या है?', '[{"id":"A","en":"A wood-based panel made from layers of veneer","hi":"लकड़ी की परतों से बना एक पैनल"},{"id":"B","en":"A type of steel","hi":"एक प्रकार का स्टील"},{"id":"C","en":"A type of pipe","hi":"एक प्रकार का पाइप"},{"id":"D","en":"A type of cement","hi":"एक प्रकार का सीमेंट"}]'::jsonb, 'A', 6),
  ('Furniture Carpenter - Finishing, All Rounder', 'What is a nail used for?', 'कील का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Joining or fixing suitable materials","hi":"उपयुक्त सामग्री को जोड़ने या फिक्स करने के लिए"},{"id":"B","en":"Measuring voltage","hi":"वोल्टेज मापने के लिए"},{"id":"C","en":"Cutting tiles","hi":"टाइल काटने के लिए"},{"id":"D","en":"Painting wood","hi":"लकड़ी पेंट करने के लिए"}]'::jsonb, 'A', 7),
  ('Furniture Carpenter - Finishing, All Rounder', 'What is sandpaper used for?', 'सैंडपेपर का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Smoothing a surface","hi":"सतह को चिकना करने के लिए"},{"id":"B","en":"Joining pipes","hi":"पाइप जोड़ने के लिए"},{"id":"C","en":"Measuring electricity","hi":"बिजली मापने के लिए"},{"id":"D","en":"Welding steel","hi":"स्टील वेल्ड करने के लिए"}]'::jsonb, 'A', 8),
  ('Furniture Carpenter - Finishing, All Rounder', 'Why should carpentry tools be kept in good condition?', 'कारपेंटरी के उपकरणों को अच्छी स्थिति में क्यों रखना चाहिए?', '[{"id":"A","en":"For safe and effective work","hi":"सुरक्षित और प्रभावी काम के लिए"},{"id":"B","en":"To increase their weight","hi":"उनका वजन बढ़ाने के लिए"},{"id":"C","en":"To make them colourful","hi":"उन्हें रंगीन बनाने के लिए"},{"id":"D","en":"To reduce their size","hi":"उनका आकार कम करने के लिए"}]'::jsonb, 'A', 9),
  ('Furniture Carpenter - Finishing, All Rounder', 'Which PPE protects the eyes from wood dust and particles?', 'लकड़ी की धूल और कणों से आंखों की सुरक्षा के लिए कौन सा PPE उपयोगी है?', '[{"id":"A","en":"Safety glasses","hi":"सेफ्टी ग्लास"},{"id":"B","en":"Safety belt","hi":"सेफ्टी बेल्ट"},{"id":"C","en":"Safety shoes only","hi":"केवल सेफ्टी शूज़"},{"id":"D","en":"Ear plugs","hi":"ईयर प्लग"}]'::jsonb, 'A', 10),
  ('Steel Fixer', 'What does a steel fixer mainly work with?', 'स्टील फिक्सर मुख्य रूप से किसके साथ काम करता है?', '[{"id":"A","en":"Reinforcement steel","hi":"रिइन्फोर्समेंट स्टील"},{"id":"B","en":"Paint","hi":"पेंट"},{"id":"C","en":"Glass only","hi":"केवल कांच"},{"id":"D","en":"Electrical wires","hi":"विद्युत तार"}]'::jsonb, 'A', 1),
  ('Steel Fixer', 'What is rebar?', 'रीबार क्या होता है?', '[{"id":"A","en":"Reinforcement steel bar","hi":"रिइन्फोर्समेंट स्टील बार"},{"id":"B","en":"A type of paint","hi":"एक प्रकार का पेंट"},{"id":"C","en":"A plumbing valve","hi":"प्लंबिंग वाल्व"},{"id":"D","en":"A wooden panel","hi":"लकड़ी का पैनल"}]'::jsonb, 'A', 2),
  ('Steel Fixer', 'Why is reinforcement steel placed in concrete?', 'कंक्रीट में रिइन्फोर्समेंट स्टील क्यों लगाया जाता है?', '[{"id":"A","en":"To provide additional structural strength","hi":"संरचना को अतिरिक्त मजबूती देने के लिए"},{"id":"B","en":"To change its colour","hi":"उसका रंग बदलने के लिए"},{"id":"C","en":"To make it lighter","hi":"उसे हल्का बनाने के लिए"},{"id":"D","en":"To make it waterproof by itself","hi":"इसे अपने आप वाटरप्रूफ बनाने के लिए"}]'::jsonb, 'A', 3),
  ('Steel Fixer', 'What is binding wire used for?', 'बाइंडिंग वायर का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Tying reinforcement bars together","hi":"रिइन्फोर्समेंट बार को आपस में बांधने के लिए"},{"id":"B","en":"Carrying electricity","hi":"बिजली ले जाने के लिए"},{"id":"C","en":"Cutting concrete","hi":"कंक्रीट काटने के लिए"},{"id":"D","en":"Painting steel","hi":"स्टील पेंट करने के लिए"}]'::jsonb, 'A', 4),
  ('Steel Fixer', 'What is a rebar bending machine used for?', 'रीबार बेंडिंग मशीन का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Bending reinforcement bars","hi":"रिइन्फोर्समेंट बार को मोड़ने के लिए"},{"id":"B","en":"Cutting wood","hi":"लकड़ी काटने के लिए"},{"id":"C","en":"Mixing cement","hi":"सीमेंट मिलाने के लिए"},{"id":"D","en":"Painting steel","hi":"स्टील पेंट करने के लिए"}]'::jsonb, 'A', 5),
  ('Steel Fixer', 'Why is correct spacing between reinforcement bars important?', 'रिइन्फोर्समेंट बार के बीच सही दूरी क्यों जरूरी है?', '[{"id":"A","en":"To place reinforcement according to the required design","hi":"निर्धारित डिजाइन के अनुसार रिइन्फोर्समेंट लगाने के लिए"},{"id":"B","en":"To make steel colourful","hi":"स्टील को रंगीन बनाने के लिए"},{"id":"C","en":"To reduce steel strength","hi":"स्टील की मजबूती कम करने के लिए"},{"id":"D","en":"To make concrete dry faster","hi":"कंक्रीट को जल्दी सुखाने के लिए"}]'::jsonb, 'A', 6),
  ('Steel Fixer', 'Why should steel bars be handled carefully?', 'स्टील बार को सावधानी से क्यों संभालना चाहिए?', '[{"id":"A","en":"They can be heavy and have sharp edges","hi":"वे भारी हो सकते हैं और उनके किनारे तेज हो सकते हैं"},{"id":"B","en":"They can melt in sunlight","hi":"वे धूप में पिघल सकते हैं"},{"id":"C","en":"They produce electricity automatically","hi":"वे अपने आप बिजली बनाते हैं"},{"id":"D","en":"They are made of glass","hi":"वे कांच से बने होते हैं"}]'::jsonb, 'A', 7),
  ('Steel Fixer', 'What should you use when moving very heavy steel bars?', 'बहुत भारी स्टील बार को स्थानांतरित करते समय क्या उपयोग करना चाहिए?', '[{"id":"A","en":"Proper assistance or lifting equipment","hi":"उचित सहायता या लिफ्टिंग उपकरण"},{"id":"B","en":"Bare hands only","hi":"केवल नंगे हाथ"},{"id":"C","en":"A paint brush","hi":"पेंट ब्रश"},{"id":"D","en":"A screwdriver","hi":"स्क्रूड्राइवर"}]'::jsonb, 'A', 8),
  ('Steel Fixer', 'What tool is commonly used to tie reinforcement bars with binding wire?', 'बाइंडिंग वायर से रिइन्फोर्समेंट बार बांधने के लिए किस उपकरण का उपयोग किया जाता है?', '[{"id":"A","en":"Rebar tying hook","hi":"रीबार टाइंग हुक"},{"id":"B","en":"Paint roller","hi":"पेंट रोलर"},{"id":"C","en":"Pipe wrench","hi":"पाइप रिंच"},{"id":"D","en":"Tile cutter","hi":"टाइल कटर"}]'::jsonb, 'A', 9),
  ('Steel Fixer', 'What should you wear when handling reinforcement steel?', 'रिइन्फोर्समेंट स्टील संभालते समय क्या पहनना चाहिए?', '[{"id":"A","en":"Suitable gloves and safety footwear","hi":"उपयुक्त ग्लव्स और सेफ्टी फुटवियर"},{"id":"B","en":"Slippers only","hi":"केवल चप्पल"},{"id":"C","en":"No PPE","hi":"कोई PPE नहीं"},{"id":"D","en":"Loose jewellery","hi":"ढीली ज्वेलरी"}]'::jsonb, 'A', 10),
  ('AC Technician', 'What is the main purpose of an air conditioner?', 'एयर कंडीशनर का मुख्य उद्देश्य क्या है?', '[{"id":"A","en":"To cool and condition indoor air","hi":"कमरे की हवा को ठंडा और नियंत्रित करना"},{"id":"B","en":"To heat steel","hi":"स्टील गर्म करना"},{"id":"C","en":"To pump water","hi":"पानी पंप करना"},{"id":"D","en":"To generate electricity","hi":"बिजली बनाना"}]'::jsonb, 'A', 1),
  ('AC Technician', 'What is the main function of an AC filter?', 'AC फिल्टर का मुख्य काम क्या है?', '[{"id":"A","en":"To help remove dust and particles from air","hi":"हवा से धूल और कण हटाने में मदद करना"},{"id":"B","en":"To increase voltage","hi":"वोल्टेज बढ़ाना"},{"id":"C","en":"To store refrigerant","hi":"रेफ्रिजरेंट स्टोर करना"},{"id":"D","en":"To produce electricity","hi":"बिजली बनाना"}]'::jsonb, 'A', 2),
  ('AC Technician', 'What is a compressor in an AC system?', 'AC सिस्टम में कंप्रेसर क्या होता है?', '[{"id":"A","en":"A major component that compresses and circulates refrigerant","hi":"एक मुख्य घटक जो रेफ्रिजरेंट को कंप्रेस और सर्कुलेट करता है"},{"id":"B","en":"An electrical switch only","hi":"केवल इलेक्ट्रिकल स्विच"},{"id":"C","en":"An air filter","hi":"एयर फिल्टर"},{"id":"D","en":"A water tank","hi":"पानी की टंकी"}]'::jsonb, 'A', 3),
  ('AC Technician', 'What is refrigerant used for in an AC?', 'AC में रेफ्रिजरेंट का उपयोग किस लिए होता है?', '[{"id":"A","en":"Transferring heat in the cooling system","hi":"कूलिंग सिस्टम में गर्मी को ट्रांसफर करने के लिए"},{"id":"B","en":"Cleaning floors","hi":"फर्श साफ करने के लिए"},{"id":"C","en":"Painting walls","hi":"दीवार पेंट करने के लिए"},{"id":"D","en":"Lubricating doors","hi":"दरवाजों को चिकना करने के लिए"}]'::jsonb, 'A', 4),
  ('AC Technician', 'Why should an AC filter be cleaned?', 'AC फिल्टर को साफ क्यों करना चाहिए?', '[{"id":"A","en":"To maintain proper airflow and efficient operation","hi":"सही एयरफ्लो और बेहतर संचालन के लिए"},{"id":"B","en":"To increase room temperature","hi":"कमरे का तापमान बढ़ाने के लिए"},{"id":"C","en":"To increase electricity consumption","hi":"बिजली की खपत बढ़ाने के लिए"},{"id":"D","en":"To make the AC heavier","hi":"AC को भारी बनाने के लिए"}]'::jsonb, 'A', 5),
  ('AC Technician', 'What is the indoor unit of a split AC?', 'स्प्लिट AC की इनडोर यूनिट क्या होती है?', '[{"id":"A","en":"The unit installed inside the room","hi":"कमरे के अंदर लगाई जाने वाली यूनिट"},{"id":"B","en":"The outdoor compressor only","hi":"केवल आउटडोर कंप्रेसर"},{"id":"C","en":"The electrical meter","hi":"बिजली का मीटर"},{"id":"D","en":"The water tank","hi":"पानी की टंकी"}]'::jsonb, 'A', 6),
  ('AC Technician', 'What is the outdoor unit?', 'आउटडोर यूनिट क्या होती है?', '[{"id":"A","en":"The external unit containing components such as the compressor and condenser","hi":"बाहर लगी यूनिट जिसमें कंप्रेसर और कंडेंसर जैसे घटक होते हैं"},{"id":"B","en":"The indoor air filter only","hi":"केवल इनडोर एयर फिल्टर"},{"id":"C","en":"The room thermostat only","hi":"केवल रूम थर्मोस्टेट"},{"id":"D","en":"The electrical socket","hi":"इलेक्ट्रिकल सॉकेट"}]'::jsonb, 'A', 7),
  ('AC Technician', 'What should be done before working on an AC''s electrical components?', 'AC के इलेक्ट्रिकल पार्ट्स पर काम करने से पहले क्या करना चाहिए?', '[{"id":"A","en":"Safely isolate/switch off the electrical supply","hi":"इलेक्ट्रिकल सप्लाई को सुरक्षित रूप से बंद/आइसोलेट करना"},{"id":"B","en":"Pour water on the unit","hi":"यूनिट पर पानी डालना"},{"id":"C","en":"Touch the wires","hi":"तारों को छूना"},{"id":"D","en":"Increase the voltage","hi":"वोल्टेज बढ़ाना"}]'::jsonb, 'A', 8),
  ('AC Technician', 'What can happen if an AC filter is heavily blocked with dust?', 'यदि AC फिल्टर धूल से बहुत ज्यादा ब्लॉक हो जाए तो क्या हो सकता है?', '[{"id":"A","en":"Airflow can be reduced","hi":"एयरफ्लो कम हो सकता है"},{"id":"B","en":"The room becomes larger","hi":"कमरा बड़ा हो जाता है"},{"id":"C","en":"The AC becomes a heater automatically","hi":"AC अपने आप हीटर बन जाता है"},{"id":"D","en":"Refrigerant becomes water","hi":"रेफ्रिजरेंट पानी बन जाता है"}]'::jsonb, 'A', 9),
  ('AC Technician', 'Why should PPE be used when working on an AC?', 'AC पर काम करते समय PPE का उपयोग क्यों करना चाहिए?', '[{"id":"A","en":"To protect against electrical and other workplace hazards","hi":"विद्युत और अन्य कार्यस्थल के खतरों से सुरक्षा के लिए"},{"id":"B","en":"To make the AC colder","hi":"AC को अधिक ठंडा करने के लिए"},{"id":"C","en":"To increase refrigerant pressure","hi":"रेफ्रिजरेंट का दबाव बढ़ाने के लिए"},{"id":"D","en":"To reduce room size","hi":"कमरे का आकार कम करने के लिए"}]'::jsonb, 'A', 10),
  ('General Labour - Warehouse/Supermarket', 'What is a common job of a warehouse worker?', 'वेयरहाउस वर्कर का सामान्य काम क्या होता है?', '[{"id":"A","en":"Moving, sorting and organizing goods","hi":"सामान को ले जाना, छांटना और व्यवस्थित करना"},{"id":"B","en":"Designing buildings","hi":"इमारतों का डिजाइन बनाना"},{"id":"C","en":"Repairing electrical panels","hi":"इलेक्ट्रिकल पैनल की मरम्मत करना"},{"id":"D","en":"Welding structures","hi":"स्ट्रक्चर वेल्ड करना"}]'::jsonb, 'A', 1),
  ('General Labour - Warehouse/Supermarket', 'What is stock?', 'स्टॉक क्या होता है?', '[{"id":"A","en":"Goods/products kept for sale or use","hi":"बिक्री या उपयोग के लिए रखे गए सामान/उत्पाद"},{"id":"B","en":"A type of machine","hi":"एक प्रकार की मशीन"},{"id":"C","en":"A safety helmet","hi":"सेफ्टी हेलमेट"},{"id":"D","en":"A type of pipe","hi":"एक प्रकार का पाइप"}]'::jsonb, 'A', 2),
  ('General Labour - Warehouse/Supermarket', 'Why should warehouse aisles be kept clear?', 'वेयरहाउस के रास्ते/आइल्स खाली क्यों रखने चाहिए?', '[{"id":"A","en":"For safe movement and to prevent accidents","hi":"सुरक्षित आवाजाही और दुर्घटनाओं से बचने के लिए"},{"id":"B","en":"To store more waste","hi":"अधिक कचरा रखने के लिए"},{"id":"C","en":"To block workers","hi":"कर्मचारियों को रोकने के लिए"},{"id":"D","en":"To reduce visibility","hi":"दिखाई देना कम करने के लिए"}]'::jsonb, 'A', 3),
  ('General Labour - Warehouse/Supermarket', 'What is a barcode mainly used for?', 'बारकोड का मुख्य उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Identifying and tracking products","hi":"उत्पादों की पहचान और ट्रैकिंग के लिए"},{"id":"B","en":"Cutting boxes","hi":"डिब्बे काटने के लिए"},{"id":"C","en":"Measuring temperature","hi":"तापमान मापने के लिए"},{"id":"D","en":"Cleaning shelves","hi":"शेल्फ साफ करने के लिए"}]'::jsonb, 'A', 4),
  ('General Labour - Warehouse/Supermarket', 'What should you do if you find damaged stock?', 'यदि आपको क्षतिग्रस्त स्टॉक मिले तो क्या करना चाहिए?', '[{"id":"A","en":"Report it according to workplace procedure","hi":"कार्यस्थल की प्रक्रिया के अनुसार इसकी सूचना दें"},{"id":"B","en":"Hide it","hi":"उसे छिपा दें"},{"id":"C","en":"Sell it without informing anyone","hi":"बिना बताए बेच दें"},{"id":"D","en":"Throw it anywhere","hi":"कहीं भी फेंक दें"}]'::jsonb, 'A', 5),
  ('General Labour - Warehouse/Supermarket', 'What should you do when a box is too heavy to lift safely?', 'यदि कोई बॉक्स सुरक्षित रूप से उठाने के लिए बहुत भारी है तो क्या करना चाहिए?', '[{"id":"A","en":"Ask for help or use suitable equipment","hi":"मदद मांगें या उचित उपकरण का उपयोग करें"},{"id":"B","en":"Lift it alone immediately","hi":"अकेले तुरंत उठाएं"},{"id":"C","en":"Kick it","hi":"उसे लात मारें"},{"id":"D","en":"Throw it","hi":"उसे फेंक दें"}]'::jsonb, 'A', 6),
  ('General Labour - Warehouse/Supermarket', 'Why is stock counting important?', 'स्टॉक की गिनती करना क्यों जरूरी है?', '[{"id":"A","en":"To know how much stock is available","hi":"उपलब्ध स्टॉक की मात्रा जानने के लिए"},{"id":"B","en":"To make products heavier","hi":"उत्पादों को भारी बनाने के लिए"},{"id":"C","en":"To change product prices automatically","hi":"उत्पाद की कीमत अपने आप बदलने के लिए"},{"id":"D","en":"To clean the warehouse","hi":"वेयरहाउस साफ करने के लिए"}]'::jsonb, 'A', 7),
  ('General Labour - Warehouse/Supermarket', 'Can an untrained worker operate a forklift?', 'क्या बिना ट्रेनिंग वाला कर्मचारी फोर्कलिफ्ट चला सकता है?', '[{"id":"A","en":"Yes","hi":"हां"},{"id":"B","en":"No","hi":"नहीं"},{"id":"C","en":"Only after lunch","hi":"केवल लंच के बाद"},{"id":"D","en":"Only when the warehouse is empty","hi":"केवल वेयरहाउस खाली होने पर"}]'::jsonb, 'B', 8),
  ('General Labour - Warehouse/Supermarket', 'Why should products be stored properly?', 'उत्पादों को सही तरीके से क्यों रखना चाहिए?', '[{"id":"A","en":"To prevent damage and maintain safety","hi":"नुकसान से बचाने और सुरक्षा बनाए रखने के लिए"},{"id":"B","en":"To make them difficult to find","hi":"उन्हें ढूंढना मुश्किल बनाने के लिए"},{"id":"C","en":"To increase dust","hi":"धूल बढ़ाने के लिए"},{"id":"D","en":"To block aisles","hi":"रास्ते बंद करने के लिए"}]'::jsonb, 'A', 9),
  ('General Labour - Warehouse/Supermarket', 'What should you do if you notice a safety hazard in the warehouse?', 'यदि आपको वेयरहाउस में कोई सुरक्षा खतरा दिखाई दे तो क्या करना चाहिए?', '[{"id":"A","en":"Report it to the supervisor","hi":"सुपरवाइजर को इसकी सूचना दें"},{"id":"B","en":"Ignore it","hi":"नजरअंदाज करें"},{"id":"C","en":"Hide it","hi":"उसे छिपा दें"},{"id":"D","en":"Continue working without informing anyone","hi":"किसी को बताए बिना काम जारी रखें"}]'::jsonb, 'A', 10),
  ('Scaffolder', 'What is scaffolding used for?', 'स्कैफोल्डिंग का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Providing a temporary working platform/access at height","hi":"ऊंचाई पर अस्थायी कार्य प्लेटफॉर्म/पहुंच प्रदान करने के लिए"},{"id":"B","en":"Carrying water","hi":"पानी ले जाने के लिए"},{"id":"C","en":"Painting vehicles","hi":"वाहनों पर पेंट करने के लिए"},{"id":"D","en":"Cutting electrical wires","hi":"विद्युत तार काटने के लिए"}]'::jsonb, 'A', 1),
  ('Scaffolder', 'Why must scaffolding be stable?', 'स्कैफोल्डिंग का स्थिर होना क्यों जरूरी है?', '[{"id":"A","en":"To prevent movement and collapse","hi":"हिलने और गिरने से बचाने के लिए"},{"id":"B","en":"To make it heavier","hi":"इसे भारी बनाने के लिए"},{"id":"C","en":"To increase its height automatically","hi":"इसकी ऊंचाई अपने आप बढ़ाने के लिए"},{"id":"D","en":"To make it easier to paint","hi":"इसे पेंट करना आसान बनाने के लिए"}]'::jsonb, 'A', 2),
  ('Scaffolder', 'What is a scaffold platform?', 'स्कैफोल्ड प्लेटफॉर्म क्या होता है?', '[{"id":"A","en":"The working surface where workers stand","hi":"वह कार्य सतह जहां कर्मचारी खड़े होकर काम करते हैं"},{"id":"B","en":"A type of pipe","hi":"एक प्रकार का पाइप"},{"id":"C","en":"A type of electrical cable","hi":"एक प्रकार की इलेक्ट्रिकल केबल"},{"id":"D","en":"A safety helmet","hi":"सेफ्टी हेलमेट"}]'::jsonb, 'A', 3),
  ('Scaffolder', 'What is a guardrail used for?', 'गार्डरेल का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Helping prevent workers from falling","hi":"कर्मचारियों को गिरने से बचाने में मदद करने के लिए"},{"id":"B","en":"Measuring height","hi":"ऊंचाई मापने के लिए"},{"id":"C","en":"Carrying tools","hi":"उपकरण ले जाने के लिए"},{"id":"D","en":"Joining pipes","hi":"पाइप जोड़ने के लिए"}]'::jsonb, 'A', 4),
  ('Scaffolder', 'Can damaged scaffold components be used?', 'क्या क्षतिग्रस्त स्कैफोल्डिंग पार्ट्स का उपयोग किया जा सकता है?', '[{"id":"A","en":"Yes, always","hi":"हां, हमेशा"},{"id":"B","en":"No, they should be reported","hi":"नहीं, इसकी सूचना देनी चाहिए"},{"id":"C","en":"Yes, if painted","hi":"हां, अगर पेंट किए हों"},{"id":"D","en":"Only at night","hi":"केवल रात में"}]'::jsonb, 'B', 5),
  ('Scaffolder', 'Why should scaffolding be inspected?', 'स्कैफोल्डिंग का निरीक्षण क्यों किया जाना चाहिए?', '[{"id":"A","en":"To identify unsafe or damaged components","hi":"असुरक्षित या क्षतिग्रस्त पार्ट्स की पहचान करने के लिए"},{"id":"B","en":"To change its colour","hi":"उसका रंग बदलने के लिए"},{"id":"C","en":"To increase its weight","hi":"उसका वजन बढ़ाने के लिए"},{"id":"D","en":"To make it easier to transport","hi":"उसे ले जाना आसान बनाने के लिए"}]'::jsonb, 'A', 6),
  ('Scaffolder', 'What should you do if scaffolding appears unsafe?', 'यदि स्कैफोल्डिंग असुरक्षित दिखाई दे तो क्या करना चाहिए?', '[{"id":"A","en":"Do not use it and inform the responsible person","hi":"इसका उपयोग न करें और जिम्मेदार व्यक्ति को सूचित करें"},{"id":"B","en":"Use it carefully anyway","hi":"फिर भी सावधानी से इस्तेमाल करें"},{"id":"C","en":"Remove random parts","hi":"कुछ भी पार्ट निकाल दें"},{"id":"D","en":"Ignore the problem","hi":"समस्या को नजरअंदाज करें"}]'::jsonb, 'A', 7),
  ('Scaffolder', 'Why should the scaffold platform be kept clear?', 'स्कैफोल्ड प्लेटफॉर्म को खाली/साफ क्यों रखना चाहिए?', '[{"id":"A","en":"To reduce trips and falling-object hazards","hi":"ठोकर और गिरने वाली वस्तुओं के खतरे को कम करने के लिए"},{"id":"B","en":"To store more waste","hi":"अधिक कचरा रखने के लिए"},{"id":"C","en":"To make the platform heavier","hi":"प्लेटफॉर्म को भारी बनाने के लिए"},{"id":"D","en":"To reduce working space","hi":"कार्य स्थान कम करने के लिए"}]'::jsonb, 'A', 8),
  ('Scaffolder', 'When working at height, what may be required in addition to normal PPE?', 'ऊंचाई पर काम करते समय सामान्य PPE के अलावा क्या आवश्यक हो सकता है?', '[{"id":"A","en":"Appropriate fall-protection equipment","hi":"उचित फॉल-प्रोटेक्शन उपकरण"},{"id":"B","en":"Swimming equipment","hi":"तैराकी उपकरण"},{"id":"C","en":"Cooking gloves","hi":"कुकिंग ग्लव्स"},{"id":"D","en":"Earphones","hi":"ईयरफोन"}]'::jsonb, 'A', 9),
  ('Scaffolder', 'What is one important hazard when working on scaffolding?', 'स्कैफोल्डिंग पर काम करते समय एक महत्वपूर्ण खतरा क्या है?', '[{"id":"A","en":"Falling from height","hi":"ऊंचाई से गिरना"},{"id":"B","en":"Getting wet from rain only","hi":"केवल बारिश में भीगना"},{"id":"C","en":"Losing a measuring tape","hi":"मेजरिंग टेप खोना"},{"id":"D","en":"Paint colour changing","hi":"पेंट का रंग बदलना"}]'::jsonb, 'A', 10),
  ('Painter', 'What is the main job of a painter?', 'पेंटर का मुख्य काम क्या होता है?', '[{"id":"A","en":"Preparing and painting surfaces","hi":"सतह तैयार करना और पेंट करना"},{"id":"B","en":"Installing electrical panels","hi":"इलेक्ट्रिकल पैनल लगाना"},{"id":"C","en":"Welding steel","hi":"स्टील वेल्ड करना"},{"id":"D","en":"Installing pipes","hi":"पाइप लगाना"}]'::jsonb, 'A', 1),
  ('Painter', 'What is a paint brush used for?', 'पेंट ब्रश का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Applying paint","hi":"पेंट लगाने के लिए"},{"id":"B","en":"Cutting wood","hi":"लकड़ी काटने के लिए"},{"id":"C","en":"Measuring voltage","hi":"वोल्टेज मापने के लिए"},{"id":"D","en":"Joining pipes","hi":"पाइप जोड़ने के लिए"}]'::jsonb, 'A', 2),
  ('Painter', 'What is a paint roller commonly used for?', 'पेंट रोलर का सामान्य उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Painting larger surfaces","hi":"बड़ी सतहों पर पेंट करने के लिए"},{"id":"B","en":"Cutting metal","hi":"धातु काटने के लिए"},{"id":"C","en":"Measuring pipes","hi":"पाइप मापने के लिए"},{"id":"D","en":"Welding","hi":"वेल्डिंग करने के लिए"}]'::jsonb, 'A', 3),
  ('Painter', 'Why is surface preparation important before painting?', 'पेंट करने से पहले सतह तैयार करना क्यों जरूरी है?', '[{"id":"A","en":"It helps the paint adhere properly and improves the finish","hi":"इससे पेंट अच्छी तरह चिपकता है और फिनिश बेहतर होती है"},{"id":"B","en":"It makes the wall heavier","hi":"दीवार भारी हो जाती है"},{"id":"C","en":"It increases electricity","hi":"बिजली बढ़ती है"},{"id":"D","en":"It makes paint dry before application","hi":"पेंट लगाने से पहले ही सूख जाता है"}]'::jsonb, 'A', 4),
  ('Painter', 'What is sandpaper used for?', 'सैंडपेपर का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Smoothing a surface","hi":"सतह को चिकना करने के लिए"},{"id":"B","en":"Mixing paint","hi":"पेंट मिलाने के लिए"},{"id":"C","en":"Measuring paint","hi":"पेंट मापने के लिए"},{"id":"D","en":"Cutting pipes","hi":"पाइप काटने के लिए"}]'::jsonb, 'A', 5),
  ('Painter', 'What is primer used for?', 'प्राइमर का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Preparing a surface before the final coat","hi":"अंतिम पेंट कोट से पहले सतह तैयार करने के लिए"},{"id":"B","en":"Cleaning electrical wires","hi":"इलेक्ट्रिकल तार साफ करने के लिए"},{"id":"C","en":"Cutting tiles","hi":"टाइल काटने के लिए"},{"id":"D","en":"Joining steel pipes","hi":"स्टील पाइप जोड़ने के लिए"}]'::jsonb, 'A', 6),
  ('Painter', 'Why should paint be mixed properly?', 'पेंट को अच्छी तरह मिलाना क्यों जरूरी है?', '[{"id":"A","en":"To achieve an even consistency","hi":"एक समान कंसिस्टेंसी प्राप्त करने के लिए"},{"id":"B","en":"To make the paint heavier","hi":"पेंट को भारी बनाने के लिए"},{"id":"C","en":"To increase electricity","hi":"बिजली बढ़ाने के लिए"},{"id":"D","en":"To make the brush harder","hi":"ब्रश को कठोर बनाने के लिए"}]'::jsonb, 'A', 7),
  ('Painter', 'Why is ventilation important when using certain paints?', 'कुछ प्रकार के पेंट इस्तेमाल करते समय वेंटिलेशन क्यों जरूरी है?', '[{"id":"A","en":"To reduce exposure to fumes","hi":"धुएं के संपर्क को कम करने के लिए"},{"id":"B","en":"To increase paint smell","hi":"पेंट की गंध बढ़ाने के लिए"},{"id":"C","en":"To make paint thicker","hi":"पेंट को गाढ़ा बनाने के लिए"},{"id":"D","en":"To make the wall wet","hi":"दीवार को गीला करने के लिए"}]'::jsonb, 'A', 8),
  ('Painter', 'What should you do if paint gets into your eyes?', 'यदि पेंट आंखों में चला जाए तो क्या करना चाहिए?', '[{"id":"A","en":"Rinse with clean water and report/seek appropriate medical attention","hi":"साफ पानी से धोकर सूचना दें और उचित चिकित्सा सहायता लें"},{"id":"B","en":"Rub your eyes","hi":"आंखों को रगड़ें"},{"id":"C","en":"Ignore it","hi":"नजरअंदाज करें"},{"id":"D","en":"Continue painting","hi":"पेंटिंग जारी रखें"}]'::jsonb, 'A', 9),
  ('Painter', 'Why should paint containers be closed when not in use?', 'इस्तेमाल न होने पर पेंट के डिब्बे बंद क्यों रखने चाहिए?', '[{"id":"A","en":"To prevent spills and unnecessary drying","hi":"गिरने और अनावश्यक रूप से सूखने से रोकने के लिए"},{"id":"B","en":"To increase paint temperature","hi":"पेंट का तापमान बढ़ाने के लिए"},{"id":"C","en":"To make the paint heavier","hi":"पेंट को भारी बनाने के लिए"},{"id":"D","en":"To change the colour","hi":"रंग बदलने के लिए"}]'::jsonb, 'A', 10),
  ('Aluminium Fixer/Fabricator', 'Where is aluminium commonly used in construction?', 'निर्माण कार्य में एल्युमिनियम का सामान्यतः उपयोग कहां किया जाता है?', '[{"id":"A","en":"Windows, doors and frames","hi":"खिड़कियों, दरवाजों और फ्रेम में"},{"id":"B","en":"Concrete foundations only","hi":"केवल कंक्रीट फाउंडेशन में"},{"id":"C","en":"Water tanks only","hi":"केवल पानी की टंकी में"},{"id":"D","en":"Electrical transformers only","hi":"केवल इलेक्ट्रिकल ट्रांसफॉर्मर में"}]'::jsonb, 'A', 1),
  ('Aluminium Fixer/Fabricator', 'What is an aluminium profile?', 'एल्युमिनियम प्रोफाइल क्या होती है?', '[{"id":"A","en":"A shaped aluminium section used to make frames or structures","hi":"फ्रेम या स्ट्रक्चर बनाने के लिए उपयोग की जाने वाली आकार वाली एल्युमिनियम सेक्शन"},{"id":"B","en":"A type of cement","hi":"एक प्रकार का सीमेंट"},{"id":"C","en":"A type of electrical cable","hi":"एक प्रकार की इलेक्ट्रिकल केबल"},{"id":"D","en":"A type of paint","hi":"एक प्रकार का पेंट"}]'::jsonb, 'A', 2),
  ('Aluminium Fixer/Fabricator', 'Why is accurate measurement important in aluminium fabrication?', 'एल्युमिनियम फैब्रिकेशन में सही माप क्यों जरूरी है?', '[{"id":"A","en":"To ensure the frame fits correctly","hi":"यह सुनिश्चित करने के लिए कि फ्रेम सही फिट हो"},{"id":"B","en":"To make aluminium heavier","hi":"एल्युमिनियम को भारी बनाने के लिए"},{"id":"C","en":"To increase electricity","hi":"बिजली बढ़ाने के लिए"},{"id":"D","en":"To change its colour","hi":"इसका रंग बदलने के लिए"}]'::jsonb, 'A', 3),
  ('Aluminium Fixer/Fabricator', 'What is a measuring tape used for?', 'मेजरिंग टेप का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Measuring dimensions","hi":"माप लेने के लिए"},{"id":"B","en":"Cutting aluminium","hi":"एल्युमिनियम काटने के लिए"},{"id":"C","en":"Painting aluminium","hi":"एल्युमिनियम पेंट करने के लिए"},{"id":"D","en":"Welding aluminium","hi":"एल्युमिनियम वेल्ड करने के लिए"}]'::jsonb, 'A', 4),
  ('Aluminium Fixer/Fabricator', 'What is a drill commonly used for?', 'ड्रिल का सामान्य उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Making holes for suitable fixing","hi":"उचित फिक्सिंग के लिए छेद बनाने के लिए"},{"id":"B","en":"Painting walls","hi":"दीवार पेंट करने के लिए"},{"id":"C","en":"Measuring temperature","hi":"तापमान मापने के लिए"},{"id":"D","en":"Mixing cement","hi":"सीमेंट मिलाने के लिए"}]'::jsonb, 'A', 5),
  ('Aluminium Fixer/Fabricator', 'What is a cutting machine used for in aluminium fabrication?', 'एल्युमिनियम फैब्रिकेशन में कटिंग मशीन का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Cutting aluminium profiles to the required size","hi":"एल्युमिनियम प्रोफाइल को आवश्यक आकार में काटने के लिए"},{"id":"B","en":"Measuring electricity","hi":"बिजली मापने के लिए"},{"id":"C","en":"Mixing paint","hi":"पेंट मिलाने के लिए"},{"id":"D","en":"Cleaning floors","hi":"फर्श साफ करने के लिए"}]'::jsonb, 'A', 6),
  ('Aluminium Fixer/Fabricator', 'Why should aluminium edges be handled carefully?', 'एल्युमिनियम के किनारों को सावधानी से क्यों संभालना चाहिए?', '[{"id":"A","en":"They can be sharp and cause cuts","hi":"वे तेज हो सकते हैं और कट लगा सकते हैं"},{"id":"B","en":"They can produce electricity","hi":"वे बिजली बना सकते हैं"},{"id":"C","en":"They can melt immediately","hi":"वे तुरंत पिघल सकते हैं"},{"id":"D","en":"They can absorb water","hi":"वे पानी सोख सकते हैं"}]'::jsonb, 'A', 7),
  ('Aluminium Fixer/Fabricator', 'What should be checked before installing an aluminium frame?', 'एल्युमिनियम फ्रेम लगाने से पहले क्या जांचना चाहिए?', '[{"id":"A","en":"Dimensions and alignment","hi":"माप और अलाइनमेंट"},{"id":"B","en":"Paint smell only","hi":"केवल पेंट की गंध"},{"id":"C","en":"Worker height","hi":"कर्मचारी की लंबाई"},{"id":"D","en":"Weather colour","hi":"मौसम का रंग"}]'::jsonb, 'A', 8),
  ('Aluminium Fixer/Fabricator', 'Which PPE can protect the eyes when cutting aluminium?', 'एल्युमिनियम काटते समय आंखों की सुरक्षा के लिए कौन सा PPE उपयोगी है?', '[{"id":"A","en":"Safety glasses","hi":"सेफ्टी ग्लास"},{"id":"B","en":"Safety shoes only","hi":"केवल सेफ्टी शूज़"},{"id":"C","en":"Cotton cap","hi":"सूती टोपी"},{"id":"D","en":"Earphones","hi":"ईयरफोन"}]'::jsonb, 'A', 9),
  ('Aluminium Fixer/Fabricator', 'What is a screw commonly used for in aluminium installation?', 'एल्युमिनियम इंस्टॉलेशन में स्क्रू का सामान्य उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Fixing or joining suitable components","hi":"उपयुक्त पार्ट्स को फिक्स या जोड़ने के लिए"},{"id":"B","en":"Measuring aluminium","hi":"एल्युमिनियम मापने के लिए"},{"id":"C","en":"Painting aluminium","hi":"एल्युमिनियम पेंट करने के लिए"},{"id":"D","en":"Cleaning glass","hi":"कांच साफ करने के लिए"}]'::jsonb, 'A', 10);
