REVOKE EXECUTE ON FUNCTION public.current_employer_org() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.employer_visible_fields() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.employer_field_map(uuid) FROM anon, PUBLIC, authenticated;
REVOKE EXECUTE ON FUNCTION public.employer_visible_worker_ids(uuid) FROM anon, PUBLIC, authenticated;
REVOKE EXECUTE ON FUNCTION public.employer_list_workers(text,text,text,integer,integer) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.employer_get_worker(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_list_employer_orgs() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_assign_workers(uuid,uuid[],text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_revoke_worker_assignment(uuid,uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_set_field_visibility(uuid,text,boolean) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_employer_org_workers(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.ensure_employer_org() FROM anon, PUBLIC, authenticated;
GRANT EXECUTE ON FUNCTION public.current_employer_org() TO authenticated;
GRANT EXECUTE ON FUNCTION public.employer_visible_fields() TO authenticated;
GRANT EXECUTE ON FUNCTION public.employer_list_workers(text,text,text,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.employer_get_worker(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_employer_orgs() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_assign_workers(uuid,uuid[],text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_revoke_worker_assignment(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_field_visibility(uuid,text,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_employer_org_workers(uuid) TO authenticated;