-- Replace cloned generic banks with dedicated screening papers for
-- MIG Welder, TIG Welder, Mason (bricks/plaster) and Dubai Cleaner (Male/Female).
-- Option order is shuffled at test time in loadQuizItems / loadQuizItemsFromJson.

INSERT INTO public.skill_quiz_configs
  (skill_code, region, questions_to_show, selection_mode, selected_ids, pass_score, active)
SELECT v.skill_code, NULL, 10, 'random_active', '{}'::uuid[], 60, true
FROM (VALUES
  ('MIG Welder'),
  ('TIG Welder'),
  ('Mason (bricks/plaster)'),
  ('Cleaner (Male)'),
  ('Cleaner (Female)')
) AS v(skill_code)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.skill_quiz_configs c
  WHERE c.skill_code = v.skill_code
    AND c.region IS NULL
);

UPDATE public.skill_quiz_configs
SET questions_to_show = 10,
    pass_score = 60,
    selection_mode = 'random_active',
    selected_ids = '{}'::uuid[],
    active = true,
    updated_at = now()
WHERE region IS NULL
  AND skill_code IN (
    'MIG Welder',
    'TIG Welder',
    'Mason (bricks/plaster)',
    'Cleaner (Male)',
    'Cleaner (Female)'
  );

DELETE FROM public.worker_skill_quiz_responses
WHERE quiz_item_id IN (
  SELECT id
  FROM public.worker_skill_quiz_items
  WHERE skill_code IN (
    'MIG Welder',
    'TIG Welder',
    'Mason (bricks/plaster)',
    'Cleaner (Male)',
    'Cleaner (Female)'
  )
);

DELETE FROM public.worker_skill_quiz_items
WHERE skill_code IN (
  'MIG Welder',
  'TIG Welder',
  'Mason (bricks/plaster)',
  'Cleaner (Male)',
  'Cleaner (Female)'
);

INSERT INTO public.worker_skill_quiz_items
  (skill_code, question, question_hi, options, correct_option, sort_order)
VALUES
  ('MIG Welder', 'What does MIG stand for?', 'MIG का पूरा नाम क्या है?', '[{"id":"A","en":"Metal Inert Gas","hi":"मेटल इनर्ट गैस"},{"id":"B","en":"Metal Iron Gas","hi":"मेटल आयरन गैस"},{"id":"C","en":"Manual Industrial Gas","hi":"मैनुअल इंडस्ट्रियल गैस"},{"id":"D","en":"Metal Internal Ground","hi":"मेटल इंटरनल ग्राउंड"}]'::jsonb, 'A', 1),
  ('MIG Welder', 'What is mainly used as the electrode in MIG welding?', 'MIG वेल्डिंग में मुख्य रूप से इलेक्ट्रोड के रूप में क्या उपयोग किया जाता है?', '[{"id":"A","en":"Welding rod","hi":"वेल्डिंग रॉड"},{"id":"B","en":"Continuous wire","hi":"लगातार चलने वाली वायर"},{"id":"C","en":"Copper plate","hi":"कॉपर प्लेट"},{"id":"D","en":"Steel pipe","hi":"स्टील पाइप"}]'::jsonb, 'B', 2),
  ('MIG Welder', 'What is the main purpose of shielding gas in MIG welding?', 'MIG वेल्डिंग में शील्डिंग गैस का मुख्य उद्देश्य क्या है?', '[{"id":"A","en":"To cool the worker","hi":"वर्कर को ठंडा करना"},{"id":"B","en":"To protect the weld from air contamination","hi":"वेल्ड को हवा से होने वाले प्रदूषण से बचाना"},{"id":"C","en":"To clean the floor","hi":"फर्श साफ करना"},{"id":"D","en":"To increase the weight of the metal","hi":"धातु का वजन बढ़ाना"}]'::jsonb, 'B', 3),
  ('MIG Welder', 'Which equipment protects the welder''s eyes and face from the welding arc?', 'वेल्डिंग आर्क से वेल्डर की आंखों और चेहरे की सुरक्षा के लिए कौन सा उपकरण उपयोग किया जाता है?', '[{"id":"A","en":"Safety helmet","hi":"सेफ्टी हेलमेट"},{"id":"B","en":"Welding helmet","hi":"वेल्डिंग हेलमेट"},{"id":"C","en":"Safety shoes","hi":"सेफ्टी शूज़"},{"id":"D","en":"Ear plugs","hi":"ईयर प्लग"}]'::jsonb, 'B', 4),
  ('MIG Welder', 'What is the purpose of the welding gun in MIG welding?', 'MIG वेल्डिंग में वेल्डिंग गन का क्या काम होता है?', '[{"id":"A","en":"To deliver the welding wire and shielding gas","hi":"वेल्डिंग वायर और शील्डिंग गैस पहुंचाना"},{"id":"B","en":"To measure metal thickness","hi":"धातु की मोटाई मापना"},{"id":"C","en":"To cut the metal","hi":"धातु काटना"},{"id":"D","en":"To clean the welding area","hi":"वेल्डिंग क्षेत्र साफ करना"}]'::jsonb, 'A', 5),
  ('MIG Welder', 'What should you do before starting MIG welding?', 'MIG वेल्डिंग शुरू करने से पहले आपको क्या करना चाहिए?', '[{"id":"A","en":"Check the welding machine, cables and PPE","hi":"वेल्डिंग मशीन, केबल और PPE की जांच करना"},{"id":"B","en":"Touch the welding wire with bare hands","hi":"वेल्डिंग वायर को नंगे हाथों से छूना"},{"id":"C","en":"Pour water on the machine","hi":"मशीन पर पानी डालना"},{"id":"D","en":"Remove the welding helmet","hi":"वेल्डिंग हेलमेट हटाना"}]'::jsonb, 'A', 6),
  ('MIG Welder', 'What can happen if the shielding gas flow is not proper?', 'यदि शील्डिंग गैस का फ्लो सही नहीं है तो क्या हो सकता है?', '[{"id":"A","en":"The weld may have defects","hi":"वेल्ड में खराबी आ सकती है"},{"id":"B","en":"The metal becomes plastic","hi":"धातु प्लास्टिक बन जाती है"},{"id":"C","en":"The welding machine becomes larger","hi":"वेल्डिंग मशीन बड़ी हो जाती है"},{"id":"D","en":"Nothing can happen","hi":"कुछ भी नहीं होता"}]'::jsonb, 'A', 7),
  ('MIG Welder', 'Why should the welding surface be clean before welding?', 'वेल्डिंग से पहले धातु की सतह को साफ क्यों करना चाहिए?', '[{"id":"A","en":"To improve the quality of the weld","hi":"वेल्ड की गुणवत्ता बेहतर करने के लिए"},{"id":"B","en":"To make the metal heavier","hi":"धातु को भारी बनाने के लिए"},{"id":"C","en":"To increase electricity consumption","hi":"बिजली की खपत बढ़ाने के लिए"},{"id":"D","en":"To change the metal colour","hi":"धातु का रंग बदलने के लिए"}]'::jsonb, 'A', 8),
  ('MIG Welder', 'What should a MIG welder do if the welding wire is not feeding properly?', 'यदि MIG वेल्डिंग वायर सही तरीके से फीड नहीं हो रही है तो वेल्डर को क्या करना चाहिए?', '[{"id":"A","en":"Check the wire feed and equipment","hi":"वायर फीड और उपकरण की जांच करनी चाहिए"},{"id":"B","en":"Pull the wire with bare hands while welding","hi":"वेल्डिंग के दौरान वायर को हाथ से खींचना चाहिए"},{"id":"C","en":"Pour water on the wire","hi":"वायर पर पानी डालना चाहिए"},{"id":"D","en":"Continue welding without checking","hi":"बिना जांचे वेल्डिंग जारी रखनी चाहिए"}]'::jsonb, 'A', 9),
  ('MIG Welder', 'Why should a welder wear protective gloves?', 'वेल्डर को सुरक्षात्मक ग्लव्स क्यों पहनने चाहिए?', '[{"id":"A","en":"To protect hands from heat, sparks and sharp metal","hi":"हाथों को गर्मी, चिंगारी और तेज धातु से बचाने के लिए"},{"id":"B","en":"To increase welding speed","hi":"वेल्डिंग की गति बढ़ाने के लिए"},{"id":"C","en":"To reduce the weight of the welding gun","hi":"वेल्डिंग गन का वजन कम करने के लिए"},{"id":"D","en":"To increase gas flow","hi":"गैस फ्लो बढ़ाने के लिए"}]'::jsonb, 'A', 10),
  ('TIG Welder', 'What does TIG stand for?', 'TIG का पूरा नाम क्या है?', '[{"id":"A","en":"Tungsten Inert Gas","hi":"टंगस्टन इनर्ट गैस"},{"id":"B","en":"Tungsten Industrial Gas","hi":"टंगस्टन इंडस्ट्रियल गैस"},{"id":"C","en":"Thermal Inert Gas","hi":"थर्मल इनर्ट गैस"},{"id":"D","en":"Tungsten Iron Gas","hi":"टंगस्टन आयरन गैस"}]'::jsonb, 'A', 1),
  ('TIG Welder', 'Which electrode is used in TIG welding?', 'TIG वेल्डिंग में किस प्रकार का इलेक्ट्रोड उपयोग किया जाता है?', '[{"id":"A","en":"Tungsten electrode","hi":"टंगस्टन इलेक्ट्रोड"},{"id":"B","en":"Copper electrode","hi":"कॉपर इलेक्ट्रोड"},{"id":"C","en":"Aluminium electrode","hi":"एल्युमिनियम इलेक्ट्रोड"},{"id":"D","en":"Wooden electrode","hi":"लकड़ी का इलेक्ट्रोड"}]'::jsonb, 'A', 2),
  ('TIG Welder', 'What is the main purpose of shielding gas in TIG welding?', 'TIG वेल्डिंग में शील्डिंग गैस का मुख्य उद्देश्य क्या है?', '[{"id":"A","en":"To protect the weld from air contamination","hi":"वेल्ड को हवा से होने वाले प्रदूषण से बचाना"},{"id":"B","en":"To cool the welding machine","hi":"वेल्डिंग मशीन को ठंडा करना"},{"id":"C","en":"To clean the floor","hi":"फर्श साफ करना"},{"id":"D","en":"To increase the weight of the metal","hi":"धातु का वजन बढ़ाना"}]'::jsonb, 'A', 3),
  ('TIG Welder', 'Which gas is commonly used as shielding gas in TIG welding?', 'TIG वेल्डिंग में शील्डिंग गैस के रूप में सामान्यतः किस गैस का उपयोग किया जाता है?', '[{"id":"A","en":"Argon","hi":"आर्गन"},{"id":"B","en":"Oxygen","hi":"ऑक्सीजन"},{"id":"C","en":"Hydrogen","hi":"हाइड्रोजन"},{"id":"D","en":"Carbon dioxide only","hi":"केवल कार्बन डाइऑक्साइड"}]'::jsonb, 'A', 4),
  ('TIG Welder', 'What is the purpose of a TIG welding torch?', 'TIG वेल्डिंग टॉर्च का क्या उद्देश्य है?', '[{"id":"A","en":"To hold the tungsten electrode and direct the shielding gas","hi":"टंगस्टन इलेक्ट्रोड को पकड़ना और शील्डिंग गैस को सही दिशा में पहुंचाना"},{"id":"B","en":"To measure metal thickness","hi":"धातु की मोटाई मापना"},{"id":"C","en":"To cut the metal","hi":"धातु काटना"},{"id":"D","en":"To mix welding gas","hi":"वेल्डिंग गैस मिलाना"}]'::jsonb, 'A', 5),
  ('TIG Welder', 'What should you wear to protect your eyes during TIG welding?', 'TIG वेल्डिंग के दौरान आंखों की सुरक्षा के लिए क्या पहनना चाहिए?', '[{"id":"A","en":"Welding helmet","hi":"वेल्डिंग हेलमेट"},{"id":"B","en":"Normal sunglasses","hi":"सामान्य धूप का चश्मा"},{"id":"C","en":"Cotton cap","hi":"सूती टोपी"},{"id":"D","en":"Ear plugs","hi":"ईयर प्लग"}]'::jsonb, 'A', 6),
  ('TIG Welder', 'What is a filler rod used for in TIG welding?', 'TIG वेल्डिंग में फिलर रॉड का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"To add additional metal to the weld when required","hi":"आवश्यकता होने पर वेल्ड में अतिरिक्त धातु जोड़ने के लिए"},{"id":"B","en":"To cool the metal","hi":"धातु को ठंडा करने के लिए"},{"id":"C","en":"To measure the weld","hi":"वेल्ड को मापने के लिए"},{"id":"D","en":"To clean the floor","hi":"फर्श साफ करने के लिए"}]'::jsonb, 'A', 7),
  ('TIG Welder', 'Why should the metal surface be cleaned before TIG welding?', 'TIG वेल्डिंग से पहले धातु की सतह को साफ क्यों करना चाहिए?', '[{"id":"A","en":"To improve weld quality","hi":"वेल्ड की गुणवत्ता बेहतर करने के लिए"},{"id":"B","en":"To make the metal heavier","hi":"धातु को भारी बनाने के लिए"},{"id":"C","en":"To increase gas pressure","hi":"गैस का दबाव बढ़ाने के लिए"},{"id":"D","en":"To change the metal colour","hi":"धातु का रंग बदलने के लिए"}]'::jsonb, 'A', 8),
  ('TIG Welder', 'What can happen if shielding gas is not supplied properly?', 'यदि शील्डिंग गैस सही तरीके से सप्लाई न हो तो क्या हो सकता है?', '[{"id":"A","en":"The weld can become defective or contaminated","hi":"वेल्ड में खराबी या प्रदूषण हो सकता है"},{"id":"B","en":"The metal becomes plastic","hi":"धातु प्लास्टिक बन जाती है"},{"id":"C","en":"The welding machine becomes larger","hi":"वेल्डिंग मशीन बड़ी हो जाती है"},{"id":"D","en":"Nothing happens","hi":"कुछ नहीं होता"}]'::jsonb, 'A', 9),
  ('TIG Welder', 'Why should a TIG welder wear protective gloves?', 'TIG वेल्डर को सुरक्षात्मक ग्लव्स क्यों पहनने चाहिए?', '[{"id":"A","en":"To protect hands from heat, sparks and sharp metal","hi":"हाथों को गर्मी, चिंगारी और तेज धातु से बचाने के लिए"},{"id":"B","en":"To increase welding speed","hi":"वेल्डिंग की गति बढ़ाने के लिए"},{"id":"C","en":"To increase gas flow","hi":"गैस फ्लो बढ़ाने के लिए"},{"id":"D","en":"To make the welding torch lighter","hi":"वेल्डिंग टॉर्च को हल्का बनाने के लिए"}]'::jsonb, 'A', 10),
  ('Mason (bricks/plaster)', 'What is the main work of a mason?', 'राजमिस्त्री का मुख्य काम क्या होता है?', '[{"id":"A","en":"Building walls and doing masonry work","hi":"दीवार बनाना और चिनाई का काम करना"},{"id":"B","en":"Repairing electrical panels","hi":"इलेक्ट्रिकल पैनल की मरम्मत करना"},{"id":"C","en":"Welding pipes","hi":"पाइप वेल्ड करना"},{"id":"D","en":"Repairing vehicles","hi":"वाहनों की मरम्मत करना"}]'::jsonb, 'A', 1),
  ('Mason (bricks/plaster)', 'What is mortar commonly used for?', 'मोर्टार का सामान्यतः उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Joining bricks or blocks","hi":"ईंटों या ब्लॉक्स को जोड़ने के लिए"},{"id":"B","en":"Cutting steel","hi":"स्टील काटने के लिए"},{"id":"C","en":"Painting walls","hi":"दीवारों पर पेंट करने के लिए"},{"id":"D","en":"Measuring electricity","hi":"बिजली मापने के लिए"}]'::jsonb, 'A', 2),
  ('Mason (bricks/plaster)', 'What are common materials used to make cement mortar?', 'सीमेंट मोर्टार बनाने में सामान्यतः किन सामग्रियों का उपयोग किया जाता है?', '[{"id":"A","en":"Cement, sand and water","hi":"सीमेंट, रेत और पानी"},{"id":"B","en":"Paint, oil and water","hi":"पेंट, तेल और पानी"},{"id":"C","en":"Steel, glass and water","hi":"स्टील, कांच और पानी"},{"id":"D","en":"Wood, paint and cement","hi":"लकड़ी, पेंट और सीमेंट"}]'::jsonb, 'A', 3),
  ('Mason (bricks/plaster)', 'What is a trowel used for?', 'ट्रॉवेल का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Applying and spreading mortar or plaster","hi":"मोर्टार या प्लास्टर लगाने और फैलाने के लिए"},{"id":"B","en":"Cutting electrical wires","hi":"विद्युत तार काटने के लिए"},{"id":"C","en":"Measuring voltage","hi":"वोल्टेज मापने के लिए"},{"id":"D","en":"Welding metal","hi":"धातु वेल्ड करने के लिए"}]'::jsonb, 'A', 4),
  ('Mason (bricks/plaster)', 'Why is a spirit level used in masonry work?', 'चिनाई के काम में स्पिरिट लेवल का उपयोग क्यों किया जाता है?', '[{"id":"A","en":"To check whether a surface is level","hi":"यह जांचने के लिए कि सतह सीधी और लेवल में है"},{"id":"B","en":"To cut bricks","hi":"ईंट काटने के लिए"},{"id":"C","en":"To mix cement","hi":"सीमेंट मिलाने के लिए"},{"id":"D","en":"To measure water temperature","hi":"पानी का तापमान मापने के लिए"}]'::jsonb, 'A', 5),
  ('Mason (bricks/plaster)', 'Why is proper alignment important when building a wall?', 'दीवार बनाते समय सही अलाइनमेंट क्यों जरूरी है?', '[{"id":"A","en":"To make the wall straight and properly positioned","hi":"दीवार को सीधा और सही स्थिति में बनाने के लिए"},{"id":"B","en":"To make the wall heavier","hi":"दीवार को भारी बनाने के लिए"},{"id":"C","en":"To increase the colour of the wall","hi":"दीवार का रंग बढ़ाने के लिए"},{"id":"D","en":"To make cement dry immediately","hi":"सीमेंट को तुरंत सुखाने के लिए"}]'::jsonb, 'A', 6),
  ('Mason (bricks/plaster)', 'What is plastering?', 'प्लास्टरिंग क्या है?', '[{"id":"A","en":"Applying a layer of plaster/mortar to a surface","hi":"सतह पर प्लास्टर/मोर्टार की परत लगाना"},{"id":"B","en":"Cutting steel bars","hi":"स्टील बार काटना"},{"id":"C","en":"Joining electrical wires","hi":"विद्युत तार जोड़ना"},{"id":"D","en":"Installing pipes","hi":"पाइप लगाना"}]'::jsonb, 'A', 7),
  ('Mason (bricks/plaster)', 'Why should the wall surface be cleaned before plastering?', 'प्लास्टर करने से पहले दीवार की सतह को साफ क्यों करना चाहिए?', '[{"id":"A","en":"To help the plaster bond properly","hi":"प्लास्टर को सतह पर अच्छी तरह चिपकने में मदद करने के लिए"},{"id":"B","en":"To increase dust","hi":"धूल बढ़ाने के लिए"},{"id":"C","en":"To make the wall heavier","hi":"दीवार को भारी बनाने के लिए"},{"id":"D","en":"To change the wall colour","hi":"दीवार का रंग बदलने के लिए"}]'::jsonb, 'A', 8),
  ('Mason (bricks/plaster)', 'What should you do if a brick or block is damaged?', 'यदि कोई ईंट या ब्लॉक क्षतिग्रस्त हो तो क्या करना चाहिए?', '[{"id":"A","en":"Use it without checking","hi":"बिना जांचे इस्तेमाल करना"},{"id":"B","en":"Use a suitable undamaged brick/block or follow the supervisor''s instruction","hi":"सही और बिना क्षतिग्रस्त ईंट/ब्लॉक का उपयोग करना या सुपरवाइजर के निर्देश का पालन करना"},{"id":"C","en":"Hide it inside the wall","hi":"उसे दीवार के अंदर छिपा देना"},{"id":"D","en":"Throw it at another worker","hi":"उसे दूसरे कर्मचारी पर फेंकना"}]'::jsonb, 'B', 9),
  ('Mason (bricks/plaster)', 'Which PPE is important for a mason working on a construction site?', 'कंस्ट्रक्शन साइट पर काम करने वाले राजमिस्त्री के लिए कौन सा PPE महत्वपूर्ण है?', '[{"id":"A","en":"Safety helmet and safety shoes","hi":"सेफ्टी हेलमेट और सेफ्टी शूज़"},{"id":"B","en":"Sunglasses and slippers","hi":"धूप का चश्मा और चप्पल"},{"id":"C","en":"Earphones and sandals","hi":"ईयरफोन और सैंडल"},{"id":"D","en":"Normal clothes only","hi":"केवल सामान्य कपड़े"}]'::jsonb, 'A', 10),
  ('Cleaner (Male)', 'What is the main duty of a cleaner?', 'क्लीनर का मुख्य काम क्या होता है?', '[{"id":"A","en":"Cleaning and maintaining cleanliness","hi":"सफाई करना और स्वच्छता बनाए रखना"},{"id":"B","en":"Repairing electrical machines","hi":"इलेक्ट्रिकल मशीनों की मरम्मत करना"},{"id":"C","en":"Welding metal","hi":"धातु वेल्ड करना"},{"id":"D","en":"Installing pipes","hi":"पाइप लगाना"}]'::jsonb, 'A', 1),
  ('Cleaner (Male)', 'Which tool is commonly used to clean floors?', 'फर्श साफ करने के लिए सामान्यतः किस उपकरण का उपयोग किया जाता है?', '[{"id":"A","en":"Mop","hi":"पोछा"},{"id":"B","en":"Welding machine","hi":"वेल्डिंग मशीन"},{"id":"C","en":"Pipe wrench","hi":"पाइप रिंच"},{"id":"D","en":"Hammer","hi":"हथौड़ा"}]'::jsonb, 'A', 2),
  ('Cleaner (Male)', 'What is a broom mainly used for?', 'झाड़ू का मुख्य उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Sweeping dust and dirt","hi":"धूल और गंदगी साफ करने के लिए"},{"id":"B","en":"Washing windows","hi":"खिड़कियां धोने के लिए"},{"id":"C","en":"Cutting materials","hi":"सामग्री काटने के लिए"},{"id":"D","en":"Repairing machines","hi":"मशीनों की मरम्मत करने के लिए"}]'::jsonb, 'A', 3),
  ('Cleaner (Male)', 'Why should cleaning chemicals be used carefully?', 'सफाई के केमिकल का सावधानी से उपयोग क्यों करना चाहिए?', '[{"id":"A","en":"They may cause harm if used incorrectly","hi":"गलत तरीके से उपयोग करने पर वे नुकसान पहुंचा सकते हैं"},{"id":"B","en":"They make the floor heavier","hi":"वे फर्श को भारी बनाते हैं"},{"id":"C","en":"They increase electricity","hi":"वे बिजली बढ़ाते हैं"},{"id":"D","en":"They make tools stronger","hi":"वे उपकरणों को मजबूत बनाते हैं"}]'::jsonb, 'A', 4),
  ('Cleaner (Male)', 'What should you wear when handling cleaning chemicals?', 'सफाई के केमिकल को संभालते समय क्या पहनना चाहिए?', '[{"id":"A","en":"Appropriate protective gloves","hi":"उचित सुरक्षा ग्लव्स"},{"id":"B","en":"Slippers only","hi":"केवल चप्पल"},{"id":"C","en":"No protection","hi":"कोई सुरक्षा नहीं"},{"id":"D","en":"Loose jewellery","hi":"ढीली ज्वेलरी"}]'::jsonb, 'A', 5),
  ('Cleaner (Male)', 'What should you do if the floor is wet after cleaning?', 'सफाई के बाद यदि फर्श गीला है तो क्या करना चाहिए?', '[{"id":"A","en":"Put a warning sign and allow it to dry","hi":"चेतावनी संकेत लगाएं और फर्श को सूखने दें"},{"id":"B","en":"Leave it without any warning","hi":"बिना चेतावनी के छोड़ दें"},{"id":"C","en":"Pour more water","hi":"और पानी डालें"},{"id":"D","en":"Cover it with dust","hi":"उस पर धूल डालें"}]'::jsonb, 'A', 6),
  ('Cleaner (Male)', 'What is a vacuum cleaner used for?', 'वैक्यूम क्लीनर का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Removing dust and dirt","hi":"धूल और गंदगी हटाने के लिए"},{"id":"B","en":"Cutting metal","hi":"धातु काटने के लिए"},{"id":"C","en":"Painting walls","hi":"दीवार पेंट करने के लिए"},{"id":"D","en":"Carrying water","hi":"पानी ले जाने के लिए"}]'::jsonb, 'A', 7),
  ('Cleaner (Male)', 'What should you do with waste after collecting it?', 'कचरा इकट्ठा करने के बाद क्या करना चाहिए?', '[{"id":"A","en":"Put it in the appropriate waste bin or disposal area","hi":"उसे उचित कूड़ेदान या निर्धारित स्थान पर डालना"},{"id":"B","en":"Leave it on the floor","hi":"फर्श पर छोड़ देना"},{"id":"C","en":"Hide it behind furniture","hi":"फर्नीचर के पीछे छिपा देना"},{"id":"D","en":"Throw it anywhere","hi":"कहीं भी फेंक देना"}]'::jsonb, 'A', 8),
  ('Cleaner (Male)', 'Why is hand hygiene important for a cleaner?', 'क्लीनर के लिए हाथों की स्वच्छता क्यों जरूरी है?', '[{"id":"A","en":"To maintain hygiene and reduce the spread of germs","hi":"स्वच्छता बनाए रखने और कीटाणुओं के फैलाव को कम करने के लिए"},{"id":"B","en":"To make hands stronger","hi":"हाथों को मजबूत बनाने के लिए"},{"id":"C","en":"To increase cleaning speed","hi":"सफाई की गति बढ़ाने के लिए"},{"id":"D","en":"To save cleaning chemicals","hi":"सफाई के केमिकल बचाने के लिए"}]'::jsonb, 'A', 9),
  ('Cleaner (Male)', 'What should you do if you find a broken glass while cleaning?', 'सफाई करते समय यदि टूटा हुआ कांच मिले तो क्या करना चाहिए?', '[{"id":"A","en":"Handle it safely using appropriate protection and dispose of it properly","hi":"उचित सुरक्षा के साथ सावधानी से संभालकर सही तरीके से निपटाना"},{"id":"B","en":"Pick it up with bare hands","hi":"नंगे हाथों से उठाना"},{"id":"C","en":"Kick it away","hi":"उसे पैर से दूर करना"},{"id":"D","en":"Leave it where it is without reporting","hi":"बिना बताए वहीं छोड़ देना"}]'::jsonb, 'A', 10),
  ('Cleaner (Female)', 'What is the main duty of a cleaner?', 'क्लीनर का मुख्य काम क्या होता है?', '[{"id":"A","en":"Cleaning and maintaining cleanliness","hi":"सफाई करना और स्वच्छता बनाए रखना"},{"id":"B","en":"Repairing electrical machines","hi":"इलेक्ट्रिकल मशीनों की मरम्मत करना"},{"id":"C","en":"Welding metal","hi":"धातु वेल्ड करना"},{"id":"D","en":"Installing pipes","hi":"पाइप लगाना"}]'::jsonb, 'A', 1),
  ('Cleaner (Female)', 'Which tool is commonly used to clean floors?', 'फर्श साफ करने के लिए सामान्यतः किस उपकरण का उपयोग किया जाता है?', '[{"id":"A","en":"Mop","hi":"पोछा"},{"id":"B","en":"Welding machine","hi":"वेल्डिंग मशीन"},{"id":"C","en":"Pipe wrench","hi":"पाइप रिंच"},{"id":"D","en":"Hammer","hi":"हथौड़ा"}]'::jsonb, 'A', 2),
  ('Cleaner (Female)', 'What is a broom mainly used for?', 'झाड़ू का मुख्य उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Sweeping dust and dirt","hi":"धूल और गंदगी साफ करने के लिए"},{"id":"B","en":"Washing windows","hi":"खिड़कियां धोने के लिए"},{"id":"C","en":"Cutting materials","hi":"सामग्री काटने के लिए"},{"id":"D","en":"Repairing machines","hi":"मशीनों की मरम्मत करने के लिए"}]'::jsonb, 'A', 3),
  ('Cleaner (Female)', 'Why should cleaning chemicals be used carefully?', 'सफाई के केमिकल का सावधानी से उपयोग क्यों करना चाहिए?', '[{"id":"A","en":"They may cause harm if used incorrectly","hi":"गलत तरीके से उपयोग करने पर वे नुकसान पहुंचा सकते हैं"},{"id":"B","en":"They make the floor heavier","hi":"वे फर्श को भारी बनाते हैं"},{"id":"C","en":"They increase electricity","hi":"वे बिजली बढ़ाते हैं"},{"id":"D","en":"They make tools stronger","hi":"वे उपकरणों को मजबूत बनाते हैं"}]'::jsonb, 'A', 4),
  ('Cleaner (Female)', 'What should you wear when handling cleaning chemicals?', 'सफाई के केमिकल को संभालते समय क्या पहनना चाहिए?', '[{"id":"A","en":"Appropriate protective gloves","hi":"उचित सुरक्षा ग्लव्स"},{"id":"B","en":"Slippers only","hi":"केवल चप्पल"},{"id":"C","en":"No protection","hi":"कोई सुरक्षा नहीं"},{"id":"D","en":"Loose jewellery","hi":"ढीली ज्वेलरी"}]'::jsonb, 'A', 5),
  ('Cleaner (Female)', 'What should you do if the floor is wet after cleaning?', 'सफाई के बाद यदि फर्श गीला है तो क्या करना चाहिए?', '[{"id":"A","en":"Put a warning sign and allow it to dry","hi":"चेतावनी संकेत लगाएं और फर्श को सूखने दें"},{"id":"B","en":"Leave it without any warning","hi":"बिना चेतावनी के छोड़ दें"},{"id":"C","en":"Pour more water","hi":"और पानी डालें"},{"id":"D","en":"Cover it with dust","hi":"उस पर धूल डालें"}]'::jsonb, 'A', 6),
  ('Cleaner (Female)', 'What is a vacuum cleaner used for?', 'वैक्यूम क्लीनर का उपयोग किस लिए किया जाता है?', '[{"id":"A","en":"Removing dust and dirt","hi":"धूल और गंदगी हटाने के लिए"},{"id":"B","en":"Cutting metal","hi":"धातु काटने के लिए"},{"id":"C","en":"Painting walls","hi":"दीवार पेंट करने के लिए"},{"id":"D","en":"Carrying water","hi":"पानी ले जाने के लिए"}]'::jsonb, 'A', 7),
  ('Cleaner (Female)', 'What should you do with waste after collecting it?', 'कचरा इकट्ठा करने के बाद क्या करना चाहिए?', '[{"id":"A","en":"Put it in the appropriate waste bin or disposal area","hi":"उसे उचित कूड़ेदान या निर्धारित स्थान पर डालना"},{"id":"B","en":"Leave it on the floor","hi":"फर्श पर छोड़ देना"},{"id":"C","en":"Hide it behind furniture","hi":"फर्नीचर के पीछे छिपा देना"},{"id":"D","en":"Throw it anywhere","hi":"कहीं भी फेंक देना"}]'::jsonb, 'A', 8),
  ('Cleaner (Female)', 'Why is hand hygiene important for a cleaner?', 'क्लीनर के लिए हाथों की स्वच्छता क्यों जरूरी है?', '[{"id":"A","en":"To maintain hygiene and reduce the spread of germs","hi":"स्वच्छता बनाए रखने और कीटाणुओं के फैलाव को कम करने के लिए"},{"id":"B","en":"To make hands stronger","hi":"हाथों को मजबूत बनाने के लिए"},{"id":"C","en":"To increase cleaning speed","hi":"सफाई की गति बढ़ाने के लिए"},{"id":"D","en":"To save cleaning chemicals","hi":"सफाई के केमिकल बचाने के लिए"}]'::jsonb, 'A', 9),
  ('Cleaner (Female)', 'What should you do if you find a broken glass while cleaning?', 'सफाई करते समय यदि टूटा हुआ कांच मिले तो क्या करना चाहिए?', '[{"id":"A","en":"Handle it safely using appropriate protection and dispose of it properly","hi":"उचित सुरक्षा के साथ सावधानी से संभालकर सही तरीके से निपटाना"},{"id":"B","en":"Pick it up with bare hands","hi":"नंगे हाथों से उठाना"},{"id":"C","en":"Kick it away","hi":"उसे पैर से दूर करना"},{"id":"D","en":"Leave it where it is without reporting","hi":"बिना बताए वहीं छोड़ देना"}]'::jsonb, 'A', 10);
