/* Generated by scripts/import-india-post-offices.mjs. Do not edit. */
export type LocalityPack = Record<string, [string, string[]][]>;

export async function loadPackedLocalities(slug: string): Promise<LocalityPack> {
  switch (slug) {
    case 'andaman-and-nicobar-islands':
      return (await import('./localities/andaman-and-nicobar-islands.json')).default as LocalityPack;
    case 'andhra-pradesh':
      return (await import('./localities/andhra-pradesh.json')).default as LocalityPack;
    case 'arunachal-pradesh':
      return (await import('./localities/arunachal-pradesh.json')).default as LocalityPack;
    case 'assam':
      return (await import('./localities/assam.json')).default as LocalityPack;
    case 'bihar':
      return (await import('./localities/bihar.json')).default as LocalityPack;
    case 'chandigarh':
      return (await import('./localities/chandigarh.json')).default as LocalityPack;
    case 'chhattisgarh':
      return (await import('./localities/chhattisgarh.json')).default as LocalityPack;
    case 'dadra-and-nagar-haveli':
      return (await import('./localities/dadra-and-nagar-haveli.json')).default as LocalityPack;
    case 'daman-and-diu':
      return (await import('./localities/daman-and-diu.json')).default as LocalityPack;
    case 'delhi':
      return (await import('./localities/delhi.json')).default as LocalityPack;
    case 'goa':
      return (await import('./localities/goa.json')).default as LocalityPack;
    case 'gujarat':
      return (await import('./localities/gujarat.json')).default as LocalityPack;
    case 'haryana':
      return (await import('./localities/haryana.json')).default as LocalityPack;
    case 'himachal-pradesh':
      return (await import('./localities/himachal-pradesh.json')).default as LocalityPack;
    case 'jammu-and-kashmir':
      return (await import('./localities/jammu-and-kashmir.json')).default as LocalityPack;
    case 'jharkhand':
      return (await import('./localities/jharkhand.json')).default as LocalityPack;
    case 'karnataka':
      return (await import('./localities/karnataka.json')).default as LocalityPack;
    case 'kerala':
      return (await import('./localities/kerala.json')).default as LocalityPack;
    case 'ladakh':
      return (await import('./localities/ladakh.json')).default as LocalityPack;
    case 'lakshadweep':
      return (await import('./localities/lakshadweep.json')).default as LocalityPack;
    case 'madhya-pradesh':
      return (await import('./localities/madhya-pradesh.json')).default as LocalityPack;
    case 'maharashtra':
      return (await import('./localities/maharashtra.json')).default as LocalityPack;
    case 'manipur':
      return (await import('./localities/manipur.json')).default as LocalityPack;
    case 'meghalaya':
      return (await import('./localities/meghalaya.json')).default as LocalityPack;
    case 'mizoram':
      return (await import('./localities/mizoram.json')).default as LocalityPack;
    case 'nagaland':
      return (await import('./localities/nagaland.json')).default as LocalityPack;
    case 'odisha':
      return (await import('./localities/odisha.json')).default as LocalityPack;
    case 'puducherry':
      return (await import('./localities/puducherry.json')).default as LocalityPack;
    case 'punjab':
      return (await import('./localities/punjab.json')).default as LocalityPack;
    case 'rajasthan':
      return (await import('./localities/rajasthan.json')).default as LocalityPack;
    case 'sikkim':
      return (await import('./localities/sikkim.json')).default as LocalityPack;
    case 'tamil-nadu':
      return (await import('./localities/tamil-nadu.json')).default as LocalityPack;
    case 'telangana':
      return (await import('./localities/telangana.json')).default as LocalityPack;
    case 'tripura':
      return (await import('./localities/tripura.json')).default as LocalityPack;
    case 'uttar-pradesh':
      return (await import('./localities/uttar-pradesh.json')).default as LocalityPack;
    case 'uttarakhand':
      return (await import('./localities/uttarakhand.json')).default as LocalityPack;
    case 'west-bengal':
      return (await import('./localities/west-bengal.json')).default as LocalityPack;
    default:
      throw new Error(`No locality pack for ${slug}`);
  }
}
